### ISSUE TITLE
run error (no py3d found)

### ISSUE THREAD

**Issue by amiltonwong** [IntelVCL/Open3D#129]
Hi, all,

I followed the build [guide](http://www.open3d.org/docs/getting_started.html#ubuntu) . The build process has passed with success. The `py3d.cpython-35m-x86_64-linux-gnu.so` is generated at `build/lib/` after build process.

However, when I run the following commands:
```
cd lib/Tutorial/Basic
python rgbd_redwood.py
```
I encounter the following error:
```
Traceback (most recent call last):
  File "rgbd_redwood.py", line 9, in <module>
    from py3d import *
ImportError: No module named py3d
```
It seems `py3d` is not found. What steps should I perform for this issue?

(My system is ubuntu 16.04, python 3.5)

**Comment by syncle** [comment]
Few suggestions:

- Can you check that Python versions detected by cmake and your python environment matches? If you type ``python`` in terminal it should say version 3.5.
- Can you move to ``build/lib/`` and try
```
python
from py3d import *
```

**Comment by amiltonwong** [comment]
Thanks @syncle ,
Yes, you're right. I have to specify py3.5 in cmake process. And this suggestion works :)

**Comment by mbouhallel** [comment]
Hi @syncle , what if the second suggestion doesn't work either ?
I feel like open3d isn't getting installed properly. I tried
`sudo pip install open3d`
and : `sudo apt-get install open3d`

**Comment by syncle** [comment]
@mbouhallel: please install open3d by using ``pip install open3d-python``. ``pip install open3d`` will install other 3rd party package that is not the libarary we are developing. We are not supporting ``apt-get`` yet, so ``sudo apt-get install open3d`` will not work. 

Please check http://open3d.org/docs/getting_started.html for more details.

**Comment by mbouhallel** [comment]
@syncle thank you for responding, actually I think that the problem for me is that I'm running your project on a 32 bits Ubuntu. I'm trying to compile the project from source, but got problems with the architecture on every dependency (pytest is the latest). I think it's just better for me to install a 64 bits Ubuntu for a clean use.

**Comment by mbouhallel** [comment]
Reinstalled Ubuntu with a 64 bits architecture, got no problem with open3d (pip install open3d), but py3d is still not working, but unlike @amiltonwong I can run rgbd_redwood with no issues. However I cannot import py3d (even from /build/lib/)
