### ISSUE TITLE
Updates for Open3D document

### ISSUE THREAD

**Issue by syncle** [IntelVCL/Open3D#132]
There are some questions regarding basic usage of Open3D. 
Revising/adding [Open3D document](http://open3d.org/docs) for those questions will be helpful for users.

I will work on this after collecting more questions.
At this moment, this issue relates to #131 #130 #129.

**Comment by csukuangfj** [comment]
Doxygen style documentation is needed and is very helpful for developers.

**Comment by syncle** [comment]
That's very good suggestion. Doxygen document will give reference for c++ API. Working on it.
