### ISSUE TITLE
Error when trying to display point cloud

### ISSUE THREAD

**Issue by aeoleader** [IntelVCL/Open3D#135]
```
import sys
import numpy as np
sys.path.append("../..")
import py3d

pcd = py3d.read_point_cloud("./test.ply")
py3d.draw_geometries([pcd])
```
And I get the following error:
GLFW Error: GLX: Failed to create context: BadValue (integer parameter out of range for operation)
Failed to create window
[DrawGeometry] Failed creating OpenGL window.

Can anyone help me with this?

**Comment by syncle** [comment]
Umm, it is error message from GLFW. It seems like your environment does not support OpenGL. Does your graphical hardware correctly setup? Are you working with remote machine? It would be helpful for others if you share your environment, or configuration for compilation.

**Comment by aeoleader** [comment]
I am remotely accessing the machine in question via VNC. OpenGL had been working fine before I ran the setup scripts coming with open3d, but after, the all the programs using GL stopped working. 

EDIT:
I fixed it by reinstalling x-org and restarting. I don't know exactly why it worked but at least it is working now :))

**Comment by lukaspistelak** [comment]
hello i have same issue i am on remote ssh -X -C 

echo $DISPLAY
localhost:13.0

**Comment by maxjaritz** [comment]
@lukaspistelak Have you found a solution?

**Comment by YangJae96** [comment]
Hi, I am also having problem with remote Ubuntu using VNC Server.
How did you solve the problem?

**Comment by mdabdk** [comment]
For future readers, it turns out that my NVIDIA drivers were not installed correctly. I fixed this problem by running `sudo apt --fix-broken install` followed by `sudo reboot`.
