### ISSUE TITLE
About RegistrationICP &Multiway Registration

### ISSUE THREAD

**Issue by Joezzr** [IntelVCL/Open3D#137]
I've just tested Registration and Multiway Registration, but I can't get any good result. Here is my code, any wrong?
```
	std::vector< std::shared_ptr<PointCloud> > pcds;
	std::vector< std::shared_ptr<PointCloud> > pcdsOri;


	for (int i = 1; i <= 3; ++i)
	{
		auto pcd = CreatePointCloudFromFile(argv[i]);
		auto pcd_down = VoxelDownSample(*pcd, 0.02);
		pcds.push_back(pcd_down);
		pcdsOri.push_back(pcd);
	}
	//DrawGeometries({pcdsOri[0], pcdsOri[1], pcdsOri[2]});
	DrawGeometries({ pcds[0], pcds[1], pcds[2] });
	
	PoseGraph pose_graph;

	Eigen::Matrix4d	odometry;
	odometry.Identity();
	pose_graph.nodes_.push_back(PoseGraphNode(odometry));

	for (int source_id = 0; source_id < 3; ++source_id)
	{
		for (int target_id = source_id + 1; target_id < 3; ++target_id)
		{
			auto source = pcds[source_id];
			auto target = pcds[target_id];

			printf("Apply point-to-plane ICP");
			auto icp_coarse = RegistrationICP(*source, *target, 0.3, Eigen::Matrix4d::Identity(), TransformationEstimationPointToPlane());
			auto icp_fine = RegistrationICP(*source, *target, 0.03, icp_coarse.transformation_, TransformationEstimationPointToPlane());
			auto transformation_icp = icp_fine.transformation_;
			auto trans = transformation_icp * icp_coarse.transformation_;
			auto information_icp = GetInformationMatrixFromPointClouds(*source, *target, 0.03, icp_fine.transformation_);
			std::cout << icp_coarse.transformation_ << std::endl << icp_fine.transformation_;
			VisualizeRegistration(*source, *target, icp_fine.transformation_);

			printf("Build PoseGraph");
			if (target_id == source_id + 1) // # odometry case
			{
				//auto om = transformation_icp.dot(odometry);//Eigen::Matrix4d::dot(transformation_icp, odometry);

				pose_graph.nodes_.push_back(PoseGraphNode(transformation_icp.inverse()));
				pose_graph.edges_.push_back(PoseGraphEdge(source_id, target_id, transformation_icp, information_icp, false));
			}
			else//: # loop closure case
			{
				pose_graph.edges_.push_back(PoseGraphEdge(source_id, target_id, transformation_icp, information_icp, true));
			}
		}
	}

	printf("Optimizing PoseGraph ...");
	GlobalOptimizationConvergenceCriteria criteria;
	GlobalOptimizationOption option(0.03, 0.25, 0);
	GlobalOptimizationLevenbergMarquardt optimization_method;
	GlobalOptimization(pose_graph, optimization_method, criteria, option);


	printf("Transform points and display");
	std::vector<std::shared_ptr<const Geometry>> pcds2;
	
		for (int point_id = 0; point_id < 3; ++point_id)
		{
			//print(pose_graph.nodes[point_id].pose)
			pcds[point_id]->Transform(pose_graph.nodes_[point_id].pose_);
			pcdsOri[point_id]->Transform(pose_graph.nodes_[point_id].pose_);
//			visualizer.AddGeometry(pcds[point_id]);
			pcds2.push_back(pcdsOri[point_id]);
		}


	DrawGeometries(pcds2);
```

**Comment by syncle** [comment]
The cpp code presumably looks good. Can you check each point cloud pairs are well aligned? It might be necessary to tune point-to-plane ICP parameters.

**Comment by Joezzr** [comment]
I'll show you some results.
input data:
![image](https://user-images.githubusercontent.com/5101183/35951639-3f6db680-0cb7-11e8-8de6-229f61681953.png)

cloud_bin_0.pcd & cloud_bin_1.pcd result:
![image](https://user-images.githubusercontent.com/5101183/35951675-6de7a552-0cb7-11e8-8b43-82a7be671f49.png)

cloud_bin_0.pcd & cloud_bin_2.pcd result:
![image](https://user-images.githubusercontent.com/5101183/35951739-ac9a9fe8-0cb7-11e8-9541-882ec55a303f.png)

cloud_bin_1.pcd & cloud_bin_2.pcd result:
![image](https://user-images.githubusercontent.com/5101183/35951770-cc49d99e-0cb7-11e8-8473-1bd9a7092e17.png)

and here is final result:
![image](https://user-images.githubusercontent.com/5101183/35951790-ee1ce4da-0cb7-11e8-9932-d9edd7279e5a.png)

I think the metrics are wrong, but I have no idea why. @syncle

**Comment by syncle** [comment]
You're trying to mimic [Python tutorial](http://open3d.org/docs/tutorial/Advanced/multiway_registration.html) using c++. Does the same thing happens when you run `src/Python/Tutorial/Advanced/multiway_registration.py`? If the python tutorial runs well, something is wrong with your cpp example. Please check your transformation matrices, and play with toy example first to check ICP result.

**Comment by Joezzr** [comment]
python tutorial runs well, I'll check ICP result.

**Comment by qianyizh** [comment]
Hi Joezzr,

Try to remove this line:
```
			auto transformation_icp = icp_fine.transformation_;
```

You don't need to multiply the two matrices. The second ``Registration_ICP`` function simply takes ``icp_coarse.transformation_`` as initialization and computes the final transformation that aligns ``source`` to ``target``.

**Comment by qianyizh** [comment]
Btw, it is amazing to see the C++ interface being used. I thought everyone would love the python binding and forget about C++. Clearly I was wrong, :sweat:

**Comment by Joezzr** [comment]
Thanks, @qianyizh, I still have a problem, I can't get a right result of GlobalOptimization.
I am trying to mimic Python code using C++
`{
print("Build PoseGraph")
			if target_id == source_id + 1: # odometry case
				odometry = np.dot(transformation_icp, odometry)
				pose_graph.nodes.append(
						PoseGraphNode(np.linalg.inv(odometry)))
				pose_graph.edges.append(
						PoseGraphEdge(source_id, target_id,
						transformation_icp, information_icp, uncertain = False))
			else: # loop closure case
				pose_graph.edges.append(
						PoseGraphEdge(source_id, target_id,
						transformation_icp, information_icp, uncertain = True))

C++ code:
if (target_id == source_id + 1) // # odometry case
			{
				//auto om = transformation_icp.dot(odometry);//Eigen::Matrix4d::dot(transformation_icp, odometry);

				pose_graph.nodes_.push_back(PoseGraphNode(transformation_icp.inverse()));
				pose_graph.edges_.push_back(PoseGraphEdge(source_id, target_id, transformation_icp, information_icp, false));
			}
			else//: # loop closure case
			{
				pose_graph.edges_.push_back(PoseGraphEdge(source_id, target_id, transformation_icp, information_icp, true));
			}
}
`

What's wrong with the C++ code?

**Comment by qianyizh** [comment]
Try this:

```
Eigen::Matrix4d odometry = Eigen::Matrix4d::Identity();

...

if (target_id == source_id + 1) // # odometry case
{
	odometry = transformation_icp * odometry;
	pose_graph.nodes_.push_back(PoseGraphNode(odometry.inverse()));
	pose_graph.edges_.push_back(PoseGraphEdge(source_id, target_id, transformation_icp, information_icp, false));
} else//: # loop closure case {
	pose_graph.edges_.push_back(PoseGraphEdge(source_id, target_id, transformation_icp, information_icp, true));
}
```

Matrix ``odometry`` is pose of each fragment by aggregating odometry transformations.
aggregate

**Comment by antithing** [comment]
Hi @Joezzr, I am attempting to run a pose graph optimise on multiple clouds also. Are you able to share your working code here? 

It would be very much appreciated! Trying to reverse engineer the python code is breaking my brain. 

Thank you!
