### ISSUE TITLE
Interactions with Rendering

### ISSUE THREAD

**Issue by matthiasvestner** [IntelVCL/Open3D#138]
It would be nice to have a way to interact with the rendering window, eg. picking of points (return point/vertex/triangle id).

**Comment by syncle** [comment]
Thanks for the suggestion. We have [ManuallyAlignPointCloud](https://github.com/IntelVCL/Open3D/tree/master/src/Tools/ManuallyAlignPointCloud) where the user can select vertex. Do you mean interactions on Python environment?

**Comment by qianyizh** [comment]
Yes, the point picking function has been implemented in class [VisualizerWithEditing](https://github.com/IntelVCL/Open3D/blob/master/src/Visualization/Visualizer/VisualizerWithEditing.h). We have not exposed it in Python interface though.

The current workaround is to use the C++ interface (you can check Tools/ViewGeometry as an example, and change the Visualizer there to ``VisualizerWithEditing``, or even better a class inheriting ``VisualizerWithEditing``.

Also I think this is a very common feature and should be included in one of Open3D Python convenient visualization functions.

**Comment by syncle** [comment]
I am working on exposing `VisualizerWithEditing` class. This will include additional Python Tutorial.

**Comment by syncle** [comment]
FYI, here is [a new document for the additional tutorial](http://open3d.org/docs/tutorial/Advanced/interactive_visualization.html).

**Comment by amrit110** [comment]
hi, it seems not possible to add multiple geometries to the VisualizerWithEditing class where the geometries can be PointCloud or say TriangleMesh. Is there a way to add this or am I thinking wrong?
`def draw_geometries_pick_points(geometries):
    vis = VisualizerWithEditing()
    vis.create_window()
    for geometry in geometries:
        vis.add_geometry(geometry)
        vis.run()
    vis.destroy_window()`

**Comment by syncle** [comment]
Hi @amrit110. Can you open a new issue for this? We would like to handle the issue in public domain. Thanks!

**Comment by amrit110** [comment]
sure! https://github.com/IntelVCL/Open3D/issues/239
