### ISSUE TITLE
Optimize a pose graph, GlobalOptimizationOption

### ISSUE THREAD

**Issue by QinZiwen** [IntelVCL/Open3D#141]
http://www.open3d.org/docs/tutorial/Advanced/multiway_registration.html#input    tell me that “Class GlobalOptimizationOption defines the loss function of the pose graph.” , But I am not find how to defines the loss function, and I also found no default loss function

**Comment by qianyizh** [comment]
The default loss function is the dense point-to-point L2 loss, with a line process weight. It is equation (2) in this paper: http://qianyi.info/docs/papers/cvpr15_loopclosure.pdf
The loss functions is approximated by matrix multiplication using information matrices. See derivation through equation (3) to (9).

``GlobalOptimizationOption`` defines a couple of options. ``max_correspondence_distance`` decides the correspondence threshold. ``edge_prune_threshold`` is the line process weight. ``reference_node`` is the node id that is considered to be the global space.

We should refine the documentation to make this clear.

**Comment by syncle** [comment]
Addressed in #210.
