### ISSUE TITLE
Non-blocking rendering

### ISSUE THREAD

**Issue by riccardomarin** [IntelVCL/Open3D#145]
Hi,
I am wondering if there is a way to render an image and interact with it while the code keep running.

I am implementing a non-rigid registration pipeline based on many optimization cycles, and I'd like to see how the optimization work in every loop. 
Now running "draw_geometries" method, it waits until I close the windows to goes on.

Thanks!
R

**Comment by syncle** [comment]
That's good question. How about using `from threading import Thread`? `draw_geometries` is based on GLFW, and it supports multi-threading. A good reference for Python multi-threading is [here](https://www.toptal.com/python/beginners-guide-to-concurrency-and-parallelism-in-python). You will need to design worker threads to display new geometry once it is obtained from registration pipeline.
