### ISSUE TITLE
Compiler warning for the provided Eigen library

### ISSUE THREAD

**Issue by csukuangfj** [IntelVCL/Open3D#154]
See the following log:
```
xx/Open3d/src/External/Eigen/Eigen/src/Core/arch/CUDA/Half.h:241:19: warning: 
      comparing floating point with == or != is unsafe [-Wfloat-equal]
  return float(a) == float(b);
         ~~~~~~~~ ^  ~~~~~~~~
xx/Open3d/src/External/Eigen/Eigen/src/Core/arch/CUDA/Half.h:244:19: warning: 
      comparing floating point with == or != is unsafe [-Wfloat-equal]
  return float(a) != float(b);
         ~~~~~~~~ ^  ~~~~~~~~
2 warnings generated.
```

```
fabs(float(a) - float(b)) < std::numeric_limits<float>::min() 
```
is better for comparing equality for two floats.

**Comment by syncle** [comment]
Thanks @csukuangfj, but I am not sure the scope for the Open3D repository. The external libraries are provided for user convenience, and intended to be untouched from the original. 

I briefly checked the [Eigen repo](https://bitbucket.org/eigen/eigen) and found out that even the recent Eigen release might have the same issue. 

https://bitbucket.org/eigen/eigen/src/253cc1138131af650a59e547d6d5228b9eb6f0d0/Eigen/src/Core/arch/CUDA/Half.h?at=default&fileviewer=file-view-default#Half.h-247

https://bitbucket.org/eigen/eigen/src/253cc1138131af650a59e547d6d5228b9eb6f0d0/Eigen/src/Core/arch/CUDA/Half.h?at=default&fileviewer=file-view-default#Half.h-250

I bet the better place for fixing this warning is to use either [Eigen bitbucket](https://bitbucket.org/eigen/eigen) or [Eigen Github mirror](https://github.com/eigenteam/eigen-git-mirror).

**Comment by csukuangfj** [comment]
An issue is opened at the address http://eigen.tuxfamily.org/bz/show_bug.cgi?id=1520

**Comment by qianyizh** [comment]
Closing this for Open3D since this is out of scope.
