### ISSUE TITLE
Error in ClipIntensityImage

### ISSUE THREAD

**Issue by csukuangfj** [IntelVCL/Open3D#156]
See the code
https://github.com/IntelVCL/Open3D/blob/5382f39abf7ad625fb6bb80b247332703665a87e/src/Core/Geometry/Image.cpp#L129

and

https://github.com/IntelVCL/Open3D/blob/5382f39abf7ad625fb6bb80b247332703665a87e/src/Core/Geometry/Image.cpp#L135

It assumes pixels are of type `float`, but `sizeof(float)` is 4.

**Comment by qianyizh** [comment]
Good catch.
