### ISSUE TITLE
The current design of three::Image cannot distinguish pixel types of float and int

### ISSUE THREAD

**Issue by csukuangfj** [IntelVCL/Open3D#164]
Both `float` and `int` occupy 4 bytes. However, `three::image` assumes
a pixel of 4 bytes is `float`.

For example, see the code here
https://github.com/IntelVCL/Open3D/blob/5382f39abf7ad625fb6bb80b247332703665a87e/src/Core/Geometry/Image.cpp#L144-L156

**Comment by qianyizh** [comment]
Yes. I don't think there is a use case for images with ``int32`` datatype.
So ``Image`` assumes ``uchar`` for 1 byte, ``uint16``for 2 bytes, and ``float`` for 4 bytes.

We can revisit this ticket again if in the future there are practical use cases for ``int32`` type and such.
