### ISSUE TITLE
Request to use scoped enum

### ISSUE THREAD

**Issue by csukuangfj** [IntelVCL/Open3D#165]
Although Open3D recommends using C++11, plain enum is still used in the project.
For example, see the code
https://github.com/IntelVCL/Open3D/blob/5382f39abf7ad625fb6bb80b247332703665a87e/src/Core/Utility/Console.h#L38-L44

Use `enum class VerbosityLevel` may be better.

**Comment by qianyizh** [comment]
Agree.

**Comment by syncle** [comment]
Adressed in #197
