### ISSUE TITLE
Error in TriangleMesh::Transform

### ISSUE THREAD

**Issue by csukuangfj** [IntelVCL/Open3D#169]
See the code

https://github.com/IntelVCL/Open3D/blob/5382f39abf7ad625fb6bb80b247332703665a87e/src/Core/Geometry/TriangleMesh.cpp#L77-L95

The normal vector should be transformed using the **transpose of the inverse** transformation matrix. For example, refer to https://www.cs.upc.edu/~robert/teaching/idi/normalsOpenGL.pdf

----

And a suggestion for using Eigen:
 - `new_point.head<3>()` is more readable than `new_point.block<3, 1>(0, 0); `, and even better
to use `new_point.hnormalized()`
 - `vertex.homogeneous()`  is more readable than `Eigen::Vector4d(vertex(0), vertex(1), vertex(2), 1.0);`

**Comment by csukuangfj** [comment]
The same problem exists for the code
https://github.com/IntelVCL/Open3D/blob/5382f39abf7ad625fb6bb80b247332703665a87e/src/Core/Geometry/PointCloud.cpp#L75-L87

**Comment by syncle** [comment]
I am not quite agree for normal transformation. 

The surface normal direction should not be affected by translational transformation, but only affected by rotation matrix in the transformation matrix. Your reference introduces a derivation for transformation of **plane** equation. If we ignore w in the reference, the transformation is transpose of the inverse of rotation matrix, which is the same as the original rotation matrix, because rotation matrix is orthonomal.

Let's take another example. Consider two points x0=[0,0,0,1] and x1=[x,y,z,1], where norm(x1) is 1. x2=x1-x0 determines surface normal. After multiplying any transformation [R,t;0,1], x2_transform will be R*x2.

**Comment by csukuangfj** [comment]
@syncle 
Yes, you are right. 

>The surface normal direction should not be affected by translational transformation

Since for (nx, ny, nz, 0), the last component of the vector is 0, which cancels out the translational part
when multiplied with a 4x4 transformation matrix.

The transpose of the inverse of a **rotation** matrix is itself, so it is fine to use the original transformation to transform the normal vector when it is a **rotation** matrix.

But when the transformation is **NOT** a rotation matrix, you have to take the 
**transpose of the inverse** of the transformation matrix to transform the normal vector.

For example, in the case of the triangle, let `x2` and `x1` be its two vertices and its normal
vector be `n`.
Let `x = x2 - x1`, then we have

n^T x = 0

If x and n are transformed by the same transformation P, then 

n' = Pn

x' = Px

After the transformation, we expect that the transformed normal vector is
still orthogonal to the transformed vector x', that is

n'^T x' = 0

which is
(Pn)^T Px = 0

n^T P^T P x = 0

which is not the case in general except when P is a rotation matrix.

But if 

n' = P^(-T) n,
then we have

n'^T x' = n^T P^(-1) P x = n^T x = 0

**Comment by qianyizh** [comment]
The assumption is that ``transformation`` is a rigid transformation matrix.

[ R | t ]
[ 0 | 1 ]

Thus Tn and (T^{-1})^{T}n is the same.

**Comment by qianyizh** [comment]
I will leave this open for a bit more discussion. But my current view is that it is not necessary to apply transpose of the inverse.

Maybe the document should be fixed so that it is written ``transformation`` is a rigid transformation matrix, and the behavior of given other types of matrix is undefined. But that is it in my current view.

**Comment by syncle** [comment]
@qianyizh I think what @csukuangfj said is correct. My arguement is correct if I only consider single directional vector, but when it is attached to the geometry, like surface normal as @csukuangfj explained, it gets changed if the transformation matrix is not pure rotation matrix. 

You can check Tn and (T^{-1})^{T}n is not equal even if ``transformation`` is rigid transformation matrix.

Let me take a real example,
```
>>> c
array([[ 0.83340129,  0.03877037,  0.55130677, -2.81010514],
       [ 0.20019144,  0.90861626, -0.36652405, -1.36098602],
       [-0.51513656,  0.41582852,  0.74948046,  2.26754521],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])
>>> np.transpose(np.linalg.inv(c))
array([[ 0.83340129,  0.03877037,  0.55130677,  0.        ],
       [ 0.20019144,  0.90861626, -0.36652405,  0.        ],
       [-0.51513656,  0.41582852,  0.74948046,  0.        ],
       [ 3.78249844,  0.40265288, -0.64908497,  1.        ]])
```

**Comment by qianyizh** [comment]
Yes, but the normal is a directional vector, isn't it?
So it is always ``(nx, ny, nz, 0)``.

**Comment by syncle** [comment]
Even with ``(nx, ny, nz, 0)``, ``Tn`` and ``(T^{-1})^{T}n`` is not the same due to the fourth-element. If we ignore forth element, and use the first three element then the Open3D's implementation is valid. However, I am not fully convinced whether this is mathematically correct.

**Comment by csukuangfj** [comment]
@syncle 
Please refer to the book `Mathematics for. 3D Game Programming and Computer Graphics`
at the address 

http://canvas.projekti.info/ebooks/Mathematics%20for%203D%20Game%20Programming%20and%20Computer%20Graphics,%20Third%20Edition.pdf

for a mathematical explanation for transforming normal vectors at section 4.5 on page 78

**Comment by syncle** [comment]
Thanks @csukuangfj. 80 page in this book also supports your argument. Let's get back to the point. Do you think Open3D implementation is correct? I am actually we need to use ``(T^{-1})^{T}`` for transforming normal vector. What I am not fully convinced is that whether ``(T^{-1})^{T}`` and ``T`` is the same for transforming ``(nx, ny, nz, 0)``.

**Comment by csukuangfj** [comment]
@syncle 
In my opinion, what you are thinking applies to tangent vectors, which are known
as **contravariant** vectors according to the above book, while
normal vectors are known as **covariant** vectors.

Although both tangent vectors and normal vectors are vectors, they are different
in terms of transformation.

I would suggest using the **transpose of the inverse** of the transformation matrix.

**Comment by qianyizh** [comment]
It is the same.
T =
[ R | t ]
[ 0 | 1 ]

Let n = [nx, ny, nz]
T [n, 0] = [Rn, 0]

T^{-1})^{T} = 
[ R | 0 ]
[ s | 1 ]

T^{-1})^{T} [n, 0] = [Rn, 0]

Please trust me on this. I have done this derivation for many times. See equations in this paper for example:
http://qianyi.info/docs/papers/cvpr14_slac.pdf
For directional vector, you just need the rotation part of the matrix, other part does not matter.

**Comment by syncle** [comment]
Actually, T^{-1})^{T} [n, 0] = [Rn, sn] not [Rn, 0] and this is why I am confused. I am not trying argue but just want to make it clear and add some comment in the code for this. Is that okay ignoring fourth element?

**Comment by qianyizh** [comment]
Ah yes, I see your point.
But the fourth number does not matter.
You throw it away anyways.
I think Tn is fine. It is clear, easy to understand, easy to compute derivative, and causes less potential troubles (e.g., if you forget to set the fourth element to 0, Tn would still be okay).

**Comment by qianyizh** [comment]
I am closing this ticket for now. Feel free to reopen it if you think more discussion is needed.

**Comment by foamliu** [comment]
Is this possible that we can reset the transformation matrix to identity?
