### ISSUE TITLE
File is not closed in case of error in FilePLY.cpp

### ISSUE THREAD

**Issue by csukuangfj** [IntelVCL/Open3D#172]
See the code
https://github.com/IntelVCL/Open3D/blob/5382f39abf7ad625fb6bb80b247332703665a87e/src/IO/FileFormat/FilePLY.cpp#L215-L217

https://github.com/IntelVCL/Open3D/blob/5382f39abf7ad625fb6bb80b247332703665a87e/src/IO/FileFormat/FilePLY.cpp#L237-L240

https://github.com/IntelVCL/Open3D/blob/5382f39abf7ad625fb6bb80b247332703665a87e/src/IO/FileFormat/FilePLY.cpp#L253-L256.

The same problem exists for
 - `WritePointCloudToPLY`
 - `ReadTriangleMeshFromPLY`
 - `WriteTriangleMeshToPLY`

`ply_close()` should be called before return.

**Comment by qianyizh** [comment]
Agree.
