### ISSUE TITLE
typo for the type RGBImagePyramid

### ISSUE THREAD

**Issue by csukuangfj** [IntelVCL/Open3D#173]
It should be `RGB**D**ImagePyramid` instead of `RGBImagePyramid`.

See the code
https://github.com/IntelVCL/Open3D/blob/5382f39abf7ad625fb6bb80b247332703665a87e/src/Core/Geometry/RGBDImage.h#L81

**Comment by qianyizh** [comment]
Agree.

**Comment by qianyizh** [comment]
@csukuangfj Just want to thank you for all the bugs you pointed out and all the PRs you submitted. You must have had a very thorough read of the entire library. This is indeed very helpful.

**Comment by csukuangfj** [comment]
@qianyizh 
That is the power of open source. I also learned a lot while reading the code 😄

**Comment by syncle** [comment]
@csukuangfj Here is my gratefulness too!

**Comment by syncle** [comment]
https://github.com/IntelVCL/Open3D/blob/5382f39abf7ad625fb6bb80b247332703665a87e/src/Core/Geometry/RGBDImage.h#L80

This comment should be also ``RGBD``
