### ISSUE TITLE
Inconsistent naming convention for class data members

### ISSUE THREAD

**Issue by csukuangfj** [IntelVCL/Open3D#178]
Some class data members end with `_` while some are not.

See the code
https://github.com/IntelVCL/Open3D/blob/84d5681c3996958320bab41478a28431b2f7dc44/src/Core/Geometry/DownSample.cpp#L81-L85

and 

https://github.com/IntelVCL/Open3D/blob/84d5681c3996958320bab41478a28431b2f7dc44/src/Core/Geometry/Image.h#L94-L99

**Comment by syncle** [comment]
I think it should come with ``_``. According to [Google Coding Style for C++ (class variable names)](https://google.github.io/styleguide/cppguide.html#Variable_Names). The modification will involve python binding. I will work for this.
