### ISSUE TITLE
Error for ordering eigen values in the function FastEigen3x3

### ISSUE THREAD

**Issue by csukuangfj** [IntelVCL/Open3D#181]
The function
https://github.com/IntelVCL/Open3D/blob/84d5681c3996958320bab41478a28431b2f7dc44/src/Core/Geometry/EstimateNormals.cpp#L39
returns the eigenvector of the **smallest** eigenvalue for a real symmetric matrix, i.e, a covariance matrix.

Inside the function, it saves the **least** eigenvalue in `eigenvalues(2)`. 
But the code for diagonal matrices
https://github.com/IntelVCL/Open3D/blob/84d5681c3996958320bab41478a28431b2f7dc44/src/Core/Geometry/EstimateNormals.cpp#L45-L49

saves the **largest** eigenvalue inside `eigenvalues(2)`.

**Comment by syncle** [comment]
Good point. The fix is
```
 	eigenvalues(0) = std::max(A(0, 0), std::max(A(1, 1), A(2, 2))); 
 	eigenvalues(2) = std::min(A(0, 0), std::min(A(1, 1), A(2, 2))); 
 	eigenvalues(1) = A.trace() - eigenvalues(0) - eigenvalues(2); 
```
