### ISSUE TITLE
SyntaxError: invalid or missing encoding declaration

### ISSUE THREAD

**Issue by felixendres** [IntelVCL/Open3D#204]
Using ipython3 (note the i in front), I get the following error message for `help(py3d.PointCloud2)` - and any other help command
``SyntaxError: invalid or missing encoding declaration for '/home/me/code/Open3D/build/lib/py3d.cpython-34m.so'
 
Funnily it works in the "regular" python3 console. An ipython problem?

**Comment by syncle** [comment]
Hi @felixendres, 
I tested with ipython3 but cannot see the problem you are facing with. Can you check your ipython3 commands runs with python3.4 (presumably from your py3d name)? It is common case that the python versions for compile and for runtime do not match. If this is the case, refer [Compilation Options -> Python Binding](http://open3d.org/docs/compilation.html#python-binding)

My result (with MacOSX, Anaconda Python 3.6):
```
Python 3.6.1 |Anaconda 4.4.0 (x86_64)| (default, May 11 2017, 13:04:09) 
Type "copyright", "credits" or "license" for more information.

IPython 5.3.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import sys
   ...: import numpy as np
   ...: sys.path.append("../..")
   ...: 
   ...: import py3d as py3d
   ...: help(py3d.PointCloud)
```
This produces
```
Help on class PointCloud in module py3d:

class PointCloud(Geometry3D)
 |  Method resolution order:
 |      PointCloud
 |      Geometry3D
 |      Geometry
 |      pybind11_builtins.pybind11_object
 |      builtins.object
 |  
 |  Methods defined here:
 |  
 |  __add__(...)
 |      __add__(self: py3d.PointCloud, arg0: py3d.PointCloud) -> py3d.PointCloud
:
```

**Comment by qianyizh** [comment]
This is weird. I tried jupyter notebook (the successor of ipython) and it works fine on both OSX and Ubuntu. See the following figure. Maybe it is a problem with ipython3?

One way to debug it is to try using jupyter notebook and see if the problem still exists. The other way is to build a minimal pybind11 project and see if it happens with that.

<img width="1164" alt="screen shot 2018-02-22 at 12 54 06 am" src="https://user-images.githubusercontent.com/5875217/36528724-f1b425b4-176a-11e8-98a0-3e75c5e1f446.png">

**Comment by felixendres** [comment]
> Can you check your ipython3 commands runs with python3.4 (presumably from your py3d name)?

Here's the initial output when starting ipython3. I had checked that they matched, at least for the major version number. 

> Python 3.4.3 (default, Nov 28 2017, 16:41:13) 
> Type "copyright", "credits" or "license" for more information.
> 
> IPython 1.2.1 -- An enhanced Interactive Python.

I am working on ubuntu 14.04. by the way. I meanwhile had to recompile the python wrapper for python 2.7, for other reasons (package conflicts). There, the documentation in ipython works fine.

Thanks for your responses. it's not a big issue, so If there's no lead on what the cause could be, feel free to close the issue.

**Comment by syncle** [comment]
Glad to hear that you resolved the issue. It seems like the issue relates to python configuration not Open3D. Closing.
