### ISSUE TITLE
class ScalableTSDFVolume(TSDFVolume)

### ISSUE THREAD

**Issue by QinZiwen** [IntelVCL/Open3D#213]
I do not understand the meaning of the parameters of the initialization function of class ScalableTSDFVolume(TSDFVolume)，and it initialization function is 
```
__init__(self: py3d.ScalableTSDFVolume, voxel_length: float, sdf_trunc: float, with_color: bool, volume_unit_resolution: int=16L, depth_sampling_stride: int=4L) -> None
```

In addition, when I test 'Open3D/build/lib/Tutorial/ReconstructionSystem/make_fragments.py' using 'rgbd_dataset_freiburg1_xyz' of TUM, the fragment obtained by the program is incomplete,like 
![fragment](https://user-images.githubusercontent.com/15364705/36660744-33f10e04-1b14-11e8-91a9-f20be8d65fc8.png)

How should I set the parameters of ScalableTSDFVolume(voxel_length = 3.0 / 512.0,  sdf_trunc = 0.04, with_color = True)?

Thank you!

**Comment by QinZiwen** [comment]
Thank you!

**Comment by lvgeng** [comment]
Sorry for ask again in a closed question...
what did 
sdf_trunc: truncation value for signed distance function (SDF).
affect?

By playing with it I have a clear idea that it would cause significant difference on integrating time. However what is the rule of choosing a sdf_tunc value? 
If there is some kind of rule, which parameters I should look into to make the decision?

**Comment by qianyizh** [comment]
It is empirical. Usually, first choose finest grid size ``voxel_length``, which decides the detail level of the final output. Then set ``sdf_trunc`` roughly 5x the finest grid size. @lvgeng

**Comment by aniketghodake10** [comment]
> It is empirical. Usually, first choose finest grid size `voxel_length`, which decides the detail level of the final output. Then set `sdf_trunc` roughly 5x the finest grid size. @lvgeng

Any idea why TSDF doesn't get properly integrated when we increase stf_trunc value ? Any workaround ?

Basically I want Non-Truncated SDF. So, I tried increasing sdf_trunc parameter. But TSDF seems to be not integrating properly.

Below is the extracted point cloud from same TSDF. We can see very distorted pointcloud. TSDF is also not accurate.

![image](https://user-images.githubusercontent.com/38704659/171361352-3b8f1de7-6738-43c0-811f-f3feecdf664b.png)
