### ISSUE TITLE
Export Transformed Points

### ISSUE THREAD

**Issue by rukie** [IntelVCL/Open3D#214]
It is readily clear how to export point clouds into a numpy array. It is not as clear how to export a **transformed** point cloud. 

I loaded point clouds with intensity values scaled 0-1 into RGB. I successfully ran a multi-way registration, but since I'm working on a cluster I can't visualize it. I'd like to open with CloudCompare on a local machine. 

For writing to file(s) I have the code below, but I'm unsure how to export the results of the transformations
.
``` python
    for i,target in enumerate(pcds):
        xyz_load = np.asarray(pcds[i].points) # Load x,y,z points
        xnynzn_load = np.asarray(pcds[i].normals) # Load normals
        rgb_load = np.asarray(pcds[i].colors) # Load colors
        data_load = np.concatenate((xyz_load, xnynzn_load, rgb_load), axis=1)
        f = open(out_dir+"Frame{:05d}.csv".format(i), 'w')
        for points in data_load:
            strlist = [str(i) for i in points]
            f.write(','.join(strlist)+'\n')
        f.close()
```

Following up on transformed points, I assume I need to transform the normals too?

**Comment by syncle** [comment]
> It is not as clear how to export a transformed point cloud.
> but I'm unsure how to export the results of the transformations

I am not sure whether you are interested in transformed point cloud or transformation matrix. Let me try answer both. For saving point cloud, your custom code looks fine and you should be able to save transformed point cloud after you apply ``transform()`` on the point cloud. ``transform()`` is in-place function and it updates points and normal field based on the transformation matrix. If you are interested in transformation matrices, all the transformations are in ``pose_graph.nodes[id].pose``.

> Following up on transformed points, I assume I need to transform the normals too?

You don't have to. Normals are transformed once you apply transformation for a point cloud.

**Comment by rukie** [comment]
I am interested in a transformed point cloud.

So to be clear, from your documentation in Multiway Registration:
```
print("Transform points and display")
    for point_id in range(n_pcds):
        print(pose_graph.nodes[point_id].pose)
        pcds[point_id].transform(pose_graph.nodes[point_id].pose)
    draw_geometries(pcds)
```
The points in pcds are transformed in global alignment?
If I run my code after that loop, I should be exporting globally aligned point clouds?

**Comment by syncle** [comment]
Exactly. This code snippet explains my answer.

**Comment by rukie** [comment]
Thank you for the clarification!
