### ISSUE TITLE
install Open3D as python package

### ISSUE THREAD

**Issue by EthanZhangYi** [IntelVCL/Open3D#217]
HI,
Following the instruction document, `py3d` is compiled in `build/lib`. How to install it as a python package and manage it by `pip` or `conda` ? or I just need to copy the py3d.so to the default python package path?

**Comment by qianyizh** [comment]
Yes. So far copying py3d.so to your working directory is the best solution.

This is also related to #130

**Comment by syncle** [comment]
This is good suggestion. I actually have been thinking about this idea for a long time. This will make accessibility of Open3D even easier as ``conda`` or ``pip`` are widely used python version control tool now days. Just typing ``conda install py3d`` or ``pip install py3d`` would be great. How about officially submit py3d to anaconda and pip once we have stable release?

**Comment by qianyizh** [comment]
I think the right timing is when we have v1.

**Comment by takanokage** [comment]
Just a note this used to be milestone 0.2 but it's not showing up anymore in the list.

**Comment by qianyizh** [comment]
Yeah I just had a discussion with @syncle and we think v0.2 might be too early to do this. Thanks for the note!

**Comment by syncle** [comment]
The solution that copies py3d module to default python path is addressed in #286.

**Comment by takanokage** [comment]
well, yes and no.
Yes, #286 is a good solution for installing from sources.
Would be nice if we place this in a public repository so that people just say something like:
`pip install open3d`.

**Comment by qianyizh** [comment]
I think this is lower priority for now. I also think Open3D is not mature enough to be adopted by pip or conda. 😸 

Let's focus on other high priority things first then we revisit this.

**Comment by harpone** [comment]
Copying works fine, but then the module is not recognized by e.g. PyCharm's package manager (can import it fine though), which is a nuisance...

**Comment by takanokage** [comment]
addressed as part of milestone [0.2](https://github.com/IntelVCL/Open3D/tree/v0.2).

**Comment by syncle** [comment]
Useful link for conda packaging: https://conda.io/docs/user-guide/tutorials/build-pkgs-skeleton.html
