### ISSUE TITLE
Python dependencies

### ISSUE THREAD

**Issue by alecjacobson** [IntelVCL/Open3D#222]
I suppose most python users will have things like matplotlib already installed, but following a fresh build following the documentation instructions I immediately got an error running `python rgbd_redwood.py`:

```
Traceback (most recent call last):
  File "rgbd_redwood.py", line 10, in <module>
    import matplotlib.pyplot as plt
ImportError: No module named matplotlib.pyplot
```

I'm not sure if matplotlib is the only python package I'm missing.

I'd like to request a python dependency check/script like the `scripts/install-deps-osx.sh`.  

(I fixed this particular issue with `pip install matplotlib`)

**Comment by syncle** [comment]
Good point. I went through python tutorial scripts and see [list of standard python packages](https://docs.python.org/3/library/index.html). FYI, The external python packages used by Python tutorial are:
- numpy
- matplotlib
- cv2 (optional for reconstruction system, shall not make run-time error)


> I'd like to request a python dependency check/script like the scripts/install-deps-osx.sh.
(I fixed this particular issue with pip install matplotlib)

As a result, this single line should work in general: 
```
python -m pip install --user numpy matplotlib opencv-python
```
However, I am bit worried that this script might not be the most preferred way for Anaconda users who already have OpenCV (or related packages). For example, ``pip install opencv-python`` installs OpenCV3.4, and ``conda install -c conda-forge opencv`` will install OpenCV3.3. Running this script may create dual OpenCV installs. I don't have a clear answer for this.

**Comment by qianyizh** [comment]
I am very lazy and always use Anaconda.

My personal best practice is to create an independent Anaconda environment and install dependencies (e.g. opencv) there. For each environment Anaconda installs the whole package of dependencies. It is redundant, and a huge consumption of disk space.

But it is good for lazy people like me :satisfied:
