### ISSUE TITLE
py3d not found in after following Ubuntu compiling steps

### ISSUE THREAD

**Issue by nianxing** [IntelVCL/Open3D#223]
after follow compiling steps for Ubuntu in Doc. My py3d's name in Open3D/build/lib is py3d.cpython-35m-x86_64-linux-gnu.so 
My platform is Ubuntu 16.04 with python 2.7 as default version.

**Comment by qianyizh** [comment]
In your case, CMake found the wrong python version. You can specify ``DPYTHON_EXECUTABLE``. It is documented at:
http://www.open3d.org/docs/compilation.html#python-binding
and
http://pybind11.readthedocs.io/en/stable/faq.html?highlight=python%20path#cmake-doesn-t-detect-the-right-python-version

**Comment by nianxing** [comment]
solved after specify DPYTHON_EXECUTABLE, thanks.
