### ISSUE TITLE
How to configure CMakeLists.txt for cpp interface?

### ISSUE THREAD

**Issue by zjudmd1015** [IntelVCL/Open3D#224]
Hi Authors,

Is there some tutorials or documentation about how to configure **CMakeLists.txt** file for c++ interface?
I am trying to use c++ but failed to compile a simple one. I include "Core/Core.h" and want to create a pointcloud instance, I want to use `three::PointCloud cloud;` to create a new cloud, When I tried to compile it with it, errors like `undefined reference to 'omp_get_num_threads'` show up. I wonder if I used a wrong syntax.

If the syntax is right, I probably made something wrong with my **CMakeLists.txt** file. Do you have a template **CMakeLists.txt** to include headers and link libraries for **Open3D** ?
Thanks a lot.

Best,

**Comment by syncle** [comment]
Related to #130.

> The best answer for your question for right now is to add your custom cpp file in src/Test folder and add entry of your application in src/Test/CMakeList.txt file. The Open3D build chain will generate standard-alone executable for you.

**Comment by zjudmd1015** [comment]
Thanks, I'll check that.
