### ISSUE TITLE
Question: RANSAC Settings

### ISSUE THREAD

**Issue by rukie** [IntelVCL/Open3D#226]
I'm sorry if this is an amateur question, but I'm trying to understand some of the settings.

I'm looking for a little more detail in the Correspondence Checkers.

```
/// Check if two aligned point clouds are close
class CorrespondenceCheckerBasedOnDistance : public CorrespondenceChecker
```
I assume this is the distance from a point to the nearest neighbor in the target cloud? Any iterations where its greater than this value are rejected.

```
/// Check if two aligned point clouds have similar normals
class CorrespondenceCheckerBasedOnNormal : public CorrespondenceChecker
```
Is this a 0 to 1 scale? Is this in radians? 

```
CorrespondenceCheckerBasedOnEdgeLength
```
This is a 0 to 1 scale. Are the normalized random selections close to the same height/width between source and target frames? 

Thank you for any clarification.

**Comment by syncle** [comment]
> I assume this is the distance from a point to the nearest neighbor in the target cloud? Any iterations where its greater than this value are rejected.

Yes. You're right.
<br />


> Is this a 0 to 1 scale? Is this in radians?

Check out this:
https://github.com/IntelVCL/Open3D/blob/9c6839de3cc57d6344a4d1a0602afeec50a1c28a/src/Core/Registration/CorrespondenceChecker.cpp#L78-L84
It uses ``std::cos`` and uses radian. 
<br />

> Are the normalized random selections close to the same height/width between source and target frames?

Yes. This adds strong geometric and joint constrains for multiple correspondences.

**Comment by rukie** [comment]
Thank you for the clarification!
