### ISSUE TITLE
Add tutorial for IO

### ISSUE THREAD

**Issue by qianyizh** [IntelVCL/Open3D#233]
I just looked through the tutorial. There is none for functions such as ``write_point_cloud``.

We should have a dedicated document for IO since this is one of the most frequently used function.

**Comment by syncle** [comment]
I see. Actually ``write_point_cloud`` appears in [working with Numpy](http://open3d.org/docs/tutorial/Basic/working_with_numpy.html?highlight=write_point_cloud), but it might be too far from getting started page. Which functions might be appropriate for tutorial? 

Some candidates are:
- ``read_point_cloud``
- ``write_point_cloud``
- ``read_triangle_mesh``
- ``write_triangle_mesh``

These I/O functions are less relevant though:
- ``read_pinhole_camera_intrinsic``
- ``write_pinhole_camera_intrinsic``
- ``read_pose_graph``
- ``write_pose_graph``
- ``read_image``
- ``write_image``
