### ISSUE TITLE
Photo-metric weight in Colored ICP

### ISSUE THREAD

**Issue by zjudmd1015** [IntelVCL/Open3D#235]
Hi Authors,

Now it seems that Photo-metric weight is a fixed one (with geometric weighting 0.968) in `registration_colored_icp()`, would you be possible to open an interface in this function to tuning the weight? 

I wonder where is this weighting ratio coming from and why is it this number?

Thanks!

**Comment by syncle** [comment]
Hi @zjudmd1015 

> would you be possible to open an interface in this function to tuning the weight?

Yes we will. We decide to put it as a hard-code due to our empirical experiment. Please check out the next answer.

> I wonder where is this weighting ratio coming from and why is it this number?

You can check Appendix B in [supplementary material of our ICCV 2017 paper](http://redwood-data.org/indoor_lidar_rgbd/supp.pdf)

**Comment by zjudmd1015** [comment]
Thanks @syncle  !
