### ISSUE TITLE
error importing py3d

### ISSUE THREAD

**Issue by takanokage** [IntelVCL/Open3D#241]
$ cd ~/Open3D/build/lib/Tutorial/Basic
$ python rgbd_redwood.py 
Traceback (most recent call last):
  File "rgbd_redwood.py", line 9, in <module>
    from py3d import *
ImportError: No module named py3d

**Comment by takanokage** [comment]
Q: is there a special step required after building Open3D?

**Comment by syncle** [comment]
From open3d doc 'getting started':

If there is an issue, check whether the Python version detected by cmake (see log from cmake) and the Python version for command line environment (type python -V) match. If it is not, please follow Python binding in docs. In addition, Pybind issue board on Github repository has helpful notes from Open3D users.

**Comment by takanokage** [comment]
Thanks, I already found that. I was hoping that someone here has had this specific issue already and could save me some time.

**Comment by qianyizh** [comment]
Yes. It is a very annoying issue.
If you search "No module named py3d" in issues, you can find #66 

It is annoying. But it is not an issue of Open3D. It is even not an issue of pybind11. More likely to be a CMake issue.

**Comment by takanokage** [comment]
In my case I forgot to run the python dependencies script. After I did that I had to run the samples with python3.

**Comment by takanokage** [comment]
I see that  this error message can have multiple causes.
One of them can be fixed through `scripts/install_deps_python.sh`: install numpy, matplotlib & opencv-python for both python2 and python3.

Both on my local machine and inside a docker container cmake identifies python3 however the current `scripts/install_deps_python.sh` only installs the python2 dependencies.

**Comment by zsfVishnu** [comment]
replace `from  py3d import *` with  `from open3d import *` , since open3d is like the parent package
