### ISSUE TITLE
Py3D name conflict

### ISSUE THREAD

**Issue by takanokage** [IntelVCL/Open3D#242]
There seems to be a [Py3D](https://pypi.python.org/pypi/py3d/1.0.0) already in the PyPi.

Do we want to find another name for our library?

**Comment by takanokage** [comment]
Eventually this is going to be a problem if we want this library listed in PyPi as well.

**Comment by syncle** [comment]
Good catch. Py3D is not official python library name BTW. We just used it for convenience so far. I think we can simply use `open3d`.

Related to #217.

**Comment by qianyizh** [comment]
We keep py3d as the name for now and worry about it when we want to release v1.
