### ISSUE TITLE
Tkinter not included in install-deps-python.sh

### ISSUE THREAD

**Issue by takanokage** [IntelVCL/Open3D#243]
Just a note, on some Ubuntu configurations 'Tkinter' is missing and needs to be installed in order to run the Tutorial/Basic/rgbd_redwood.py sample.

Packages:
- ` python-tk` for Python 2.x
- `python3-tk` for Python 3.x.

> Tkinter - Writing Tk applications with Python (3.x)
>  A module for writing portable GUI applications with Python (3.x) using Tk.

**Comment by syncle** [comment]
> on some Ubuntu configurations 'Tkinter' is missing

It is not clear whether this issue is applied for general cases. Could you elaborate more on **some Ubuntu configurations**? I think this issue arose from custom dockerlized images, not by standard ubuntu systems.

**Comment by takanokage** [comment]
I tested on two clean machines with Ubuntu 16.04: one physical system and on the Docker container for Open3D. I didn't want to generalize to all Linux distributions.
