### ISSUE TITLE
debug build 

### ISSUE THREAD

**Issue by takanokage** [IntelVCL/Open3D#248]
What is the guideline for debugging the C/C++ code?
Do we have a debug build option?

**Comment by qianyizh** [comment]
I am using ``src/Test`` as my playground for C++ code testing, debugging, and benchmarking.
The build flag is ``Open3D_BUILD_TESTS ``.

Later on I switched to exposing interfaces in Python and using Jupyter notebook for debugging and benchmarking.

**Comment by syncle** [comment]
My recommendation is to specify ``CMAKE_BUILD_TYPE=Debug`` flag. 

https://github.com/IntelVCL/Open3D/blob/39e432b5cd2179725cc5403b5d53255f3eb41b71/src/CMakeLists.txt#L24-L29

For example,
```
cmake -DCMAKE_BUILD_TYPE=Debug ../src
```

**Comment by takanokage** [comment]
thank you guys!

**Comment by syncle** [comment]
@takanokage, can you tell me which comment helped you to resolve the issue?

**Comment by takanokage** [comment]
I ended up not needing the debug build. I was trying to figure out why Open3D was crashing in Docker. Turns out that GLFW 3.3 was crashing in Docker however the mainline/master version of GLFW was working just fine.
