### ISSUE TITLE
python debug

### ISSUE THREAD

**Issue by takanokage** [IntelVCL/Open3D#249]
add brief documentation about how to debug python scripts.

**Comment by syncle** [comment]
I think python already provides a natural way to traceback the error. Some neat tools iPython, PyCharm is good fit for this.

**Comment by takanokage** [comment]
Exactly, I didn't know about these tools.
I'm suggesting simply adding links to python debugging tools & guidelines.

**Comment by qianyizh** [comment]
I think this is out of the scope of Open3D.
