### ISSUE TITLE
c++ debug

### ISSUE THREAD

**Issue by takanokage** [IntelVCL/Open3D#250]
add documentation about how to debug the c++ engine.

**Comment by syncle** [comment]
I think this will related to #166

**Comment by takanokage** [comment]
True.
In addition I'm thinking about:
- less obvious cases like for example what do you do when Open3D crashes inside docker. I imagine there are other situations as well.
- how to enable the debug build. The question may be silly but maybe it would save someone some time.

**Comment by qianyizh** [comment]
This is a duplicate of #248
