### ISSUE TITLE
docker documentation

### ISSUE THREAD

**Issue by takanokage** [IntelVCL/Open3D#251]
Add documentation for the dockerized Open3D.

**Comment by qianyizh** [comment]
Part of #17

**Comment by takanokage** [comment]
I would like to keep this open. True, this is related to #17 however this will be an independent pull request. Or we let this closed and postpone the pull request for #17 until after I implement this as well.

Personally I prefer lots of smaller pull requests. I know this puts a lot of on the people reviewing (+ time spent with the build tasks). However packing lots of small things in a single big pull request has disadvantages as well for example makes it harder to reach a stopping point and personally I feel less agile. I'm open to discuss how we can improve the process.
