### ISSUE TITLE
py3d.read_point_cloud could not read ply file

### ISSUE THREAD

**Issue by tamireiny** [IntelVCL/Open3D#252]
Hello, 

I was trying to read a point cloud that was originally saved by matlab pcwrite function, 
https://www.dropbox.com/s/87fl6qrel7nh2ym/pc_scene1_shared.ply?dl=0
When using py3d.read_point_cloud I get : Read PLY failed: unable to open file

The file is not opened by any other program.
Any suggestion?

Thanks, 
Tamir

**Comment by syncle** [comment]
Hi @tamireiny 
I found this issue now. Does the problem resolved?

**Comment by tamireiny** [comment]
Hi Jaesik, 
Yes, the problem was on my side.
Thanks for your attention!
Tamir
