### ISSUE TITLE
bind mounts

### ISSUE THREAD

**Issue by takanokage** [IntelVCL/Open3D#254]
Reserve a space (folder) on the host for Open3D inputs/outputs and mount it to the Open3D container.
This makes working with dockerized Open3D friendlier.

**Comment by takanokage** [comment]
This should not be closed yet. #17 needs it even though it's not obvious at first.
#17 needs it because docker container storage is not persistent. For example, if I run a script to generate some images there's not way to access those images on the host unless we design the Open3D docker image with bind mounts in mind.
I propose we make the whole Open3D folder available both inside the docker container and on the host side. In this way we not only gain direct access to the images generated but we also enable developing Open3D on the host side and testing on both host side and docker side of things.

I think this is mandatory for the #17 to really work.

**Comment by qianyizh** [comment]
I think it is part of #17 so I treat it as a duplicate.
Can you elaborate what you said here in #17 ?

**Comment by takanokage** [comment]
sure
