### ISSUE TITLE
Remote debug dockerized Open3D

### ISSUE THREAD

**Issue by takanokage** [IntelVCL/Open3D#255]
Investigate how tools like Visual Studio Code could be used to edit/run/debug/ Open3D remotely.
First bind mount a host folder for the Open3D code - this solves the editing problem.
Secondly and more importantly: how can VSCode be used to debug Open3D running inside Docker?

**Comment by qianyizh** [comment]
Part of #17 

Also I suggest not to test Windows/OSX environment docker for now.
