### ISSUE TITLE
location for Docker files

### ISSUE THREAD

**Issue by takanokage** [IntelVCL/Open3D#258]
I'd like to discuss options for placing the Docker files.
In my [branch](https://github.com/takanokage/Open3D/tree/issue_%230017) I am using `Open3D/docker` for storing Docker related setup files and utilities.
Another option would be to move the `docker` folder under `Open3D/src`.

Any opinions?

**Comment by qianyizh** [comment]
``Open3D/utilities/docker/...``

We should also consider moving ``Open3D/scripts/`` into ``Open3D/utilities/scripts/``, but this will be a separate issue.

**Comment by syncle** [comment]
I bet ``Open3D/util/docker/...`` because it is concise like ``src`` in root folder.

**Comment by qianyizh** [comment]
``Open3D/util/`` then.
