### ISSUE TITLE
question about fragment

### ISSUE THREAD

**Issue by yzp12** [IntelVCL/Open3D#263]
Hi!
Thank you for sharing these code! They are apparently pretty useful for doing 3D related task. I am reading the make_fragment, and register_fragment codes. I wonder why we need to design "fragment" which to my understanding is a intermediate summary(like fuse 10 nearby depth scans) of the total geometry. Is there a particular benefit for doing such two step registration: depth scan -->(registration) fragment --> (registration) final geometry ? I am novice about 3d reconstruction, apologize for a potentially stupid question! 
Thank you!

**Comment by syncle** [comment]
Hi @yzp12 

In short, it is for better reconstruction quality.

Let me borrow some sentences from [Robust Reconstruction of Indoor Scenes](https://www.cv-foundation.org/openaccess/content_cvpr_2015/papers/Choi_Robust_Reconstruction_of_2015_CVPR_paper.pdf), which describes key idea of Open3D's reconstruction system.

> Scene fragments integrate out some of the noise in the range data and yield more reliable normal information. They have a larger footprint in the scene than individual images without suffering from significant odometry drift. Fragments are analogous to submaps, which are used in a number of robotic mapping systems

**Comment by syncle** [comment]
Hi @yzp12, do you have additional questions for this? Otherwise, I will close this issue.

**Comment by yzp12** [comment]
Thank you. I will close this
