### ISSUE TITLE
cannot build on server

### ISSUE THREAD

**Issue by yzp12** [IntelVCL/Open3D#264]
Hi!

When I try to build it on a remote server, i got following error:
CMakeFiles/Makefile2:1846: recipe for target 'Experimental/ViewDistances/CMakeFiles/ViewDistances.dir/all' failed
make[1]: *** [Experimental/ViewDistances/CMakeFiles/ViewDistances.dir/all] Error 2
/usr/bin/ld: /lusr/opt/glfw-3.2.1/lib/libglfw3.a(x11_window.c.o): undefined reference to symbol 'XConvertSelection'
//usr/lib/x86_64-linux-gnu/libX11.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Test/CMakeFiles/TestLineSet.dir/build.make:105: recipe for target 'bin/Test/TestLineSet' failed
make[2]: *** [bin/Test/TestLineSet] Error 1
CMakeFiles/Makefile2:1203: recipe for target 'Test/CMakeFiles/TestLineSet.dir/all' failed
make[1]: *** [Test/CMakeFiles/TestLineSet.dir/all] Error 2
/usr/bin/ld: /lusr/opt/glfw-3.2.1/lib/libglfw3.a(x11_window.c.o): undefined reference to symbol 'XConvertSelection'

I guess this is related to visualizing functionality? I actually don't need it on server. So Is there a way to walk around this?

Thank you!

**Comment by syncle** [comment]
As a quick remedy, I recommend building GLFW from source.

**Option 1:**
Please checkout [this document](http://open3d.org/docs/compilation.html#dependencies), and try the following
```
cmake -DOpen3D_USE_NATIVE_DEPENDENCY_BUILD=OFF ../src
```

**Option 2:**
If this suggestion does not work and you just want to disable visualization module, you will need to remove 
https://github.com/IntelVCL/Open3D/blob/39e432b5cd2179725cc5403b5d53255f3eb41b71/src/CMakeLists.txt#L113

and exclude all the applications that use `Visualization` module. For example, this application should be excluded from build.
https://github.com/IntelVCL/Open3D/blob/39e432b5cd2179725cc5403b5d53255f3eb41b71/src/Test/CMakeLists.txt#L2

Or you can simply turn off building test applications by changing the following flag.
https://github.com/IntelVCL/Open3D/blob/39e432b5cd2179725cc5403b5d53255f3eb41b71/src/CMakeLists.txt#L16

I actually have not tried Option 2, so there might be another issue with Python binding.

**Another possible option, FYI**
We are working on headless rendering #17. This will make you allow render/save geometries remotely. It is about to be merged via #262.

**Comment by syncle** [comment]
Umm. how about revisit Option 1? It does not require `sudo`, as GLFW dependencies are already included in Open3d.

**Comment by yzp12** [comment]
Great, I tried the option 1 and it works! Now i can import py3d without problem. Thank you a lot for your help!

**Comment by yzp12** [comment]
Hi @syncle ,
I tried to use the lastest source codes on remote server. I encountered an issue when trying to disable all the visualization modules. I was able to build succesfully, but when trying to import open3d, it says: undefined symbol: _Z28pybind_visualization_classesRN8pybind116moduleE. Do you have any suggestions for this? Thanks!

**Comment by yzp12** [comment]
Hi @syncle , Thank you! Actually I just have solved the issue by also deleting the "pybind_visualization_classes(m)" line in open3d.cpp. Btw thanks for reference me to the headless rendering part. That is pretty cool!
