### ISSUE TITLE
docs: python binding

### ISSUE THREAD

**Issue by takanokage** [IntelVCL/Open3D#266]
Python binding appears in two locations:
1. [Tutorial/Basic/Python binding](http://open3d.org/docs/tutorial/Basic/python_binding.html)
2. [Compilation Options/Python binding](http://open3d.org/docs/compilation.html#python-binding)

I propose we merge the two entries under [Compilation Options](http://open3d.org/docs/compilation.html).
Python binding is not exactly a tutorial but more of a dependent requirement to the tutorials.

**Comment by syncle** [comment]
We decide to make them separate as Compilation Options page should address concise document for compilation options.

**Comment by takanokage** [comment]
That's a good point.
What do we do with the fact that python binding is not an Open3D specific concept?

Maybe a name change from `Tutorial/Basic/Python binding` to one of the following:
1. `Tutorial/Basic/Python module`
2. `Tutorial/Basic/Py3D`
3. `Tutorial/Basic/Open3D python module`
4. `Tutorial/Basic/Open3D python interface`
5. `Tutorial/Basic/Open3D python`

**Comment by syncle** [comment]
How about ``Tutorial/Basic/python_interface`` then?

**Comment by takanokage** [comment]
Yep, that sounds good.
