### ISSUE TITLE
move scripts under util

### ISSUE THREAD

**Issue by takanokage** [IntelVCL/Open3D#267]
Move the `Open3D/scripts` under `Open3D/scripts/util`.
`Open3D/scripts/util` will also house the docker utilities.

**Comment by syncle** [comment]
Yes. Can you make a PR for this?

**Comment by syncle** [comment]
Another note. Check whether `.appveyor.yml` and `.travis.yml` use these scripts. If necessary, fix the path accordingly.

**Comment by takanokage** [comment]
will do, thanks!

**Comment by syncle** [comment]
Closing this issue as #262 closed for now.

**Comment by takanokage** [comment]
maybe it is premature to close this. we agreed we want to keep the docker work which under util. in order to keep the clutter to a minimum we should move the scripts under util too.

**Comment by syncle** [comment]
Sure. I will make PR for this.
