### ISSUE TITLE
.gitignore

### ISSUE THREAD

**Issue by takanokage** [IntelVCL/Open3D#268]
An example of why we need a more generic .gitignore.

I was trying to commit my first draft of the documentation changes for #17.

```
$ git status
On branch issue_#0017
Your branch is up-to-date with 'origin/issue_#0017'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   tutorial/Advanced/index.rst

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	tutorial/.DS_Store
	tutorial/._.DS_Store
	tutorial/Advanced/headless_rendering.rst
```

Notice the following files. They are auto-generated by MacOS.
```
tutorial/.DS_Store
tutorial/._.DS_Store
```

Normally I would just say:
`$ git add tutorial/`

but that would add unwanted files to the commit list.

**Comment by syncle** [comment]
I am still prefer current one. You can add `.DS_Store` and `._.DS_Store`

**Comment by takanokage** [comment]
Yeah, I could add those however it's not very good practice to add specific entries to gitignore. 
Not a breaking issue currently so I guess I can live with it as is.
