### ISSUE TITLE
CI for documentation

### ISSUE THREAD

**Issue by takanokage** [IntelVCL/Open3D#269]
There are certain changes to the repository that may not be currently captured by the CI.
Do we want the CI checks to be executed in such cases?

For example when editing the documentation and commits are registered into an existing pull request. Each commit will trigger a new CI check however it may not be necessary.

**Comment by syncle** [comment]
Good point. We may consider adding a test for documentation. I think we can add

```
# for building http://open3d.org/docs
pip install sphinx sphinx-autobuild sphinx-rtd-theme
make html

# for building http://open3d.org/cppapi/
sudo apt-get install doxygen
doxygen Doxyfile
```

on this lines
https://github.com/IntelVCL/Open3D/blob/39e432b5cd2179725cc5403b5d53255f3eb41b71/.travis.yml#L59-L76
