### ISSUE TITLE
branch development - process improvement

### ISSUE THREAD

**Issue by takanokage** [IntelVCL/Open3D#272]
I'd like to discuss changes to our process.

My main proposal is to open branches for the issues/milestones we want to work on.

Advantages:
- anyone can see the active branches
- progress more clearly visible while working on a branch than when working on a fork
- anyone can try a branch before the work is completed
- more then one contributor can commit to a branch
- faster development

The branch name can be "issue_#NNN" if a branch specific issue or "milestone_x.x" if the branch is towards a certain milestone. Actually a milestone branch could be branched further into the issues we're addressing for that specific milestone.

I also propose that team members get push rights to the branch they're working on. In my opinion we don't need as many pull requests as the current methodology implies. Instead of many small PRs we can have many informal code reviews in order to keep the code in check and only one big PR at the end when merging a branch back into main. 

Regarding the visibility of our progress: I've made over 40 commits in the past week on my fork for issue #17 and issue #130 however if we're looking at the main page the last commit was 7 days ago. This doesn't look like a very active project.

Regarding the number of contributors on a particular issue: the way we're doing it now only one person works on a fork.

We should keep the current process for contributions from outside the team.

**Comment by syncle** [comment]
I was thinking about making branches only for source code release. For example, the main repo https://github.com/IntelVCL/Open3D only has branches of v0.1, v0.2, .. and master working branch. If we make branches for the development, we might receive too many commit notifications.

> Regarding the visibility of our progress: I've made over 40 commits in the past week on my fork for issue #17 and issue #130 however if we're looking at the main page the last commit was 7 days ago. This doesn't look like a very active project.

I think the progress is visible via [milestone page](https://github.com/IntelVCL/Open3D/milestones). This is just my opinion. We can discuss offline.

**Comment by takanokage** [comment]
I propose that branches are meant for development and can help us move faster. A branch should have a limited life which is the duration of the development on the specific set of features for which the branch was created. Once the work is done on a branch we initiate a pull request and with a merge we close the branch.
I agree we should mark each milestone - this is where tags will help.

**Comment by qianyizh** [comment]
Commits can be made on branches of your own fork. This change to the master repository should be only made via PR.
