### ISSUE TITLE
Compilation issue with Visual Studio 2015

### ISSUE THREAD

**Issue by nosleduc** [IntelVCL/Open3D#285]
Hi

Thanks for this great library.

When I'm trying to compile it with Visual Studio 2015, the file ColoredICP does not compile.
At the line 186, the compiler reports an error that says there is an ambiguous call to three:ComputeJTandJTr. It does not know which one to pick (Odometry, TransformationEstimation or ColoredIICP).

I've fixed it by replacing the line at 148

```
auto compute_jacobian_and_residual = [&]
			(int i, std::vector<Eigen::Vector6d> &J_r, std::vector<double> &r)
```

by 

```
std::function<void(int, std::vector<Eigen::Vector6d> &, std::vector<double>&))> compute_jacobian_and_residual = [&]
			(int i, std::vector<Eigen::Vector6d> &J_r, std::vector<double> &r)
```

There is the same thing with Odometry.cpp and TransformationEstimation.cpp

**Comment by qianyizh** [comment]
Have you applied the latest service pack of Visual Studio 2015?
VS2015 pre SP1 has an incomplete support of C++11.
This might be the reason.

**Comment by nosleduc** [comment]
No I did not apply the last update

**Comment by syncle** [comment]
I agree with @qianyizh.
Every commits and PRs are tested with Visual Studio 2015 using AppVeyor. [Check out the build status using Visual Studio 2015 and 2017.](https://ci.appveyor.com/project/syncle/open3d) They are all passed without syntax error.

[AppVeyor's visual studio 2015 image is **visual studio 2015 with service pack 3**](https://www.appveyor.com/docs/build-environment/#visual-studio-2015).
