### ISSUE TITLE
Global registration behaviour

### ISSUE THREAD

**Issue by nosleduc** [IntelVCL/Open3D#288]
Hi

I'm trying to use the global registration function based on the tutorial using feature matching.
My purpose is to use the global registration and then use an ICP to align my two scans
Each time I running it, I'm getting a different alignment.  Sometimes it works and sometimes it does not work. I need to apply it several times to get my alignment.

I know it comes from the ransac procedure to get the global alignment, it uses different points each time. 
This behaviour seems strange. A user may think that the result depends on the initial position of the scans. It may be interested to use a random procedure that can be repeated. Moreover in the multithreaded version, each thread has its own seed meaning that the result depends on the number of cores of the computer. A user can expect to get the same result independently of his computer

**Comment by syncle** [comment]
Hi @nosleduc 

> Sometimes it works and sometimes it does not work. I need to apply it several times to get my alignment.

I recommend increasing `CorrespondenceCheckerBasedOnEdgeLength(0.9)` to be 0.95 or even closer to 1. It should bring better registration result. However, it would take a bit more computation time.

> A user may think that the result depends on the initial position of the scans. It may be interested to use a random procedure that can be repeated. Moreover in the multithreaded version, each thread has its own seed meaning that the result depends on the number of cores of the computer. A user can expect to get the same result independently of his computer.

The RANSAC algorithm that produces the same result would be interesting, but I don't clearly get how to do it. Could you explain with pseudo code? That would be helpful. Thanks!

**Comment by nosleduc** [comment]
Here there are two things, the seed depends on the time and on the number of cores.
One way to be independent of the number of cores is to compute  in the main thread the different combinations and then use them in the other threads. In general, in a ransac procedure we know the maximum number of iterations. 

To repeat the same random procedure, it may be interested to use an object dedicated to pick random numbers. Maybe the seed must not depends on the time but on something else.

I don't know if in c++11 if std::srand and std::rand is safe thread and reentrant

**Comment by syncle** [comment]
Sorry, It is not clear to me. In general, if success rate of RANSAC is low, the rule of the thumb is to increase iteration or validation number `RANSACConvergenceCriteria(max_iteration = 4000000, max_validation = 500)`, or to increase `CorrespondenceCheckerBasedOnEdgeLength(0.9)` for harder geometric constraints. In this manner, if the success rate is reasonably high (say about 95%), users may feel RANSAC produces the stable result.

I don't think that would require controlling seed numbers. _Repeating the same random procedure_ might break the true randomness. I may misunderstand the idea. If you can push PR for this, I can take a look. Thanks for the suggestion.

**Comment by syncle** [comment]
Aha! I finally got the point what you mean! Regarding this comment

> Moreover in the multithreaded version, each thread has its own seed meaning that the result depends on the number of cores of the computer. A user can expect to get the same result independently of his computer

I think you mean this part
https://github.com/IntelVCL/Open3D/blob/3cbee2e1ccc0ec80ed1f031411335421f59927ea/src/Core/Registration/Registration.cpp#L248-L254

Actually I have extensively tested for this. Let's say there are 10 CPU cores, and 100,000 RANSAC iterations are needed. In parallel implementation, each CPU core iterates 10,000 times. It is required to use the different seed number for each thread because using the same seed for 10 threads are marginally better than single-thread RANSAC with 10,000 iterations. Please see #107.

> Maybe the seed must not depends on the time but on something else.

Yes. I agree with the current scheme can be improved, but using `std::time(0)` is not completely wrong to preserve the randomness. If you suggest better idea for this, I would be appreciated!

**Comment by Sahloul** [comment]
@syncle I suggest porting the [RANSAC implementation from OpenCV](https://github.com/opencv/opencv/blob/master/modules/calib3d/src/ptsetreg.cpp#L76). It is very reliable and well tested.

Another option is to implement the [Optimal RANSAC by Hast et al](http://www.cb.uu.se/~aht/articles/A53-full.pdf). It is easy to implement, but be aware that the authors themselves made a slight glitch in both their paper and the MATLAB implementation. Although this can be fixed with ease, the returned model is actually the last tested model rather than the best model. Furthermore, the last two conditional statements in _Algorithm 1_ seems redundant and can be merged in a single condition.

Perhaps this is also related to #287

**Comment by qianyizh** [comment]
FYI, the RANSAC algorithm currently in Open3D is a re-implementation of the RANSAC algorithm in [Choi2015] "Robust Reconstruction of Indoor Scenes". Under the hood it is a speed-up, bug-fixing, parameter-tuning version of the PCL RANSAC, 😜 

That being said, it is definitely not the best algorithm for global registration (this is also part of the reason we later developed fast global registration). But I tried to expose the interfaces and parameters that I think are useful.

Please suggest better global registration algorithms. As long as it beats the current Open3D implementation in either speed or accuracy on a benchmark dataset (e.g., the redwood benchmark), and someone can produce an implementation, we are happy to adopt it!

**Comment by Sahloul** [comment]
@qianyizh How about the [Sparse Surface Adjustment](http://ais.informatik.uni-freiburg.de/publications/papers/ruhnke12icra.pdf)? It has [an open source implementation](https://github.com/MichaelRuhnke/ssa), and I highly suggest trying it, and ultimately adding it here.

**Comment by nosleduc** [comment]
I understand that you need to pick different seeds to avoid taking same indexes from different threads. I know that from a theoretical  point of view is better to increase the randomness.
Someone knows if std::rand and std::srand is thread safe and reentrant ?

When an algorithm is implemented in a multithreaded way, we may expect just to modify the speed of execution compared to a single core implementation. We may expect to end up with the same solution with a single core or ten core computer cores.

There is an elegant implementation of random procedures by  sweeneychris/TheiaSfM on github.
It can seem cumbersome at the first glance but it really simplifies implementing algorithms based on ransac procedure. Moreover it is easy to change ransac to prosac and other implementations. You can also select different random strategy to pick indexes, which can be very useful in a debug situation or in a "controlled random procedure". The implementation also computes the number of iterations needed by the algorithm based on probabilities given by the user. This number is also updated when the procedure is running.

**Comment by qianyizh** [comment]
@Sahloul can you try it out and report the numbers (speed, recall, precision) comparing with:
https://github.com/IntelVCL/Open3D/blob/master/src/Python/Tutorial/Benchmark/ransac_registration.py

Would love to see something better than the current RANSAC solution.

**Comment by Sahloul** [comment]
@qianyizh I plan to use it in a project, so most likely I will do, but maybe not soon enough.
However, it is not a RANSAC! It is a weighted least-squares method with elastic point-cloud fitting depending on an uncertainty model of the RGB-D sensor.

**Comment by qianyizh** [comment]
I hate RANSAC and the randomness it brings. FastGlobalRegistration is also weighted least squares and we do have a roadmap for it in #142 

Let's test and find out the best global registration algorithm!

**Comment by qianyizh** [comment]
Close it for now. Will reopen once we have updates on benchmarking other global registration algorithms.
