### ISSUE TITLE
Naming convention and conflicts

### ISSUE THREAD

**Issue by Sahloul** [IntelVCL/Open3D#292]
`Core`, `IO`, and `Visualization` libraries are common names, and can result in ambiguous dynamic/static loading issues. I suggest renaming them to something like: `open3d_core`, `open3d_io`, `open3d_viz`

Furthermore, as others might already mensioned, `py3d` is already a reserved name in the pypi hub, so it better be renamed to something like `open3d`.

Finally, the compiled libraries needs to have the version number in their names (e.g., `open3d_core_v011` or so) to avoid linkage issues. I hope to see all these issues addressed by the first release. Keep it up!

**Comment by syncle** [comment]
Good suggestion. The naming conflict should be considered in order to install Open3D in the system path. This suggestion is related to #130, #242. We had put this issue for the 1.0, but worth to discuss for #130.
