### ISSUE TITLE
Executables/libs are not installed

### ISSUE THREAD

**Issue by Sahloul** [IntelVCL/Open3D#293]
It seems the current CMake rules do not include installation instructions for various `lib` and `bin` components.
The same applies for the `TestData` and `Tutorial` directories.

**Comment by syncle** [comment]
Good point. It is necessary upgrade Cmake rules. Feel free to take a token for this.

**Comment by qianyizh** [comment]
Is this supposed to be address in #130 ?

**Comment by Sahloul** [comment]
@qianyizh Very related, but different view. My view is that we can start organizing the built libs and execs in their corresponding directories without worrying about `find_package(Open3D)`. Basically, it is the first four points in [takanokage comment](https://github.com/IntelVCL/Open3D/issues/130#issuecomment-380868970).

**Comment by qianyizh** [comment]
I think so too. Let me merge this issue and discuss there.
