### ISSUE TITLE
Visualizing a sequence of pcd files

### ISSUE THREAD

**Issue by masonsun** [IntelVCL/Open3D#305]
Thanks for all the hard work!

I have a sequence of pcd files that correspond to point cloud data recorded over some period of time. Is there a way to animate/visualize this using the current Open3D implementation?

**Comment by syncle** [comment]
This is an open issue. One work around is to refer @felixendres's solution in #145.

**Comment by syncle** [comment]
and we would be appreciated if somebody can contribute for this.

**Comment by qianyizh** [comment]
I don't think the interface is exposed in python binding.
But for C++, there is a way to do this.

In general, just inherent a class from ``VisualizerWithCustomAnimation``, and create a function similar to:
https://github.com/IntelVCL/Open3D/blob/50a31d8daaf3218b767ddbacc0db4e4f125f13d6/src/Visualization/Visualizer/VisualizerWithCustomAnimation.cpp#L88

Edit ``this->geometry_ptrs_`` in the lambda function bond by ``RegisterAnimationCallback``.
