### ISSUE TITLE
`External` should not be placed inside the `src` directory

### ISSUE THREAD

**Issue by Sahloul** [IntelVCL/Open3D#311]
The `src` directory is intended for the library source itself.

It does not make sense, at least for me, to include the 3rd party dependencies inside the same folder that binds people to the licence and provides a minimal version of the library. I suggest moving it to the outermost directory, and preferably to rename it to `3rdparty`.

**Comment by syncle** [comment]
I agree. This issue is related to #238, but this suggestion is about moving the existing folder.

**Comment by qianyizh** [comment]
sounds good to me.

**Comment by Sahloul** [comment]
In #298, I am addressing both this and #238 by downloading the dependencies rather than including them. I believe everyone will be happy this way!
