### ISSUE TITLE
Split the source and headers

### ISSUE THREAD

**Issue by Sahloul** [IntelVCL/Open3D#312]
When the source and headers are located in the same directory, it becomes almost impossible to enable package installation. That is because the source usually utilize relative `#include`, and even if it an absolute inclusion, the `<open3d/...>` prefix will be impossible to include.

I suggest utilizing the standard `include` and `src` directories.

**Comment by takanokage** [comment]
I believe this would be in conflict with the existing directory structure. Every directory add/delete would have to happen twice.

The above would work great if at the same time we simplify the directory structure: only one directory per library.

For example `Open3D/src/Core` currently contains the following directories:
- Camera
- Geometry
- Integration
- Odometry
- Registration
- Utility

We would move all the files in these folders to `Open3D/src/Core`.

**Comment by takanokage** [comment]
I propose we remove the relative paths from the headers of the same library.
This can work even if we keep the folder structure: we can add those relative paths to the include folders list.

**Comment by Sahloul** [comment]
@takanokage Even if we remove relative paths, as long as we want to install the headers to `include/Open3D`, then the problem will persist, as `Open3D` does not currently exist in the inclusion directives.
