### ISSUE TITLE
Vectorization bugs in MSVC 2015

### ISSUE THREAD

**Issue by Sahloul** [IntelVCL/Open3D#314]
It seems that there is various bugs in the code as seen [here](https://ci.appveyor.com/project/syncle/open3d/build/1.0.197/job/bl4highgup9pm923#L605) and [here](https://ci.appveyor.com/project/syncle/open3d/build/1.0.198/job/v78xjvue34eg20p4#L1718).

I guess all are related to vectorization, and Eigen3 in particular..

**Comment by qianyizh** [comment]
This is a very annoying issue with Eigen.
Can you confirm the issue persist with Visual Studio with the latest SP?

**Comment by Sahloul** [comment]
@qianyizh Yes I did, it was failing! It is already addressed in #298, as [shown here](https://github.com/IntelVCL/Open3D/pull/298/commits/520dc6d7a1865304629c4a7878937fab9f6719b0?w=1)

**Comment by qianyizh** [comment]
Actually @Sahloul can you break #298 down to smaller PRs? It is hard to keep track to so many things in a giant PR. 😄

**Comment by Sahloul** [comment]
It is already conflicting with the HEAD, and it is a tremendous effort to keep rewriting.
And let me predict the future: even if I break it, you will merge the smallest one among all the PRs (as you did now), and I will need to rewrite them again and again and again.. This is endless, and I am already tired! Sometimes rules are for frustration, not for progress..

@qianyizh So, how about you break it yourself? It is a good practice to know how much trouble you give me by merging the smallest PR while always asking to break the PRs.

**Comment by qianyizh** [comment]
I understand your frustration. That's the reason we ask the contributors to submit small PRs from the beginning. So you don't need to break it down into smaller ones. If everyone submits big PRs there is no way to maintain the sanity of the project.

**Comment by Sahloul** [comment]
@qianyizh @syncle If you guys review in a single day or so (remember that you merge for yourselves in seconds), I would be very happy to hold the rest of my PRs until you merge, and thus reduce the lost effort. But waiting for centuries, just to be asked to break it after it becomes huge does not imply that you really care about the library at all.

**Comment by qianyizh** [comment]
You just explained the reason why PRs need to be small in your own post.

**Comment by Sahloul** [comment]
Small PRs if this library is a decent one.. Open3D is currently far far away from matching the minimum standards, thus each PR is highly coupled with other PRs. We cannot just ensure their independence from each other unless we write a three lines every two weeks (so that you catch up).

There is no wonder it is been two years in such sluggish progress and bad shape..

**Comment by qianyizh** [comment]
Why are you wasting your time here then?

**Comment by Stantheman1985** [comment]
Idk

On Apr 17, 2018 3:35 AM, "Qianyi Zhou" <notifications@github.com> wrote:

Why are you wasting your time here then?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/IntelVCL/Open3D/issues/314#issuecomment-381880043>, or mute
the thread

**Comment by Sahloul** [comment]
I need this library to mature, that is why!
I still hope you would realize that a library in its early stages need to sacrifice strict rules for the sake of faster development.
Shall I give up on a mutual understanding and maintain my own fork?

**Comment by Stantheman1985** [comment]
Yep

On Apr 17, 2018 3:39 AM, "Hamdi Sahloul" <notifications@github.com> wrote:

I need this library to mature, that is why!
I still hope you would realize that a library in its early stages need to
sacrifice strict rules for the sake of faster development.
Shall I give up on a mutual understanding and maintain my own fork?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/IntelVCL/Open3D/issues/314#issuecomment-381881198>, or mute
the thread

**Comment by qianyizh** [comment]
Yeah. I would suggest to go ahead with your own fork for now.
I actually did it with PCL myself (had my own fork and maintained it for a few years) and never regret it.
Maybe come back in the future when Open3D is more mature and you will find it useful again.

**Comment by qianyizh** [comment]
I think the discussion is off-topic. I will leave it for a couple of days then delete the posts.
