### ISSUE TITLE
Windows x86 testing + possible failures

### ISSUE THREAD

**Issue by Sahloul** [IntelVCL/Open3D#316]
The current AppVeyor settings only tests Windows x64 platform, but what about x86?

There is a possibility that Windows x86 would fail (such as in [here](https://ci.appveyor.com/project/syncle/open3d/build/1.0.202/job/wp3w4bybtru4bh85)). The failure might be just due to changes I made, so I will investigate further and update!

**Comment by qianyizh** [comment]
Actually I suggest we focus on x64. We already have lots of stuff to worry about and I don't think x86 is a frequent use case.
