### ISSUE TITLE
AppVeyor failure

### ISSUE THREAD

**Issue by syncle** [IntelVCL/Open3D#317]
AppVeyor configuration in the current master branch keeps failing.
The error comes from some `pip` commands:
https://github.com/IntelVCL/Open3D/blob/5bb9fb0bbed6b5dcc243476cf7535caf01c0f304/.appveyor.yml#L35-L36

These lines can be omitted.

**Comment by Sahloul** [comment]
@syncle
> I would like to mention couple of things for you. We have built the library for two years from the scratch. During this procedure, we had to set strict principle and rules to make the library to be light-weight but powerful. Therefore, **we regard contribution page very important. One of the core principle is the consensus. If there is an issue, we submit it on the issue board, after the discussion and decide to work for it, then switch to work and submit pull request.**

It is your word against you!

**Comment by syncle** [comment]
You're right. It was my bad. I didn't expect this will break your PR. I personally thought this is rather independent issue. However, as your spending priceless time, I had to be more careful and shouldn't merge before I got your comment. My apologies.
