### ISSUE TITLE
Question: RANSAC and ICP repeat on condition

### ISSUE THREAD

**Issue by rukie** [IntelVCL/Open3D#322]
I'm using a Velodyne HDL 64 and I know my images scene to scene will be small translations. For the most part, my transformation matrix will be close to
1 0 0 0
0 1 0 0
0 0 1 0
0 0 0 1

Occasionally, I'll end up with a transformation matrix that'll rotate an image by 90 degrees. Would you have any suggestions on how to auto-attempt this again? Should I check the values (0,0), (1,1), (2,2), (3,3) as being >0.99? Or would a math function on the whole matrix possibly be quicker? Just looking for a second opinion I guess. Maybe there's another approach I missed? 

I'll be checking the values from 
edit:
pose_graph.nodes[point_id].pose
edit:

Thanks again for the great tool!

**Comment by syncle** [comment]
Hi @rukie. Can you share code snippet or data so that I can regenerate your issue? Presumably this issue may be related to #276.

**Comment by syncle** [comment]
I quickly went through the script. Overall, it looks good to me except for the several things need to be checked.
- edge_prune_threshold = 50.0: it is normalized. Only [0,1] scale will work.
- parameters: I don't know how the point cloud is distributed, or how it is dense enough. 

Let me give some general idea. Depending on the dataset and configurations, local feature extraction and matching may not working. I think you can debug one by one: pick an easy pair, see/validate point cloud normal, feature extraction matching, and validate ICP. In this manner, you may notice the wrong step breaks the registration result, or find the better parameter configurations. If everything working fine with the pairs, the next thing to validate is global optimization. Visualize pose graph before and after optimization, and check whether the energy decreases.

**Comment by rukie** [comment]
It is definitely a sparse point cloud. 
See https://www.youtube.com/watch?v=09JjEQp9Nxk for an idea. It would be similar to this.

Thank's for catching the pruning threshold! I'll make an update there. 

I've spent considerable time looking at normals and validating them in meshlab. I'm pretty confident it breaks in the RANSAC step, and of course ICP can't make up for that. 

Generally my transforms are very small (see sample). 
[[  1.00000000e+00  -5.84664492e-19   0.00000000e+00   0.00000000e+00]
 [  2.82803125e-19   1.00000000e+00   0.00000000e+00  -2.71050543e-20]
 [  1.08420217e-19   0.00000000e+00   1.00000000e+00   1.35525272e-20]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]
[[  9.99998116e-01   1.73833634e-03  -8.63639802e-04   1.87099813e-03]
 [ -1.73772219e-03   9.99998237e-01   7.11358632e-04   1.75419109e-01]
 [  8.64874860e-04  -7.09856525e-04   9.99999374e-01   7.79016245e-03]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]
[[  9.99992591e-01  -3.84076138e-03   2.59039609e-04   8.06286387e-03]
 [  3.84103031e-03   9.99992076e-01  -1.04579853e-03   3.59428156e-01]
 [ -2.55020894e-04   1.04678576e-03   9.99999420e-01   8.55598405e-03]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]


Right now I'm working on processing 44,000 frames of data. I've been taking groups of 3-4 frames, combining them, and exporting new point clouds. Then I take those new point clouds and repeat the process. My 44,000 frames become 8,000 frames, my 8,000 become 800, and so on. Since I have so much data, I'm okay throwing some of it out the window.

I think I'm going to use something like the following to determine if I should throw it out.
```python
        translation_failed = 0
        for point_id in range(n_pcds):
            if (pose_graph.nodes[point_id].pose[0,0]<0.98):
                if (pose_graph.nodes[point_id].pose[1,1]<0.98):
                    if (pose_graph.nodes[point_id].pose[2,2]<0.98):
                        translation_failed = 1
            if (pose_graph.nodes[point_id].pose[1,0]>0.1):
                translation_failed = 1
            if (pose_graph.nodes[point_id].pose[0,1]>0.1):
                translation_failed = 1
```

**Comment by syncle** [comment]
>I think I'm going to use something like the following to determine if I should throw it out.

Yes, or simply you might try to use trace of the matrix. I found good discussions from https://stackoverflow.com/questions/34139586/how-to-check-if-an-eigenmatrix4f-is-close-to-identity-matrix.

> I'm pretty confident it breaks in the RANSAC step, and of course ICP can't make up for that.

If the feature based matching keep failing due to the nature of the dataset, and the desirable pose is not far from the identity matrix, how about just using local registration method? You can skip global registration steps because local feature is not a good option and the point clouds just require minor pose alignment.

**Comment by rukie** [comment]
Since the lidar system scans radially, I get a set of half circles (I'm only scanning forward 180 degrees). Local alignment tends to drive for placing the semi-circles on-top of each other, rather than aligning features. (with iterative closest point) Using planes seems to alleviate some of this, but tends to be a little more blurry. 

I've had my best luck with the approach above. I think ideally, I need to adjust the parameters based on cloud density. The features work excellent when close to buildings, but as I move into an open field I have more trouble. I can tune for larger open areas, but then issues arise in smaller (dense) clouds. 

Imagine driving on an open country road in the middle of Nebraska, versus driving through wooded hills in Connecticut. That would probably be pretty representative of my current data set.

**Comment by rukie** [comment]
This is a (small) section of scanned terrain as viewed from above. This is 3 frames. There's a very clear radial effect from how the information is scanned. (color refers to intensity of returned). As the lasers scan further from the device, the space between annular rings increases. When terrain is particularly flat, it likes to align those more. 

![image](https://user-images.githubusercontent.com/6559628/38903159-32992272-4269-11e8-9fc1-6a205944b2b1.png)

A single frame as seen from above:
![image](https://user-images.githubusercontent.com/6559628/38903451-8258d25c-426a-11e8-9499-13bdcf2d4a06.png)

Obviously there is more data, this is showing maybe 1/3. Trees/terrain visible in the distance. This is all I'm willing to share publicly however.

**Comment by syncle** [comment]
Thanks for sharing images @rukie. Without the sample data, my best recommendation is not using local features, increasing voxel down sampling size (to reduce non-uniform sampling issue), and apply local alignment algorithm. 

Maybe there would be better solution I am missing. @qianyizh, can you comment something on @rukie's issue?

**Comment by rukie** [comment]
Is there an easy way I can tune parameters based on density of the cloud? Can I easily (and quickly) obtain size and average distance between points? Then I could voxelize based on that information, or crop based on that information. As my scans move around buildings, trees, on/off road the size of each cloud may vary from 20 meters wide to 300 meters wide. Sometimes it'll be dense up close, sometimes I'll have features in the distance. 

This would be an example of more dense clouds (again, 3 frames through the same script):

![image](https://user-images.githubusercontent.com/6559628/38936476-7e2f6bec-42e6-11e8-9711-b0e74304f091.png)

and seen from above:
![image](https://user-images.githubusercontent.com/6559628/38936498-865e6cbe-42e6-11e8-9b32-251b2b4ce0ae.png)

**Comment by rukie** [comment]
For additional detail: each box is a group of 15 frames. You can see that the overall size of my clouds can vary significantly. I have 10 boxes (150 frames at 100,000 points each). The red/blue colors represent trees, and green is mostly ground. 

![image](https://user-images.githubusercontent.com/6559628/39058322-1668761a-4481-11e8-97c7-87115f4f038e.png)

**Comment by syncle** [comment]
Thanks @rukie. This depicts the challenge of real Lidar scans. It is quite interesting. 

> Is there an easy way I can tune parameters based on density of the cloud? Can I easily (and quickly) obtain size and average distance between points?

One naive idea I had is to extract features using multiple scales: for example, you may extract features using 1m, 3m, 5m radius (just example), when you do match, the features should be matched if they are extracted from same scale. In this way, the coarse region will naturally use the feature with larger radius, and vise versa for the dense regions. Again, this is my naive idea :)

**Comment by rukie** [comment]
So lets say I want to try RANSAC 3 times with 3 different scales,
I can run RANSAC easily enough, but to access the RMSE (root mean squared error right?) 
Can I access that as result_ransac.inlier_rmse? Or result_ransac.rmse? Or should I evaluate with fitness instead?

``python
(success_ransac_1, result_ransac_1) = register_point_cloud_fpfh(source_crop, target_crop, source_fpfh_1, target_fpfh_1)
''

**Comment by syncle** [comment]
I think you might need to customize the function instead of iterating RANSAC for three times. You may extend `register_point_cloud_fpfh`. Consider matching the features of the same scale in the function. In this manner, you would not need to care about multiple `result_ransac`s. This idea not implemented though. I just proposing an idea here hoping this might be helpful. 😁

**Comment by rukie** [comment]
I'm not sure I follow. You're suggesting I edit the python function below?
Or do you mean I should modify the c code on function:
```C
RegistrationResult RegistrationRANSACBasedOnFeatureMatching(
```

Could you elaborate just a little more? 

```python
def register_point_cloud_fpfh(source, target, source_fpfh, target_fpfh):
    result_ransac = registration_ransac_based_on_feature_matching(
            source, target, source_fpfh, target_fpfh, 0.075,
            TransformationEstimationPointToPoint(False), 4,
            [CorrespondenceCheckerBasedOnEdgeLength(0.9),
            CorrespondenceCheckerBasedOnDistance(0.075),
            CorrespondenceCheckerBasedOnNormal(0.52359878)],
            RANSACConvergenceCriteria(4000000, 2000))
    if (result_ransac.transformation.trace() == 4.0):
        return (False, np.identity(4))
    else:
        return (True, result_ransac)
```

**Comment by syncle** [comment]
Oh, I was meant to say c++ code, as all the internal implementations are there. You can customize your `RegistrationRANSACBasedOnFeatureMatching` function.

**Comment by syncle** [comment]
Closing the issue due to inactivity. @rukie: Please feel free to reopen if needed.
