### ISSUE TITLE
Persistent Feature Visualization

### ISSUE THREAD

**Issue by rukie** [IntelVCL/Open3D#332]
Is it possible to view the FPFH feature persistence?

For the most part my attempts at aligning point clouds have been based on trial and error. I jump in victory when I see "RANSAC Succeeded!" As I continue building larger scenes with more information, I find myself consistently repeating this process. 

I'm trying to understand how scenes like below are generated. 

![image](https://user-images.githubusercontent.com/6559628/39331479-52784f2a-496a-11e8-8f76-39e77639014b.png)

![image](https://user-images.githubusercontent.com/6559628/39331936-9069eba8-496b-11e8-9063-d9d66432cf22.png)

**Comment by syncle** [comment]
>Is it possible to view the FPFH feature persistence?

Open3d does not provide feature persistence yet. Our aim was to provide an implementation of well-proven FPFH features for Open3D users, not the additional metric for analysis.

However, I think it can be implemented in python by following the description in the paper. You extract multiple scale FPFH features, and see how it is distinguish a feature over the scale. [According to the paper](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.332.3710&rep=rep1&type=pdf), the distinctiveness can be determined by analyzing histogram similarities w.r.t the that of adjacent points. This might involve mean and variance analysis of the histogram, which can be computed using python scipy packages.

**Comment by rukie** [comment]
Following up on this, say I dump out the variable source_fpfh
What is the direction of the array? Do I have 1 histogram for each point in the cloud? FPFH isn't actually reducing the number of histograms, its just calculating in a method that minimizes memory calls right?

And then I'm reading the histogram, what is its significance? What would a "good" histogram look like?

**Comment by rukie** [comment]
I guess part of where I'm stuck, is I see the definition for FPFH
![image](https://user-images.githubusercontent.com/6559628/39397056-a6a83740-4abe-11e8-9c87-22075e9abdb7.png)

and SPFH is a histogram of angles and vectors
![image](https://user-images.githubusercontent.com/6559628/39397138-ec468184-4abf-11e8-8af9-e66c68916c0e.png)

I don't really understand how these are binned. I do see that its resized to 33 bins? I think?
feature->Resize(33, (int)input.points_.size());

But generally we:
Calculate SPFH at each point P_i
Calculate FPFH at each point P_i from summation of weighted SPFH within given radius

For example: the FPFH of the center red dot consists of 6 (including red dot) SPFH calculations? 

![image](https://user-images.githubusercontent.com/6559628/39397355-76ed9cd4-4ac3-11e8-838b-7e8c161c06d7.png)


I apologize for rambling, I'm just trying to make sense of the equations.

Note: Paper I'm referencing
https://pdfs.semanticscholar.org/c254/a46b4d42862de6ac254edb05f189fa139aa3.pdf

**Comment by qianyizh** [comment]
Can you elaborate what is a feature persistence?

The way Open3D works is that you first call ``compute_fpfh_feature()``, which gives you an array of 33-d vectors. Then you compute some value that you think if important (e.g., you can choose the x-th dimension of the 33-d vector) and render it in ``PointCloud.colors``. Then you call ``draw_geometries()`` to render it.

**Comment by syncle** [comment]
Closing for now, because this thread is not active.

**Comment by kaixin-bai** [comment]
@rukie I tried qianyizh's method and get the visualization result of FPFH features like this:
![Screenshot_2021-01-27_17-18-32](https://user-images.githubusercontent.com/38804949/106020127-b6ff3580-60c3-11eb-8581-523fa1d0ddcf.png)

**Comment by aycameric** [comment]
@qianyizh @kaixin-bai  how can I render a (1123,) vector (one row from fpfh.data) in Pointcloud.colors?

**Comment by ammaryasirnaich** [comment]
> @rukie I tried qianyizh's method and get the visualization result of FPFH features like this:
> ![Screenshot_2021-01-27_17-18-32](https://user-images.githubusercontent.com/38804949/106020127-b6ff3580-60c3-11eb-8581-523fa1d0ddcf.png)



> visualization result of FPFH features


Hi kaixin-bai,
         Please can you guide me a little as you have managed to visualise the FPFH feature. I am lost with the visualization result of FPFH features. After getting feature with
` fragment = fragment = o3d.io.read_point_cloud("fragment.ply")
 featureout = o3d.pipelines.registration.compute_fpfh_feature(fragment, o3d.geometry.KDTreeSearchParamHybrid(radius=0.1, max_nn=30))   `  

 I am not sure how to visualize the _featureout_ after it?

**Comment by kaixin-bai** [comment]
> > @rukie I tried qianyizh's method and get the visualization result of FPFH features like this:
> > ![Screenshot_2021-01-27_17-18-32](https://user-images.githubusercontent.com/38804949/106020127-b6ff3580-60c3-11eb-8581-523fa1d0ddcf.png)
> 
> > visualization result of FPFH features
> 
> Hi kaixin-bai, Please can you guide me a little as you have managed to visualize the FPFH feature? I am lost with the visualization result of FPFH features. After getting feature with
> 
> ```
> fragment = o3d.io.read_point_cloud("fragment.ply")
> featureout = o3d.pipelines.registration.compute_fpfh_feature(fragment, o3d.geometry.KDTreeSearchParamHybrid(radius=0.1, max_nn=30))  
> ```
> 
> I am not sure how to visualize the _featureout_ after it?

you could scale the feature vector to 0-1, and then give it to the color vector of the point cloud, then it could  be visualized.

**Comment by NahomKidane** [comment]
import matplotlib.pyplot as plt

> > > @rukie I tried qianyizh's method and get the visualization result of FPFH features like this:
> > > ![Screenshot_2021-01-27_17-18-32](https://user-images.githubusercontent.com/38804949/106020127-b6ff3580-60c3-11eb-8581-523fa1d0ddcf.png)
> > 
> > 
> > > visualization result of FPFH features
> > 
> > 
> > Hi kaixin-bai, Please can you guide me a little as you have managed to visualize the FPFH feature? I am lost with the visualization result of FPFH features. After getting feature with
> > ```
> > fragment = o3d.io.read_point_cloud("fragment.ply")
> > featureout = o3d.pipelines.registration.compute_fpfh_feature(fragment, o3d.geometry.KDTreeSearchParamHybrid(radius=0.1, max_nn=30))  
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I am not sure how to visualize the _featureout_ after it?
> 
> you could scale the feature vector to 0-1, and then give it to the color vector of the point cloud, then it could be visualized.

Something like this...


    import matplotlib.pyplot as plt
    fpfh = np.asarray(feature.data[2,:])
    colormap = 'viridis'
    # # #Normalize
    fpfh_colors = plt.get_cmap(colormap )(
             (fpfh - fpfh.min()) / (fpfh.max() - fpfh.min()))
    fpfh_colors = plt.get_cmap(colormap)(fpfh)
    fpfh_colors = fpfh_colors[:, :3]


    fpfh_pcd =o3d.geometry.PointCloud()
    fpfh_pcd.points = pcd.points
    fpfh_pcd.normals = pcd.normals
    fpfh_pcd.colors = o3d.utility.Vector3dVector(fpfh_colors)
