### ISSUE TITLE
Unsollicited subscription to the open3d ML

### ISSUE THREAD

**Issue by ggouaillardet** [IntelVCL/Open3D#335]
Folks,

I just received this by email

> We are sending you this email believing you will be interested
on what we are doing, and in hope you can join us.
If you received duplicate notifications or find it irrelevant to
your interests, then kindly accept our deepest apologies.
Although we are inviting you to our users mailing list, you can always
unsubscribe from it by visiting the URL: http://users.lists.open-3d.org

This way of promoting your project is so wrong imho.

Anyway, may I ask how you got by email address ?
Did you slurp it from some github commit messages ? or did you get it from some database at Intel ? or from an other source ?

Cheers,

**Comment by lovell** [comment]
I received this unsolicited email too. Confusingly I think it's from the maintainers of a very similarly-named clone at https://github.com/Open-3D/Open-3D

The comments in https://github.com/IntelVCL/Open3D/issues/321 and https://github.com/Open-3D/Open-3D/issues/31 suggest the act of cloning has not been "friendly" and would appear to be intentionally piggy-backing on the existing Open3D name.

**Comment by ggouaillardet** [comment]
you are right, and I posted an issue to the wrong (but legitimate) repository.
I will close this issue and re-post it to the offending repo (and I am not the only one ...)

**Comment by syncle** [comment]
Thanks @ggouaillardet for reporting the issue. Could I ask forwarding the email to me? We would like to collect their activities.

**Comment by ggouaillardet** [comment]
@syncle here is the full email I received (I edited out my email address though)

note the
```
pip install open3d
```

I would have expected `pip install open-3d` not to confuse this fork with the initial project.

If the software engineering skills of the members of this fork match their marketing skills, then you might not have to bother collecting their activities ;-)
Feel free to browse (closed) issue 34 in their github repo if you do not see what I mean (or want to have a good laugh and/or keep your lawyers busy)


> Hello everyone, 
> 
> We are sending you this email believing you will be interested
> on what we are doing, and in hope you can join us.
> If you received duplicate notifications or find it irrelevant to
> your interests, then kindly accept our deepest apologies.
> Although we are inviting you to our users mailing list, you can always
> unsubscribe from it by visiting the URL: http://users.lists.open-3d.org
> 
> This is Hamdi Sahloul from the Open3D community.
> Open3D community is an independent, non-profit, open-source organization 
> aiming to guarantee unbiased and rapid development of Open3D library. 
> 
> Open3D library is a modern and lightweight library for 3D data 
> processing, which exposes a set of carefully selected data structures 
> and algorithms in both C++ and Python. It is compatible with various 
> operating systems (Linux, macOS, Windows) and compilers, and can be 
> built out of box without any complications. 
> Open3D library was originally developed in Intel Labs (currently active) 
> but we find them more focused on implementing their algorithms 
> to promote their own researches. 
> However, to provide the society with a free (as in freedom) library, 
> without narrow orientations or specific interests, 
> we launched our own fork at: http://code.open-3d.org/
> 
> We are thrilled to announce that our Open3D community version had 
> underwent a remake phase, and we have just released v0.1.2 (beta), which 
> is available here: http://code.open-3d.org/releases/
> 
> The good news for Python users is that they can start using the library 
> immediately via `pip install open3d`. The documentation 
> (http://docs.open-3d.org/) includes various tutorials to help getting 
> started. C++ developers can also find the library API that covers the 
> whole functionality at http://api.open-3d.org/
> 
> Since the current release is just the first baby steps in our Open3D 
> roadmap, we are currently looking for contributors in various fields 
> (C++, Python, Computer Vision experts, Software engineering, etc). If 
> you can help, why do not you give us a hand at our Github organization? 
> Even if you are not a developer, receiving your feedback and ideas can 
> help us! Kindly be asked to star our Github project to receive our 
> updates. Our Github project is available at: http://code.open-3d.org/
> 
> Our ultimate goal is to make Open3D a central repository for 3D data and 
> strong algorithms. We are just at the start with the project, but we aim 
> to eventually build a sophisticated library for processing and 
> constructing different geometries and representations. 
> Hopefully, by implementing bleeding-edge algorithms, we can help the 
> researchers to focus more on their ideas rather than spending tremendous 
> time in implementing things. This can also help in unifying benchmark 
> frameworks, and ensuring accurate and meaningful researches. 
> 
> Looking forward to welcome you at Open3D community, 
> Sincerely yours, 
> Hamdi Sahloul 
> 
> On behalf of Open3D community 
> www.open-3d.orgWelcome to the Users@open-3d.org mailing list!
> 
> To post to this list, send your message to:
> 
>   users@open-3d.org
> 
> General information about the mailing list is at:
> 
>   http://open-3d.org/mailman/listinfo/users_open-3d.org
> 
> If you ever want to unsubscribe or change your options (eg, switch to
> or from digest mode, change your password, etc.), visit your
> subscription page at:
> 
>   http://open-3d.org/mailman/options/users_open-3d.org/EDITED
> 
> 
> You can also make such adjustments via email by sending a message to:
> 
>   Users-request@open-3d.org
> 
> with the word `help' in the subject or body (don't include the
> quotes), and you will get back a message with instructions.
> 
> You must know your password to change your options (including changing
> the password, itself) or to unsubscribe without confirmation.  It is:
> 
>   EDITED
> 
> Normally, Mailman will remind you of your open-3d.org mailing list
> passwords once every month, although you can disable this if you
> prefer.  This reminder will also include instructions on how to
> unsubscribe or change your account options.  There is also a button on
> your options page that will email your current password to you.
