### ISSUE TITLE
Packaging review for Arch Linux, split PKGBUILD

### ISSUE THREAD

**Issue by dylon** [IntelVCL/Open3D#336]
Hi,

I've packaged Open3D in the Arch Linux User Repository (AUR), and would like you to review my build scripts when you get the time.  I have two of them, one for the latest tagged release and another for the latest git commit.  Each is split into three packages: `open3d`, `python-open3d`, and `python-py3d`, and their `"*-git"` counterparts, respectively.

- [open3d/PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=open3d)
- [open3d-git/PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=open3d-git)

PKGBUILD files are simple Bash scripts with intuitive naming schemes.  For more information, please reference [the official wiki on PKGBUILDs](https://wiki.archlinux.org/index.php/PKGBUILD).  The functions in my build scripts are executed as follows:

1. `pkgver()` grabs the latest tagged version or git commit, respectively.
2. `prepare()` creates the `build/` directory.
3. `build()` compiles the library, binaries, and Python bindings.
4. `check()` runs the unit tests.
5. `package_open3d()` and `package_open3d-git()` install the library and binary files to a local directory for packaging.
6. `package_python-open3d()` and `package_python-open3d-git()` install the Python bindings to a local directory for packaging.
7. `package_python-py3d()` and `package_python-py3d-git()` install the same Python bindings to a local directory for packaging (which the user installs depends on his preferences).

The corresponding detail pages follow:
- [open3d](https://aur.archlinux.org/packages/open3d/)
- [python-open3d](https://aur.archlinux.org/packages/python-open3d/)
- [python-py3d](https://aur.archlinux.org/packages/python-py3d/)
- [open3d-git](https://aur.archlinux.org/packages/open3d-git/)
- [python-open3d-git](https://aur.archlinux.org/packages/python-open3d-git/)
- [python-py3d-git](https://aur.archlinux.org/packages/python-py3d-git/)

Regards,
Dylon

**Comment by syncle** [comment]
Thanks @dylon! This is a priceless contribution to Open3D. I will review the script.

**Comment by syncle** [comment]
I think the script can go as-is. The script refers `gtest` and installs two python packages which are both preferable to users.
