### ISSUE TITLE
IO problem about reading and writing ply file

### ISSUE THREAD

**Issue by SamuelSJTU** [IntelVCL/Open3D#337]
I see the key word compress in write_point_cloud, but it seems useless, what is this meaning? Also, in the code, we only can save the pointcloud in double format, could I use float format? Do I have to hack the IO code?

**Comment by qianyizh** [comment]
The ascii/binary switch works only for PLY and PCD format. The compression switch works only for the PCD format.

For PCD format, the data is written in float (PCD does not support double). For PLY format, the data is written in double. 

To hack the PLY format to make it write float, just need to change these code:

https://github.com/IntelVCL/Open3D/blob/352d2f4ca0dd577b37053e946eec5f2cf5afc423/src/IO/FileFormat/FilePLY.cpp#L284-L327

**Comment by SamuelSJTU** [comment]
Thank you
