### ISSUE TITLE
3 shared objects not found on import py3D 

### ISSUE THREAD

**Issue by marcel-bariou** [IntelVCL/Open3D#341]
Platform Linux 16-04, no message error on compile!
  But => ldd  /home/mbariou/.local/lib/python3.6/site-packages/py3d.cpython-36m-x86_64-linux-gnu.so
	linux-vdso.so.1 =>  (0x00007fffd17fc000)
	libVisualization.so => not found
	libIO.so => not found
	libCore.so => not found
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f516808d000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f5167e77000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f5167aad000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f51677a4000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f5168749000)

Thanks for help or hints if Idea

**Comment by takanokage** [comment]
@marcel-bariou 
Could you be more specific about the steps that led to this issue?
I have some limited experience with Open3D building/installing/importing, maybe I can help.

A possible hack: I personally haven't tried the shared libraries path. Seems to work when I build the static libraries for Open3D. Not sure if that is an option for you.

**Comment by jakobwilm** [comment]
The "not found" libraries do not exist in the dynamic library loader search path. See e.g. the answers to this question: https://unix.stackexchange.com/questions/22926/where-do-executables-look-for-shared-objects-at-runtime

**Comment by marcel-bariou** [comment]
hello ! **@jakobwilm & takanokage** Thanks for your interest. I succeed I tell you !
I  met the trouble when, after compile and install,  I have done : import py3d in Python, libVisualizaition.so  and two other libraries  were not found by  py3d.cpython-36m-x86_64-linux-gnu.so 
In fact the missing libraries were not in the lib path, because they were not installed. they were present in the build directory. So I place them manually in /usr/local/lib/open3d, I indicate the path /usr/local/lib/open3d  in  /etc/ld.so.conf.d/open3d.conf,  I run ldconfig and eveything was OK! Something is missing in the install directives.
