### ISSUE TITLE
Fast Global Registration Bugs

### ISSUE THREAD

**Issue by michael-peng** [IntelVCL/Open3D#344]
When I run fast global registration to register a model with multiple views, the registration is valid only for the first view. The debug message shows that the means and scales are 0s and 1s for all the views except for the first one. I found that pointcloud and features keep adding to pointcloud_ and features_ which are defined globally in FastGlobalRegistration.cpp, but the registration only applied to the first two elements of them. After clearing them (pointcloud_.clear(), features_.clear(), and corres_.clear())after every run, the registration works well.

The second issue is that you decreased the mu (or say, par in the definition) at the beginning of the optimization. In this case, the correspondence matching threshold will never be 1, which will include the whole set of the point cloud.

Thanks for sharing your code with the community!

**Comment by syncle** [comment]
You are right. These issues can cause problem. I was thinking about polishing FGR code as it was adopted roughly from old repository. I will work on this when other issues are addressed.
