### ISSUE TITLE
Installing Open3D in vanila ubuntu 14.04

### ISSUE THREAD

**Issue by wxt-github** [IntelVCL/Open3D#346]
Hi,everyone!
I can't understand what the first command in the ubuntu installation of the official website means just like 
"util/scripts/install-deps-ubuntu.sh"

**Comment by wxt-github** [comment]
But how do I run that command, because that doesn't seem to be the way the command is run? @takanokage

**Comment by wxt-github** [comment]
I know the command now,but I find the error  E: 未发现软件包 libglfw3-dev.How can I solve it？

**Comment by wxt-github** [comment]
My linux system is ubuntu14.04

**Comment by syncle** [comment]
``libglfw3-dev`` is not recognizable package in ubuntu 14.04. You can Ignore it as Open3D includes glfw3.3 dev. Open3D will built from source.

**Comment by wxt-github** [comment]
I ignore it but I have error:
/home/wxt/Open3D/src/External/pybind11/include/pybind11/detail/common.h:111:20: fatal error: Python.h: 没有那个文件或目录(no file or directory).How can I solve it? @syncle

**Comment by syncle** [comment]
I think you don't have python in your system, or python is not correctly installed.

**Comment by wxt-github** [comment]
But not all linux systems come with python?I have a try.

**Comment by syncle** [comment]
Yeap, but we highly recommend python binding because it provides much better API. If you don't want python binding of Open3D, you can simply add ``-DOpen3D_BUILD_PYTHON_BINDING=OFF`` in your cmake command.

**Comment by wxt-github** [comment]
After I installed python3.5.0, I successfully built a py3d target with the "make -j" command.And I run "cd util/scripts" and "./install.sh" successfully too.but when I use python import py3d running Open3D tutorials,I have an error:

Traceback (most recent call last):
  File "rgbd_redwood.py", line 6, in <module>
    from py3d import *
ImportError: ImportError: No module named 'numpy'

Is this because I did not use python binding?    @syncle

**Comment by takanokage** [comment]
You need to install numpy.
In fact you need to run 'util/scripts/install-deps-python.sh'.

**Comment by wxt-github** [comment]
Thank you for your reply,but is this command you are referring to as incomplete, shouldn't the **.sh file be preceded by "./"? Because I ran this command but suggested that there was no such file or directory, so the command I run is "sh ~/Open3D/util/scripts/install-deps-ubuntu.sh". @takanokage

**Comment by syncle** [comment]
Good, @wxt-github pointed typos in Open3D documentation. @wxt-github, can you try making a pull request? You can participate Open3D development! You can fork, make a new branch with your favorite name, replace ``util/scripts/...`` with ``./util/scripts/...`` in https://github.com/IntelVCL/Open3D/blob/master/docs/getting_started.rst, and make a pull request. :)

**Comment by takanokage** [comment]
The documentation doesn't need changing. It was written with the awareness that the user will know how to run a bash script and how to navigate the filesystem on Ubuntu.

@wxt-github As you observed one way to run the script is to prefix with the `sh` command. However the scripts in question have been marked as executables and you can also run them as `./install-deps-ubuntu.sh` after you `cd <Open3d_root>/util/scripts`.
The command you ran `sh ~/Open3D/util/scripts/install-deps-ubuntu.sh` is specific to your machine. Other people may chose to install in a different location. For this reason the path provided in the documentation is only relative to the root of Open3D.
