### ISSUE TITLE
create_point_cloud_from_rgbd_image failed

### ISSUE THREAD

**Issue by channingxiao** [IntelVCL/Open3D#352]
I use "create_point_cloud_from_rgbd_image(rgbd_image, PinholeCameraIntrinsic.get_prime_sense_default())"  to create cloud point from RGBD data, and I got the following error.
Traceback (most recent call last):
  File "rgbd_redwood.py", line 25, in <module>
    PinholeCameraIntrinsic.get_prime_sense_default())
TypeError: unbound method get_prime_sense_default() must be called with PinholeCameraIntrinsic instance as first argument (got nothing instead).

I got the same error when run it's demo "rgbd_redwood.py".

Here is what I tried
I changed  "PinholeCameraIntrinsic.get_prime_sense_default()" to "PinholeCameraIntrinsic().get_prime_sense_default()" , then I got Invoked with: PinholeCameraIntrinsic with width = -1 and height = -1. 
I read the code, 
const PinholeCameraIntrinsic PinholeCameraIntrinsic::GetPrimeSenseDefault()
{
    return PinholeCameraIntrinsic(640, 480, 525.0, 525.0, 319.5, 239.5);
}
I did not really get what's is going on here?

I was using the newest master branch, 03ee3e49e13028511ab9f7cc1d866e009cbaf5bd, and the lib was compiled from source on Ubuntu 14.04 with python 2.7.14.

**Comment by channingxiao** [comment]
I workout with    pcd = create_point_cloud_from_rgbd_image(rgbd_image,
            PinholeCameraIntrinsic(640, 480, 525.0, 525.0, 319.5, 239.5)).
 Then here I got another problem, the cloud points are in gray, which I think should be colored. 
Change "create_point_cloud_from_rgbd_image(rgbd_image, PinholeCameraIntrinsic.get_prime_sense_default())" to "create_point_cloud_from_rgbd_image(rgbd_image,
            PinholeCameraIntrinsic(640, 480, 525.0, 525.0, 319.5, 239.5))" in  rgbd_redwood.py, then you will reproduce the problem.

**Comment by syncle** [comment]
I found why this happens. It happens Python 2.7, not 3.6. In Python 2.7, returned class ``PinholeCameraIntrinsic`` is not a class instance. I pushed a new PR for fixing this issue.

**Comment by qianyizh** [comment]
Good catch. I didn't know Python2.7 and Python3.x can have different behaviors on this.
