### ISSUE TITLE
Does the lib support "registration to a template" ?

### ISSUE THREAD

**Issue by channingxiao** [IntelVCL/Open3D#354]
I am new to the geometry, as what I understand about the registration, it does the following things, correct me if i am wrong.
For a source point set  S( X1, X2, X3, X4, ..., Xn) and target point set T(Y1, Y2, Y3, Y4, ..., Ym), the registration find some pairs between the source point set and the target point set  P( (Xi1, Yj1), (Xi2, Yj2) ..., (Xik, Yjk)),  Here k <= min(n,m), which means there may be some points in source point set which are not include in pairs, and the same with target point set. So I have some questions about the registration procedure.
1. Dose Registration( S, T) == Registration( T, S) ? I mean they get the same pair set.

2. I read the documentation, but not dive into the code yet,  what is the difference between Global registration and the ICP's registration? From the documentation and demo, the main difference is about the Accuracy and Efficiency ??

3.  Do the lib support "registration to a template"? I do not know if "registration to a template" is the correct word, anyway here is what I mean by "registration to a template". For a given data set, D(S1, S2, ..., Sn). here each Si(Xi1, Xi2,..., Xik) may have different  number of points, and We have a target cloud point T(Y1, Y2, ..., Ym) which is a template.  I want to registrate the data set D to T, which means, for each Si in T,  I want to find pairs P(Si, T) = {(X1,Y1), (X2,Y2), ...(Xm, Ym)} which has exactly m pairs, the same as the number of points in target cloud point. So there maybe some X's are not in Si, which mean I need to approximate these X's. Does any body have ideas how to do this? or which lib may support this need.??

Many thanks!

**Comment by channingxiao** [comment]
You can build your own matching pipeline. The tutorials provides pairwise registration examples you can use. Depending on your data structure, you can extend it for your need. For example

for Ti in T:
   for Si in S:
      pairwise alignment between Ti and Si using global + local registration
      # http://open3d.org/docs/tutorial/Advanced/global_registration.html
      keep only the best alignment pair and so on



I think you misunderstood me. The key point of my need is to get the number of corresponding pairs exactly the same with the number of points of template point cloud.

**Comment by syncle** [comment]
That is the part need to be designed :) I just suggested full matching between scenes and templates using pairwise matching module. Consider making a confusion matrix, and apply some algorithm that can pick the templates. I think some dynamic programming can be applied for this problem.

**Comment by syncle** [comment]
Closing for now. @channingxiao If you find any useful for this task, feel free to make a PR. :)
