### ISSUE TITLE
Result of pose graph optimization same as the input pose graph

### ISSUE THREAD

**Issue by SubMishMar** [IntelVCL/Open3D#363]
I am trying to use the open3d implementation of posegraph optimization for optimizing the poses of the Manhattan g2o format dataset. But due to some strange reason, the output of the optimization process is identically same to the input pose graph. Can anyone tell me why is it so?

Here is the code:

```python
import numpy as np
import sys

sys.path.append("../..")
sys.path.append("../Utility")
from py3d import *
from common import *
from opencv import *
import matplotlib.pyplot as plt
import sys

#from optparse import OptionParser

counter = 1;

pose_graph = PoseGraph()


set_verbosity_level(VerbosityLevel.Debug)

g = open('unoptimized_pose_graph.txt', 'w') # for purpose of plotting
i = 0;
with open('input_M3500_g2o.txt','r') as f:
	for line in f:
		if(line.split(' ')[0] == 'VERTEX_SE2'):
			x = float(line.split(' ')[2])
			y = float(line.split(' ')[3])
			theta = float(line.split(' ')[4])
			c = np.cos(theta)
			s = np.sin(theta)
			wTi = np.array([[ c, -s, 0, x], [ s, c, 0, y], [ 0, 0, 1, 0], [ 0, 0, 0, 1]])
			pose_graph.nodes.append(PoseGraphNode(wTi))
			g.write(str(i) + ' ' + str(x) + ' ' + str(y) + '\n')
			i = i + 1
		else:
			source_id = int(line.split(' ')[1])
			target_id = int(line.split(' ')[2])

			x = float(line.split(' ')[3])
			y = float(line.split(' ')[4])
			theta = float(line.split(' ')[5])
			c = np.cos(theta)
			s = np.sin(theta)
			trans = np.array([[ c, -s, 0, x], [ s, c, 0, y], [ 0, 0, 1, 0], [ 0, 0, 0, 1]])

			shape = (6, 6)
			info = np.zeros(shape)

			info[0][0] = float(line.split(' ')[6])
			info[1][1] = float(line.split(' ')[9])
			info[5][5] = float(line.split(' ')[11])

			# print(info)
			if abs(source_id - target_id) == 1:
				pose_graph.edges.append(PoseGraphEdge(source_id, target_id, trans, info, uncertain=False))
			else:
				pose_graph.edges.append(PoseGraphEdge(source_id, target_id, trans, info, uncertain=True))
f.close()
g.close()

print("Optimizing PoseGraph ...")

set_verbosity_level(VerbosityLevel.Debug)
method = GlobalOptimizationLevenbergMarquardt()
criteria = GlobalOptimizationConvergenceCriteria()
option = GlobalOptimizationOption(
		max_correspondence_distance = 0.03,
		edge_prune_threshold = 0.25,
		reference_node = 0)
global_optimization(pose_graph, method, criteria, option)
set_verbosity_level(VerbosityLevel.Error)

f = open('optimized_pose_graph.txt', 'w') #for purpose of plotting
for i in range(len(pose_graph.nodes)):
	x = pose_graph.nodes[i].pose[0][3]
	y = pose_graph.nodes[i].pose[1][3]
	f.write(str(i) + ' ' + str(x)+' '+str(y)+'\n')
f.close()

```
`

**Comment by syncle** [comment]
Can you share input_M3500_g2o.txt too? I will have a look.

**Comment by syncle** [comment]
Infomation matrix should not have zero diagonal element. Otherwise, it will produce zero residual.
Replacing
```
info = np.zeros(shape)
```
this with
```
info = np.ones(shape)
```
will minimize graph energy. I got this
```
[GlobalOptimizationLM] Optimizing PoseGraph having 3500 nodes and 5453 edges. 
Line process weight : 0.082639
[Initial     ] residual : 7.036830e+04, lambda : 1.448914e+01
[Iteration 00] residual : 3.065880e+03, valid edges : 1826, time : 979.903 sec.
:
```

A few notes:
- I am not sure how this file fills out information matrix. Filling only info[0][0], info[1][1], and info[5][5] looks bit unfamiliar to me
- Single iteration took very long. Open3d uses Eigen implementation of dense LDLT. This part could be improved.
- This function takes a long time to get a determinant. This function can have a switch that skips determinant computation. 
https://github.com/IntelVCL/Open3D/blob/355fdf0352ab99dfeff4cce5a23e365cf153fbaf/src/Core/Utility/Eigen.cpp#L35-L51

**Comment by SubMishMar** [comment]
@syncle , yes thats the right link to the dataset I am using.

**Comment by SubMishMar** [comment]
@syncle Which part do you think is the major bottle neck? is it

```Cpp
	double det = A.determinant();
```
or 
```Cpp
Eigen::MatrixXd x = A.ldlt().solve(b);
```

**Comment by syncle** [comment]
You're right. It does not use this function. The only bottleneck is ``Eigen::VectorXd delta = H.ldlt().solve(b);`` I am looking your description about information matrix.

**Comment by syncle** [comment]
I think nodes are fine, but filling information matrix need to be carefully considered to use g2o compatible dataset in open3d. 

Open3D's Pose graph optimization follows the definition of information matrix described in here: http://redwood-data.org/indoor/registration.html (please see Eq 8) The key idea is to embed point to point distance into an information matrix.

**Comment by SubMishMar** [comment]
I will check it out, thanks.

So, you say that there is some difference between the way information matrices are defined for g2o and open3d?

**Comment by syncle** [comment]
That's awesome. I also found some related bug and submitted fix in #368. Another difference is that g2o uses quaternion for representing rotational components, whereas open3d uses linear coefficients for skew symmetric matrix, which is not exact rotation matrix.

Another thing is open3d builds information matrix ``\sum_q [-q_x | I ]^T * [-q_x | I ]``where q is not quatanion, it is from a correspondence. (please see http://redwood-data.org/indoor/registration.html).

**Comment by SubMishMar** [comment]
"whereas open3d uses linear coefficients for skew symmetric matrix, which is not exact rotation matrix"

What do you mean by this?

**Comment by syncle** [comment]
Yes. Please see this
https://github.com/IntelVCL/Open3D/blob/355fdf0352ab99dfeff4cce5a23e365cf153fbaf/src/Core/Registration/GlobalOptimization.cpp#L42-L50

**Comment by SubMishMar** [comment]
@syncle, I was wondering if we can provide any arbitrary information matrix (ofcourse it must be valid information matrix, satisfying all basic properties) to the pose graph optimization algorithm in open3d or it should necessarily be generated from one of the various open3d functions which return the information matrix for eg `get_information_matrix_from_point_clouds()` or

**Comment by qianyizh** [comment]
Yes, I believe you can use any valid information matrix.

**Comment by SubMishMar** [comment]
While executing the reconstruction tutorial given in the open3d website on the 016 dataset I realized that the result of the final integration doesnt change if I use or dont use pose graph optimization. @syncle @qianyizh , can you please explain this? Is it because of the fact that the number of poses being optimized is pretty small?

**Comment by syncle** [comment]
We just merged a patch related to the information matrix. It will be needed to make a pose graph again. Or, It maybe just because the pose graph is much accurate than before. With the patched version, I observe the tutorial script takes just 3~5 times of LM iteration, while energy is reduced 20x smaller than the initial one.

**Comment by SubMishMar** [comment]
Interesting. The optimization works for sure, but the changes on the final integration is not prominently visible. Probably because the initial alignment algorithms work very well.

Besides, I replaced the ldlt thing by using sparse cholesky decomposition. Something like this:

```C++
			Eigen::MatrixXd H_LM = H + current_lambda * H_I;
			Eigen::SparseMatrix<double> H_LM_sparse = H_LM.sparseView();
			Eigen::SimplicialCholesky<Eigen::SparseMatrix<double>> chol(H_LM_sparse);
			Eigen::VectorXd delta = chol.solve(b); 
```
So, now the manhattan dataset is processed pretty fast and it takes about 2 seconds per iteration (earlier it used to take 500 seconds), but I still dont understand how to input the information data available in manhattan dataset into open3d.

**Comment by syncle** [comment]
WOW, this is really awesome. Thanks Subodh! You can submit your changes for the better Open3D :)

**Comment by SubMishMar** [comment]
Okay, I will submit a PR later today. Thanks :)

**Comment by SubMishMar** [comment]
This issue needs to be closed as the "Result of the pose graph optimization was same as the input" only because there were not enough loop closure edges added to the graph. Adding enough loop closure edges will give a different result (which may not always be the best). 

But, the other issues mentioned in the above thread still needs to be solved.

**Comment by szx0112** [comment]
Is it possible for us to view the pose graph optimization process (such as iterations of cost reduction), so we can understand the error really decreasing?

**Comment by griegler** [comment]
@szx0112 could you please open a new issue with your question.
