### ISSUE TITLE
Focal length is not used in rendering

### ISSUE THREAD

**Issue by samarth-robo** [IntelVCL/Open3D#365]
I adapted the `headless_rendering.py` example and created this code to render a 3D mesh given the camera intrinsics and extrinsics:
```
import open3d
import numpy as np
# required ROS installed, else use https://www.lfd.uci.edu/~gohlke/code/transformations.py.html
import tf.transformations as tx

m = open3d.read_triangle_mesh('path-to-mesh.ply')

im_width = 640
im_height = 480
focal_length = 5
intrinsics = open3d.PinholeCameraIntrinsic(width=im_width, height=im_height,
  cx=im_width/2-0.5, cy=im_height/2-0.5, fx=focal_length, fy=focal_length)

T = tx.euler_matrix(np.deg2rad(-135), 0, 0)
T[1, 3] = -0.2
T[2, 3] = +0.2
extrinsics = tx.inverse_matrix(T)

class Scope:
    index = 0

def animation_cb(vis):
    ctr = vis.get_view_control()
    if Scope.index >= 0:
        print("Capture image {:05d}".format(Scope.index))
        depth = vis.capture_depth_float_buffer(False)
        image = vis.capture_screen_float_buffer(False)
    Scope.index = Scope.index + 1
    if Scope.index < 10:
        ctr.convert_from_pinhole_camera_parameters(intrinsics, extrinsics)
    else:
        vis.register_animation_callback(None)
    return False

vis = open3d.Visualizer()
vis.create_window(width=im_width, height=im_height)
vis.add_geometry(m)
vis.register_animation_callback(animation_cb)
vis.run()
vis.destroy_window()
```
The rendering looks OK:
![screenshot from 2018-05-22 11-28-03](https://user-images.githubusercontent.com/2848070/40382409-3f7dbb14-5db3-11e8-92cd-6e15878d2747.png)

However, it does not change at all when I change the `focal_length` variable. I would like to change the focal length to adjust my rendering. Am I missing something? I'm using [this](https://drive.google.com/open?id=1mi4q8u67k-azEixv8mW2KAdF4X43XbHL) mesh.

Thanks for creating this library!

**Comment by samarth-robo** [comment]
Realized that the field of view (the parameter that focal length affects) is getting clipped between some min and max values. Changing the focal length to be in the range of ~ 700 starts showing the effect on field of view. So this issue is closed.

**Comment by syncle** [comment]
Thanks @samarth-robo for sharing your experience!
