### ISSUE TITLE
Python pip install does not contain all the options

### ISSUE THREAD

**Issue by shaisegev** [IntelVCL/Open3D#369]
I use pip install to install the environment.
I can import open3d but I can't import all the rest (read_point_cloud, point_cloud...). can you please update the pip install process?
BTW, awesome work!!!

**Comment by syncle** [comment]
Thanks! I think @takanokage can give best answer for this.

**Comment by shaisegev** [comment]
Hi @takanokage, Do you know what the problem is?

**Comment by qianyizh** [comment]
Which package have you installed via pip?
I think the current correct one is:
```
pip install open3d-python
```
The open3d name however is hijacked by someone else and we are in the process trying to get it back.

**Comment by takanokage** [comment]
yep, I can confirm that there's a problem with the pip package.
I'm going to work on a fix right away.

Thanks for reporting!

**Comment by takanokage** [comment]
Are you comfortable with building from source?
This is the fastest way to get a working version out to you.

On my dev branch [issue_#130](https://github.com/takanokage/Open3D/tree/issue_%23130) this passes:
`from open3d import read_point_cloud`

In order to use this branch you need to checkout my branch, build from source and execute `make install`.

**Comment by takanokage** [comment]
I uploaded a new revision to pypi.
Please try again:

```
pip install open3d-python
python
>>> import open3d
>>> from open3d import read_point_cloud

```

**Comment by syncle** [comment]
I am not very sure but based on the provided screenshot, open3d package was compiled with 32bit machine, while python version importing this package is 64bit.

**Comment by shaisegev** [comment]
this one is for Linux
![image](https://user-images.githubusercontent.com/39540826/40464540-a5c6fa20-5ed0-11e8-8293-834d7dcb2339.png)

**Comment by takanokage** [comment]
The Windows and the Linux errors are different.

On Linux it doesn't seem to find OpenGL. Please double check that you have installed all Open3D dependencies. Heres the [install-deps-ubuntu.sh](https://raw.githubusercontent.com/takanokage/Open3D/issue_%23130/util/scripts/install-deps-ubuntu.sh) from my [branch](https://github.com/takanokage/Open3D/tree/issue_%23130).

On Windows @syncle could be right - maybe this is an x86 vs. x64 mismatch between the Python version on your system and the Python version I built for (x86). One way to check on your side is to install the x86 Python in parallel and either place it first in path or run:
`<path_to_python.exe> -m pip install open3d-python`

On my side I have installed four Python variants in parallel: x86 & x64, 2.7.12 and 3.5.2. I have built the open3d Python module for 2.7.12.x86 and 2.7.12.x64 and the output file name is identical. This makes packaging x86 and x64 variants together a little bit more tricky and may take a while.

**Comment by takanokage** [comment]
#130

**Comment by shaisegev** [comment]
Ok.
In my case I need to use the open3d on server and I can't install other things using sudo (like openGL. I can install using pip install the python version of openGL, but I have checked and it's probably not enough). 
In addition my server is Linux 64bit. Usually for other librarys I'm using pip install only.
My server is "temporary" server for testing that came empty (with OS only) for my tests, and I need to install using pip all the tools that I need for my tests.
I have workaround (I can create binary file with open3d and download the binary to the server- but then I not gonna have the latest version of open3d and it's require maintenance).
Do you have version without sudo installation requirement?

Thanks!

**Comment by takanokage** [comment]
If you're building from my branch you can install without sudo.

You need to set the CMAKE_INSTALL_PREFIX cmake option:

cmake ... 
-DCMAKE_INSTALL_PREFIX:PATH=~/open3d

This will configure the make install to copy the files to ~/open3d or any other path you choose.

**Comment by takanokage** [comment]
This issue has been addressed and should be closed.

The request for adding 64bit Python support for Windows 10 has been registered as #377.
