### ISSUE TITLE
unable to find py3d even after setting DPYTHON_EXECUTABLE

### ISSUE THREAD

**Issue by shomedas** [IntelVCL/Open3D#370]
I have installed open3d on ubuntu 16.04 using the specified method. However I am not able to import several modules as listed below:
global_registration, fast_global_registration, trajectory_io, register_fragments, optimize_posegraph, opencv_pose_estimation

Basic sanity check works fine:
import open3d

My platform ubuntu 16.04, 64bit, python 3.5

**Comment by shomedas** [comment]
>>> import open3d
>>>from global_registration import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'global_registration'

I had not installed matplotlib and opencv-python. Could that cause this kind of problem? 
I tried to use the command from install-deps-python.sh:
python3.5 -m pip install --user numpy matplotlib opencv-python. But it gave error: PermissionError: [Errno 13] Permission denied: '/home/krr/.local/lib/python3.5/site-packages/numpy'. 
Should I run above command with sudo permission?
Should I use pip3 instaed of pip? 

~/softwares/Open3D/util/pip_package/open3d/linux/readme.txt says place "linux binaries here". Do I have to copy the contents of open3d/build/lib folder to the above location?

**Comment by qianyizh** [comment]
I think your build is successful already.
You have run pass:
```
>>> import open3d
```
The next check point would be:
```
>>> x = open3d.read_point_cloud(".......some supported point cloud file")
>>> print(x)
```
Or even:
```
>>> x = open3d.PointCloud()
>>> print(x)
```

**Comment by shomedas** [comment]
How do I import py3d. Do I have to install it using  pip install py3d as given in [](https://pypi.org/project/py3d/#files)

There was no py3d.cpython-35m-x86_64-linux-gnu.so or py3d.so in my build folder. Only libs are
libjsoncpp.a, libCore.a, libtinyfiledialogs.a, libIO.a, libpng.a, libzlib.a, libVisualization.a and open3d.cpython-35m-x86_64-linux-gnu.so. This is after building with 

```
cmake ../src -DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python3.5
make -j
make install
```

**Comment by takanokage** [comment]
`make install` will install the open3d python module to the right location, no need to `pip install...`.

after that:
`import open3d`

in the past we used to do:
`import py3d`

We've just rolled out a python module name change from `py3d` to `open3d`. With the latest commits to master `import open3d`. With previous releases `import py3d`.

**Comment by shomedas** [comment]
ok. I will close the issue.

**Comment by Meijia-Zhi** [comment]
### ModuleNotFoundError: No module named 'global_registration'
anaconda3 
python3.6
conda install -c open3d-admin open3d
open3d 0.9.0

>>> from global_registration import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'global_registration'
>>> x = open3d.read_point_cloud(".......some supported point cloud file")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'open3d' is not defined
>>> import open3d
>>> x = open3d.read_point_cloud(".......some supported point cloud file")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'open3d' has no attribute 'read_point_cloud'
>>> x = open3d.io.read_point_cloud(".......some supported point cloud file")
>>> print(x)
geometry::PointCloud with 0 points.

All basic  tutorial can run as expected, but when I run the program "Global registration" in Advanced , it shows: ModuleNotFoundError: No module named 'global_registration'.

**Comment by Meijia-Zhi** [comment]
sorry about that I have changed the name "global_registration.py" , now it can run as well.
