### ISSUE TITLE
Feature request: Python Binding: Numpy2Image 

### ISSUE THREAD

**Issue by ralphybbbaer** [IntelVCL/Open3D#374]
I want to write a PointCloud-Viewer for a realsense camera in python.
What I am missing is a function for converting a numpy-array into an Image.

**Comment by qianyizh** [comment]
``Image`` can be converted from/to a numpy array.
It is explained here:
http://www.open3d.org/docs/tutorial/Basic/rgbd_images/index.html

A code example:
```
import numpy as np
import open3d
x = numpy.asarray(...)
img = open3d.Image(x)
```

The conversion supports ``uint8, uint16, or float`` with ``c_type`` storage (default numpy behavior), dim=2 (width*hight) or dim=3 (width*height*channel).

This is not obvious. @syncle  We should add it to the doc.

**Comment by maaft** [comment]
Hi,
i tried to install open3d both from source and with `pip install open3d-python` using python2.7.
Then when doing:
```
x = np.arange(12)
img = open3d.Image(x)
```
the program exits with `RuntimeError: Image can only be initialized from buffer of uint8, uint16, or float!`

Any suggestions?

**Comment by qianyizh** [comment]
Can you try:
```
x = np.arange(12).reshape(3,4).astype(np.float32)
img = open3d.Image(x)
```
By default, python's float is float64 (double). I think that is the reason.
