### ISSUE TITLE
After registration, failing to write the resulting point cloud in XYZ format in C++ demo

### ISSUE THREAD

**Issue by choyfung** [IntelVCL/Open3D#375]
Hello,

I am trying to save the registered point clouds in `.xyz`or`.pcd` format in C++ demo, but I encountered an error. I know how to achieve this by calling Python function. 

Specifically, I follow this example: `Open3D/src/Tools/ManuallyAlignPointCloud.cpp`, and I use the following codes to achieve this:
```c++
std::shared_ptr<PointCloud> source, target;

/** registration process**/

std::string source_filename = "../../build/bin/Test/source_alignment.xyz";
std::string target_filename = "../../build/bin/Test/target_alignment.xyz";
WritePointCloud(source_filename, *source);
WritePointCloud(target_filename, *target);
```
Error: 
```c++
Write XYZ failed: unable to open file: ../../build/bin/Test/source_alignment.xyz
Write XYZ failed: unable to open file: ../../build/bin/Test/target_alignment.xyz
```

Can somebody help me?

Thanks  in advance.

**Comment by syncle** [comment]
It is not very clear to me how to reproduce the issue. Are you encounter the same issue when you open a point cloud and save it as a xyz file? The target path might be not existing.

**Comment by choyfung** [comment]
@syncle Thank you for your reply.

Yes, I had checked and found that this error is actually caused by the wrong path.

I had changed as follows and they are working:

```
std::string source_filename = "./source_alignment.xyz";
std::string target_filename = "./target_alignment.xyz";
```
Both `source_alignment.xyz` and `target_alignment.xyz` will be generated in which the corresponding executable file located. 

Thank you @syncle

**Comment by syncle** [comment]
Awesome! Closing this issue.

**Comment by ebrahim31** [comment]
Hi, 
I am having the same issue, while I am generating a synthetic XYZ file. When want to save the generated pcd, it gives me a similar error "Write XYZ failed: unable to open file".

**Comment by ebrahim31** [comment]
> Hi,
> I am having the same issue, while I am generating a synthetic XYZ file. When want to save the generated pcd, it gives me a similar error "Write XYZ failed: unable to open file".

____________________________________________________________________

I have figured the problem, I was giving the full path to the "write_point_cloud", however, it only needs the file name, like "FILENAME.xyz", therefore it can save it in the same directory that the executable file resides.
