### ISSUE TITLE
is there any way to visualize a PCD on jupyter 

### ISSUE THREAD

**Issue by adioshun** [IntelVCL/Open3D#376]
Thanks for your works. 

It is so great and easy to use. 

The visualization function `draw_geometries` is good to see the result. 

However, I use a jupyter as an IDE tool. 

Is there any way to see the result directly on the jupyter web-page using the `draw_geometries`. 

Or could you recommend other ways?

Thanks again.

**Comment by amiltonwong** [comment]
Hi, @adioshun ,

I could execute the cell in jupyter notebook, on using draw_geometries(). The geometric output is displayed  at the prompted window. I don't think the embedded way is feasible, as it deals with the manipulation of the view in 3D.

**Comment by syncle** [comment]
As a note, I found very interesting open source project https://github.com/daavoo/pyntcloud that visualizes geometry in Jupiter notebook using iframe. This is very close to what @adioshun asked.

**Comment by adioshun** [comment]
@syncle I aware the pyntcould. it's visualization function is so great. But, as I know, it support only PLY file. Does it support PCD file?

**Comment by adioshun** [comment]
@amiltonwong  I am looking for a way to display it on Jupyter webpage for result screen sharing with my friends. thanks anyway.

**Comment by syncle** [comment]
@adioshun I don't think so. I haven't tried, but doc says it supports various format. https://github.com/daavoo/pyntcloud/blob/master/docs/io.rst

**Comment by adioshun** [comment]
@themmes Thamk you for ur comment. I tried pyntcloud. However it doesnot work. Maybe i ca n change the pcd to np or dataframe and try again.

**Comment by d-diaz** [comment]
@adioshun, I've found the plotly library to offer simple and attractive interactive 3d visualizations within Jupyter Notebooks for point clouds, meshes, etc. Here are some [examples] (https://plot.ly/python/line-and-scatter/) from the plotly docs. Scroll to the bottom to see the use of plotly's scattergl to handle a 3d scatterplot with LOTS of points.
