### ISSUE TITLE
Hessian matrix seems wrong in fast global registration

### ISSUE THREAD

**Issue by longchao343** [IntelVCL/Open3D#380]
Hi,should hessian matrix be [[I ,-q^],[-q^,q^*q^]] when we do optimization?Bcz according to bch formula jacobian should be [I,-q^].

**Comment by syncle** [comment]
Can you share more specific explanation? Actually, Jacobian matrix used for FGR is [q_x|-I]. FYI,

https://github.com/IntelVCL/Open3D/blob/2323d4615637d202c442d6277cbfbb8b6018cfef/src/Core/Registration/FastGlobalRegistration.cpp#L282-L308

**Comment by longchao343** [comment]
You are right, [I,-q^] and [q^,I ] are both right in jacobian. I have expanded the code here, and found that hessian here is [[-q^*q^, q^],[-q^,I]] . Shoud it be [[q^*q^, -q^],[-q^,I]] ? And I also found the transformation update,`aff_mat.linear() = (Eigen::Matrix3d) Eigen::AngleAxisd(result(2), Eigen::Vector3d::UnitZ())
            * Eigen::AngleAxisd(result(1), Eigen::Vector3d::UnitY())
            * Eigen::AngleAxisd(result(0), Eigen::Vector3d::UnitX());` here we convert rotation vector into rotation matrix,but the results is different from ceres' angleaxis to `rotation,auto rotationVecToMatrix=[](Eigen::Vector3d& r_v,Eigen::Matrix3d& R)
        {
            static const double kOne = 1.;
            const double theta2 = r_v.dot(r_v);
            if (theta2 > double(std::numeric_limits<double>::epsilon())) {
                // We want to be careful to only evaluate the square root if the
                // norm of the angle_axis vector is greater than zero. Otherwise
                // we get a division by zero.
                const double theta = sqrt(theta2);
                const double wx = r_v[0] / theta;
                const double wy = r_v[1] / theta;
                const double wz = r_v[2] / theta;

                const double costheta = cos(theta);
                const double sintheta = sin(theta);

                R(0, 0) =     costheta   + wx*wx*(kOne -    costheta);
                R(1, 0) =  wz*sintheta   + wx*wy*(kOne -    costheta);
                R(2, 0) = -wy*sintheta   + wx*wz*(kOne -    costheta);
                R(0, 1) =  wx*wy*(kOne - costheta)     - wz*sintheta;
                R(1, 1) =     costheta   + wy*wy*(kOne -    costheta);
                R(2, 1) =  wx*sintheta   + wy*wz*(kOne -    costheta);
                R(0, 2) =  wy*sintheta   + wx*wz*(kOne -    costheta);
                R(1, 2) = -wx*sintheta   + wy*wz*(kOne -    costheta);
                R(2, 2) =     costheta   + wz*wz*(kOne -    costheta);
            } else {
                // Near zero, we switch to using the first order Taylor expansion.
                R(0, 0) =  kOne;
                R(1, 0) =  r_v[2];
                R(2, 0) = -r_v[1];
                R(0, 1) = -r_v[2];
                R(1, 1) =  kOne;
                R(2, 1) =  r_v[0];
                R(0, 2) =  r_v[1];
                R(1, 2) = -r_v[0];
                R(2, 2) = kOne;
            }
        };.`

**Comment by syncle** [comment]
Oh, now I understand in which point we are not using the same language. q is not quaternion in the referred code snippet. q is xyz coordinate. The Jacobian formulation is based on linear approximate form of rotation matrix. Please refer Eq (7) in http://vladlen.info/papers/fast-global-registration.pdf.

**Comment by longchao343** [comment]
Well, I know q is xyz coordinate,I mean q^ is a antisymmetric matrix which is [[0 -qz qy ],[qz 0 -qx ],[-qy qx 0]]. And I think in the update step , we need to convert rotation vector into rotation matrix, I have test the conversion step of FGR and  compare the results with ceres solver's conversion api. The results are different.

**Comment by syncle** [comment]
> found that hessian here is [[-q^*q^, q^],[-q^,I]] . Shoud it be [[q^*q^, -q^],[-q^,I]] ?

Oh, there is a mistake in my previous answer. J = [q^|-I], q^T = -q^. Therefore, JTJ = [-q^q^, q^| -q^, I]

> rotationVecToMatrix is just a copy of ceres:: AngleAxisToRotationMatrix which is used to convert rotation vector into rotation matrix.

I looked the definition of ``ceres:: AngleAxisToRotationMatrix``. It is basically scaled quaternion. Please see https://github.com/ceres-solver/ceres-solver/blob/e69bd2a206118c0262185baba7a6e710decbcb28/include/ceres/rotation.h#L360-L368 to check how the rotation matrix is transformed into angle axis vector. In FGR implementation, q is not the quaternion.

**Comment by longchao343** [comment]
You are right. Thanks
