### ISSUE TITLE
Utilizing FPFH & Global Feature

### ISSUE THREAD

**Issue by bored-wolf** [IntelVCL/Open3D#383]
While using the compute FPFH features function, the computed feature vector has all zeros for each point, even after following the format of the documentation. Is there anything I might be doing wrong?

**Comment by syncle** [comment]
I think there are two reasons:
- Please check your radius size used for feature description is correct. If the radius size is too small, it become identical to making a descriptor of an isolated point. A good example to visualize your radius size is http://open3d.org/docs/tutorial/Basic/kdtree.html
- Please make sure you have pre-computed vertex normal. Normal estimation is essential for feature description, as it determines canonical orientation. If the point has no orientation, feature descriptor can output void features.

**Comment by bored-wolf** [comment]
Ah thank you that worked :D Another query being, is there any option to extract global feature descriptors using open3D?

**Comment by syncle** [comment]
Currently Open3D has FPFH only. Do you want to have some recommendations for global features?

**Comment by bored-wolf** [comment]
That would be great, I was wondering if any python implementation for any of them was available.

**Comment by syncle** [comment]
@bored-wolf: let me close the issue for now. We can comeback this issue once there is a specific request and plan for the global feature.

**Comment by guy4261** [comment]
> Please make sure you have pre-computed vertex normal. Normal estimation is essential for feature description, as it determines canonical orientation. If the point has no orientation, feature descriptor can output void features.

I got all zeroes then came to this comment two. Perhaps this warning could be added programmatically? Or even an explicit exception in case the normals have not been computed yet?

**Comment by griegler** [comment]
There should already be a warning if the `PointCloud` has no normals, i.e., `pcd.HasNormals()` returns `false`. However, there is no exception thrown, and random features are returned.

**Comment by robertoruizmu** [comment]
> I think there are two reasons:
> 
> * Please check your radius size used for feature description is correct. If the radius size is too small, it become identical to making a descriptor of an isolated point. A good example to visualize your radius size is http://open3d.org/docs/tutorial/Basic/kdtree.html
@syncle Page not found , where can I find it ?
