### ISSUE TITLE
Export PCD list in one PCD

### ISSUE THREAD

**Issue by baptiste-mnh** [IntelVCL/Open3D#386]
Hi, I'm working on the [multiway registration exemple](http://www.open3d.org/docs/tutorial/Advanced/multiway_registration.html) and I'm searching a way to export the final rendering.
```
print("Transform points and display")
    for point_id in range(n_pcds):
        print(pose_graph.nodes[point_id].pose)
        pcds[point_id].transform(pose_graph.nodes[point_id].pose)
    draw_geometries(pcds)
    # EXPORT RENDERING HERE
```
Thanks!

**Comment by syncle** [comment]
I recommend using custom visualizer:
```
    vis = Visualizer()
    vis.create_window()
    for i in range(len(pcds)):
        vis.add_geometry(pcds[i])
    vis.run()
    vis.capture_screen_image('test.png')
    vis.destroy_window()
```
This is from http://open3d.org/docs/tutorial/Advanced/customized_visualization.html

**Comment by baptiste-mnh** [comment]
I actually search a way to export the registered pcds in one complete pcd

**Comment by syncle** [comment]
Now I see the point. How about using ``+`` operator of ``Geometry`` class? 
For example:
```
    print(pcd)
    pcds = [pcd, pcd, pcd]
    pcd_combined = PointCloud()
    for i in range(len(pcds)):
        pcd_combined += pcd
    print(pcd_combined)
    write_point_cloud('test.ply', pcd)
    write_point_cloud('test_combined.ply', pcd_combined)
```
This will make ``pcd_combined`` with 3x more points 
```
PointCloud with 196133 points.
PointCloud with 588399 points.
```

**Comment by serdadoe** [comment]
Hi @syncle , this question maybe out of topic with this Issue.
I tried `write_point_cloud` to save to PCD file, but what I got is pcd file in binary data. While the common pcd file is in ascii format. (When I open binary data PCD in notepad, I got some symbols not the xyz coordinate)
How to save the pcd in ascii format?

**Comment by rukie** [comment]
Thanks for the question and solution! I've noticed significant speed boosts by writing/saving in binary ply formats over ASCII xyz/xyzrgb formats. File I/O appears to be faster. 

Also, In your example, I think you missed an [i]
pcd_combined += **pcd[i]**

**Comment by syncle** [comment]
Yes. The corrected one is
```
    pcds = [pcd, pcd, pcd]
    pcd_combined = PointCloud()
    for i in range(len(pcds)):
        pcd_combined += pcds[i]
    print(pcd_combined)
    write_point_cloud('test.ply', pcd)
    write_point_cloud('test_combined.ply', pcd_combined)
```
I am also preparing some updates in the multiway registration tutorial (http://open3d.org/docs/tutorial/Advanced/multiway_registration.html) using this idea.
