### ISSUE TITLE
Allow configuration of view parameters from python

### ISSUE THREAD

**Issue by adamlofts** [IntelVCL/Open3D#387]
I would like to directly set the view parameters rather than call rotate(), translate() ...

From C++ it looks like I can use this function:

https://github.com/IntelVCL/Open3D/blob/995b646375121e348ff814b138a924bfac0f047e/src/Visualization/Visualizer/ViewControl.cpp#L96

Can you add this call to python?

**Comment by syncle** [comment]
Thanks for the request, but I am occupied by some other issues. I will handle this issue soon.

**Comment by syncle** [comment]
@adamlofts: I am working on this.

### Saving viewpoint
Actually direct saving/loading view point is done by using ``pinhole_camera_trajectory``. For example:
```
    vis = Visualizer()
    vis.create_window()
    ctr = vis.get_view_control()
    pcd = read_point_cloud("../../TestData/fragment.pcd")
    vis.add_geometry(pcd)
    vis.run() # user changes the view and press "q" to terminate
    param = ctr.convert_to_pinhole_camera_parameters()
    trajectory = PinholeCameraTrajectory()
    trajectory.intrinsic = param[0]
    trajectory.extrinsic = Matrix4dVector([param[1]])
    write_pinhole_camera_trajectory("test.json", trajectory)
    vis.destroy_window()
```
will save ``test.json`` that has single camera pose in camera trajectory format.

### Loading viewpoint
```
    vis = Visualizer()
    vis.create_window()
    ctr = vis.get_view_control()
    pcd = read_point_cloud("../../TestData/fragment.pcd")
    trajectory = read_pinhole_camera_trajectory("test.json")
    vis.add_geometry(pcd)
    ctr.convert_from_pinhole_camera_parameters(
            trajectory.intrinsic, trajectory.extrinsic[0])
    vis.run()
    vis.destroy_window()
```
will read ``test.json`` and display the same view.


However, as @adamlofts indirectly pointed out, directly working with ``pinhole_camera_paramters`` is non-trivial as there is no I/O for pinhole_camera_paramters. 

@qianyizh: do you hide I/O functions for ``PinholeCameraParameters`` intentionally, or it is not exposed?

**Comment by qianyizh** [comment]
It is a ``IJsonConvertible``, so the IO should be exposed by default?

**Comment by qianyizh** [comment]
I think we have changed it to ``PinholeCameraIntrinsic`` in a previous version? And it is exposed in python interface.

**Comment by songanz** [comment]
Follow @syncle code mentioned before, I have the `AttributeError: 'open3d.open3d.camera.PinholeCameraTrajectory' object has no attribute 'intrinsic'` error. Is there anything I am doing wrong?

**Comment by sasa2124** [comment]
Hello everyone, I would like to capture depth image from 3d point and I want to save viewpoint from different views however I got some problem with respect to PinholeCameraTrajectory. Here is my code

from open3d import *
import numpy
import transforms3d
from scipy.spatial.transform import *
import matplotlib.pyplot as plt

pcd = open3d.io.read_point_cloud("scene0173.xyz")

vis = Visualizer()
vis.create_window()
ctr = vis.get_view_control()
vis.add_geometry(pcd)
vis.run() # user changes the view and press "q" to terminate
param = ctr.convert_to_pinhole_camera_parameters()
trajectory = open3d.camera.PinholeCameraTrajectory()
trajectory.intrinsic = param[0]

TypeError: 'open3d.open3d.camera.PinholeCameraParameters' object does not support indexing

Please help me with this problem

**Comment by rFalque** [comment]
> trajectory = read_pinhole_camera_trajectory("test.json")

just an update on the window creation to avoid the errors "ConvertFromPinholeCameraParameters() failed because window height and width do not match."

```
vis = o3d.visualization.Visualizer()
trajectory = o3d.io.read_pinhole_camera_trajectory("file.json")
vis.create_window(width=trajectory.parameters[0].intrinsic.width, height=trajectory.parameters[0].intrinsic.height)
ctr = vis.get_view_control()

vis.add_geometry(pcd)

ctr.convert_from_pinhole_camera_parameters(trajectory.parameters[0])
vis.run()
vis.destroy_window()
```
