### ISSUE TITLE
How to do linear and convex optimization in python using cvxpy module?

### ISSUE THREAD

**Issue by Mohammadnia66** [IntelVCL/Open3D#392]
I have a matrix A which is m-by-n where m = 3606 and n = 32768.

And vector b where b is n-by-1 so is 32768 elements long.

My objective function is the summation of the elements of (A*b):

So Maximize(summation(Abi)).

Subject to : Summation(bi) = 1 and Ab >= k (where k  can be 0, 1000, 2000, ...) till it becomes infeasible.

I do it but unfortunately I receive a vector with all the same values that is (1/32768).

But I want a vector that most of its elements be zero.

Anyone can help?

**Comment by syncle** [comment]
Hi @Mohammadnia66. Could you elaborate how this issue is related to Open3D?
