### ISSUE TITLE
improve make install/uninstall and find_package(Open3D) to handle building dependencies from source

### ISSUE THREAD

**Issue by takanokage** [IntelVCL/Open3D#393]
When the dependencies are not installed and have to be built from source features like make install/uninstall and find_package(Open3D) don't work.

Some of the issues encountered so far and other things that need to be done:

1. GLFW_LIBRARIES is set to glfw but the output of the build GLFW is actually glfw3. Somehow this works fine when building Open3D but when building a custom C++ project only based on installed Open3D libs & headers (and dependencies) the linker fails to find the lib. Setting the GLFW_LIBRARIES to glfw3 breaks the build of Open3D. Setting the Open3D_LIBRARIES to "...; glfw3;..." still doesn't work as the custom build project expects more libraries (dependencies of GLFW). I tested this on Ubuntu after uninstalling libglfw3 and libglfw3-dev.

```
[100%] Linking CXX executable TestVisualizer
/usr/bin/ld: /home/dpetre/open3d_install/lib/libglfw3.a(vulkan.c.o): undefined reference to symbol 'dlclose@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libdl.so.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
CMakeFiles/TestVisualizer.dir/build.make:94: recipe for target 'TestVisualizer' failed
make[2]: *** [TestVisualizer] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/TestVisualizer.dir/all' failed
make[1]: *** [CMakeFiles/TestVisualizer.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

2. set(GLFW_INSTALL ON) breaks the make uninstall
CMake Error at cmake_uninstall.cmake:3 (message):
  Cannot find install manifest:
  "/home/dpetre/open3d/issue_130/build/External/GLFW/install_manifest.txt"

```
External/GLFW/CMakeFiles/uninstall.dir/build.make:57: recipe for target 'External/GLFW/CMakeFiles/uninstall' failed
make[3]: *** [External/GLFW/CMakeFiles/uninstall] Error 1
CMakeFiles/Makefile2:226: recipe for target 'External/GLFW/CMakeFiles/uninstall.dir/all' failed
make[2]: *** [External/GLFW/CMakeFiles/uninstall.dir/all] Error 2
CMakeFiles/Makefile2:233: recipe for target 'External/GLFW/CMakeFiles/uninstall.dir/rule' failed
make[1]: *** [External/GLFW/CMakeFiles/uninstall.dir/rule] Error 2
Makefile:188: recipe for target 'uninstall' failed
make: *** [uninstall] Error 2
```

3. need to update src/External/CMakeLists.txt to set the EXTERNAL_LIBRARIES based on the build options.
4. need to update src/Open3DConfig.cmake.in to set the Open3D_LIBRARIES to include EXTERNAL_LIBRARIES.

**Comment by takanokage** [comment]
#381

**Comment by qianyizh** [comment]
Yeah. The make install on Windows and OSX is broken. I am working on fixing them.

**Comment by syncle** [comment]
@takanokage @qianyizh @yxlao: I think this issue had been addressed in v0.3, right? Should we close the issue?

**Comment by yxlao** [comment]
@syncle Yes, i recommend closing this issue. 

For future reference, we added an example cmake in `docs\_static\C++`, and test on CI for both [windows](https://github.com/IntelVCL/Open3D/blob/master/.appveyor.yml#L58) and [ubuntu and mac](https://github.com/IntelVCL/Open3D/blob/master/.travis.yml#L161). Users may refer to [this example cmake](https://github.com/IntelVCL/Open3D/blob/master/docs/_static/C%2B%2B/CMakeLists.txt).

**Comment by syncle** [comment]
Good. Thanks!
