### ISSUE TITLE
install-deps-ubuntu.sh problem (Note, selecting 'libpng12-dev' instead of 'libpng-dev')

### ISSUE THREAD

**Issue by adioshun** [IntelVCL/Open3D#395]
HI. all 

As I remember, I had no problem for Open3D installation few days ago. 

Suddenly, I got follow message. 

```
root@6761b07d3570:~/Open3D# util/scripts/install-deps-ubuntu.sh 

apt-get install \
		xorg-dev \
		libglu1-mesa-dev \
		libgl1-mesa-glx \
		libglew-dev \
		libglfw3-dev \
		libjsoncpp-dev \
		libeigen3-dev \
		libpng-dev \
		libpng16-dev \
		libjpeg-dev \
		pybind11-dev \
		python-dev \
		python3-dev \
		python-tk \
		python3-tk
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'libpng12-dev' instead of 'libpng-dev'
E: Unable to locate package pybind11-dev
root@6761b07d3570:~/Open3D# 

```

When I change the   'libpng-dev' to 'libpng12-dev', I got following error

```
Reading state information... Done
E: Unable to locate package pybind11-dev

```

I used the pure ubuntu16 images(with docker) 

Do you have any idea? 

thanks

**Comment by nrj127** [comment]
You should do ccmake ../src/ from your build directory and switch on the the option for build png from source. For pybind I built the library from source (https://github.com/pybind/pybind11) and then it worked for me.

**Comment by adioshun** [comment]
Thanks. I found that the open3d support pypi. Pip install open3d-python.

**Comment by takanokage** [comment]
Just an end note: different Ubuntu versions support different PNG releases. At this time the `install-deps-ubuntu.sh` script is not checking for the Ubuntu version. Please update the script to fit your particular needs.
Also, I've noticed that various applications may require different PNG versions on the same machine. In that case there will be a conflict; as recommended above building PNG from source would usually circumvent this issue.

**Comment by adioshun** [comment]
@takanokage  thanks. This is what I've done. 

```
sudo apt-get install -y libpng16-tools # libpng16-dev #libpng-dev
sudo apt-get install -y libglu1-mesa-dev libgl1-mesa-glx libglew-dev libglfw3-dev libjsoncpp-dev libeigen3-dev libjpeg-dev python-dev python3-dev python-tk python3-tk

sudo apt-get install -y python3-pip
pip3 install open3d-python

#sudo apt-get install pybind11-dev # ~/Open3D/src/External/pybind11/build
#sudo apt-get install xorg-dev 
```

**Comment by mtaki91** [comment]
Just for your reference, I have installed by the following procedure. (Ubuntu 16.04LTS, Python2)

```
$ git clone https://github.com/IntelVCL/Open3D
$ cd Open3D/util/scripts/
```
Remove pybind11-dev, libpng, and libpng16-dev from install-deps-ubuntu.sh.
```
$ sudo pip install pybind11
$ ./install-deps-ubuntu.sh
$ cd ../../
$ sudo pip install pybind11
$ mkdir build
$ cd build
$ cmake -DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python -DBUILD_PNG=YES ../src
$ make -j
$ sudo make install
```

**Comment by takanokage** [comment]
@adioshun I've never used `libpng16-tools`. In the Dockerfile I ended up using `libpng-dev`, it appeared at that time that any other options don't work.

At the same time I noticed that you're installing `open3d-python` with pip. That particular package was built for Ubuntu 16.04, I can't claim it's going to work on Ubuntu 18.04. You might have to build open3d from source.
