### ISSUE TITLE
[Simple Question] What is a py3d? is that a Open3D?

### ISSUE THREAD

**Issue by adioshun** [IntelVCL/Open3D#398]
In some threads, I saw the import command "import py3d"

What is the `py3d`? is that a Open3D's previous name of core module?

Thanks in advanced.

**Comment by qianyizh** [comment]
Yes, it is Open3D's previous python module name.
Simply replace it with ``open3d``, everything else should works the same.

**Comment by adioshun** [comment]
@qianyizh thank you.
