### ISSUE TITLE
Fix Xcode build.

### ISSUE THREAD

**Issue by takanokage** [IntelVCL/Open3D#401]
There seems to be a CMake bug manifested when using object libraries together with Xcode.
The solution might not be as simple as not using object libraries because this is the mechanism that I was hoping to use to fix #393.

[supporting link1](https://cmake.org/pipermail/cmake/2016-April/063169.html)
[supporting link2](https://cmake.org/Bug/view.php?id=14768)
[supporting link3](https://github.com/tensorflow/tensorflow/issues/15369)
[supporting link4](https://gitlab.kitware.com/cmake/cmake/issues/17500)

**Comment by takanokage** [comment]
mentioned in #397

**Comment by qianyizh** [comment]
This is very bad. I will take over the ownership.
