### ISSUE TITLE
depth image from pointcloud

### ISSUE THREAD

**Issue by hironoriyh** [IntelVCL/Open3D#402]
Hi! Is there a method to make a depth image from pointcloud or mesh? I'd like to make multiple depth images from different views.

**Comment by syncle** [comment]
Yes. This is a tutorial for your need. http://open3d.org/docs/tutorial/Advanced/customized_visualization.html#capture-images-in-a-customized-animation

**Comment by hironoriyh** [comment]
That's exactly what I needed. Thanks!
