### ISSUE TITLE
Crop point cloud

### ISSUE THREAD

**Issue by oarriaga** [IntelVCL/Open3D#404]
In the documentation website it says:

`read_selection_polygon_volume` reads a json file that specifies polygon selection area.
`vol = read_selection_polygon_volume("../../TestData/Crop/cropped.json")`

But the contents of the json file are never specified. How does the json file should look like?

**Comment by adioshun** [comment]
I also looking for a pointcloud cropping method. 

I found this :`https://github.com/IntelVCL/Open3D/blob/master/src/Test/TestData/Crop/cropped.json`

```
{
	"axis_max" : 4.022921085357666,
	"axis_min" : -0.76341366767883301,
	"bounding_polygon" : 
	[
		[ 2.6509309513852526, 0.0, 1.6834473132326844 ],
		[ 2.5786428246917148, 0.0, 1.6892074266735244 ],
		[ 2.4625790337552154, 0.0, 1.6665777078297999 ],
		[ 2.2228544982251655, 0.0, 1.6168160446813649 ],
		[ 2.166993206001413, 0.0, 1.6115495157201662 ],
		[ 2.1167895865303286, 0.0, 1.6257706054969348 ],
		[ 2.0634657721747383, 0.0, 1.623021658624539 ],
		[ 2.0568612343437236, 0.0, 1.5853892911207643 ],
		[ 2.1605399001237027, 0.0, 0.96228993255083017 ],
		[ 2.1956669387205228, 0.0, 0.95572746049785073 ],
		[ 2.2191318790575583, 0.0, 0.88734449982108754 ],
		[ 2.2484881847925919, 0.0, 0.87042807267013633 ],
		[ 2.6891234157295827, 0.0, 0.94140677988967603 ],
		[ 2.7328692490470647, 0.0, 0.98775740674840251 ],
		[ 2.7129337547575547, 0.0, 1.0398850034649203 ],
		[ 2.7592174072415405, 0.0, 1.0692940558509485 ],
		[ 2.7689216419453428, 0.0, 1.0953914441371593 ],
		[ 2.6851455625455669, 0.0, 1.6307334122162018 ],
		[ 2.6714776099981239, 0.0, 1.675524657088997 ],
		[ 2.6579576128816544, 0.0, 1.6819127849749496 ]
	],
	"class_name" : "SelectionPolygonVolume",
	"orthogonal_axis" : "Y",
	"version_major" : 1,
	"version_minor" : 0
}
```
However, It looks for the `polygon` format. Did you found a way for the point cloud data?

**Comment by qianyizh** [comment]
Yes. This is the polygon format. You can create one from a GUI: bin/ManuallyCropPointCloud

**Comment by SreenivasVRao** [comment]
Sorry, but where is file located? I installed Open3D with conda+pip but I can't find this binary.


Also, when I use `draw_geometries_with_editing` and crop the cloud, the `json` file has a null polygon.

> {
> 	"axis_max" : 0,
> 	"axis_min" : 0,
> 	"bounding_polygon" : null,
> 	"class_name" : "SelectionPolygonVolume",
> 	"orthogonal_axis" : "",
> 	"version_major" : 1,
> 	"version_minor" : 0
> }
>

**Comment by kimwubin** [comment]
@SreenivasVRao The viewer must be aligned to an orthogonal_axis (by pressing x, y or z). This prevents the null values in the json. It would be nice to have this printed in the help.

**Comment by noscript** [comment]
Any idea how to do the invert crop, e.g. remove points inside a volume?

**Comment by rginjapan** [comment]
@noahstier @IvanCobotic 
After you get the crop point cloud, you can use [Point Cloud Distance](http://www.open3d.org/docs/latest/tutorial/Basic/pointcloud.html) to invert the crop as you want.

**Comment by solarjoe** [comment]
@rginjapan 
How would you use the Point Cloud Distance for that?
One solution I came across is https://stackoverflow.com/a/72290128/7919597
You can get the indices of the inliners and remove them.
Other ideas?
