### ISSUE TITLE
point-to-plane ICP registration

### ISSUE THREAD

**Issue by daegeumer** [IntelVCL/Open3D#411]
Some dataset(for example Microsoft 7-scenes dataset) doesn't perform any ICP iteration using point-to-plane option. Strangely, point-to-point option works well for the same data set and the tutorial dataset also works well using point-to-plane option. I don't understand what is the problem. When the ICP algorithm doesn't converge, the result transformation of point-to-plane algorithm is always the Identity regardless of option(threshold, trans_init, relative_fitness and so on). Microsoft 7-scenes dataset consists of two png files - depth.png and rgb.png. I tried to combine two pngs to rgbd image like tutorial and I also tried to use only depth png.
I installed open3d from source a few weeks ago in Ubuntu 16.04

**Comment by syncle** [comment]
HI @daegeumer. Can you check you had computed point cloud normal before applying point to plane ICP?

**Comment by qianyizh** [comment]
@syncle we have seen similar questions recently. Maybe we should add a warning to point-to-plane ICP when there is no normal attach. (The current behavior is to fail quietly?)

Also, I think I am seeing more and more use cases directly using depth images as input, maybe we should support normal computation / bilateral filtering / sampling directly for depth images too.

**Comment by syncle** [comment]
Good point. I would need to follow-up with @daegeumer, if it is occurred by such problem. Regarding the depth image processing, let's open a new issue.

**Comment by rukie** [comment]
Personal experience: Orienting normals towards camera location significantly improves normals results (after estimating), thus improving point-to-plane registration. I typically review normals in Meshlab, as it easily lets you scale the size of normals for visualization.

**Comment by qianyizh** [comment]
FYI, you can review normals in Open3D visualizer too.
Just press ``N`` and the normals will be shown. The length of the normals can be changed with ``[`` and ``]``.

**Comment by syncle** [comment]
Hi @daegeumer, can you confirm the answers helped to resolve the issue?

**Comment by daegeumer** [comment]
oh, I'm sorry. Do I have to close the issue? Thank you for your comments. These comments help me to solve the problem. I'll close the issue right now. Thanks!

**Comment by syncle** [comment]
No you don't have to. (I sometimes close inactive threads to focus on opening issues). I just wanted to ask whether the issue is resolved.

**Comment by daegeumer** [comment]
Ok! Thank you for your concern!👍
