### ISSUE TITLE
Drawing 3D bounding box

### ISSUE THREAD

**Issue by oarriaga** [IntelVCL/Open3D#413]
Is there are form to draw a 3 bounding box given the coordinates of the corners?

**Comment by syncle** [comment]
Yes. Consider using geometric primitives. http://open3d.org/docs/tutorial/Basic/visualization.html#geometry-primitives You may generate several thin cylinders to draw a bounding box.

**Comment by haoliangjiang** [comment]
Is there any updates on this? Lineset gives better visualization in some sense...
