### ISSUE TITLE
Is it possible to create a point cloud with a numpy array?

### ISSUE THREAD

**Issue by SreenivasVRao** [IntelVCL/Open3D#416]
I see read_point_cloud() and write_point_cloud(), but no way to actually create a point cloud... 

Thanks.

**Comment by syncle** [comment]
Please also read this tutorial: http://open3d.org/docs/tutorial/Basic/working_with_numpy.html
This tutorial generates a point cloud using numpy, and transform the data as a Open3D point cloud type, and save it as a ply file.

**Comment by SreenivasVRao** [comment]
Oh great, thanks. Sorry, I didn't notice it on the docs.
