### ISSUE TITLE
[Question] creating three::Image similar to cv::Mat

### ISSUE THREAD

**Issue by TheodoreT** [IntelVCL/Open3D#417]
Hi guys,

is there any equivalent approach to the `cv::Mat` code below for the `three::Image`:

```
#define uint8 unsigned char
....
....
....
uint8* rgb = (uint8*) mxGetPr(input[0]);
int* dims = (int*) mxGetDimensions(input[0]);

int height = dims[0];
int width = dims[1];
int imsize = height * width;


cv::Mat imR(1, imsize, cv::DataType<uint8>::type, rgb);
cv::Mat imG(1, imsize, cv::DataType<uint8>::type, rgb+imsize);
cv::Mat imB(1, imsize, cv::DataType<uint8>::type, rgb+imsize + imsize);

// opencv is BGR and matlab is column-major order
cv::Mat imA[3];
imA[2] = imR.reshape(1,width).t();
imA[1] = imG.reshape(1,width).t();
imA[0] = imB.reshape(1,width).t();

// done! imf is what we want!
cv::Mat imf; 
merge(imA,3,imf);
....
....
....
```

I am trying to understand how to create a `three::Image` from the pointer data but looking in the repository couldn't quite clear find how the `three::Image` works.

As you can understand I want to create a wrapper and pass the rgb and depth images on the fly instead of saving them on the disk and reading them from there.

Thanks.

**Comment by qianyizh** [comment]
Open3D image can be converted to and from a numpy array, via:
```
img = open3d.Image(some_numpy_array)
arr = np.asarray(some_open3d_image)
```
It is direct buffer access, so it is quite fast. But it is C-major (as Open3D is written in C++). In your use case, you want to read an image and convert it to a column-major array so it can be loaded by Matlab. You can convert everything to numpy array and do it with it, something like:
```
import open3d
import numpy as np
# import matplotlib.pyplot as plt

img = open3d.read_image("...some...image...file...")
arr = np.asarray(img)

# plt.imshow(arr)
# plt.show()

arrR = arr[:, :, 0]
arrG = arr[:, :, 1]
arrB = arr[:, :, 2]

arrRt = arrR.transpose().copy()[:, :, np.newaxis]
arrGt = arrG.transpose().copy()[:, :, np.newaxis]
arrBt = arrB.transpose().copy()[:, :, np.newaxis]

arrt = np.concatenate((arrRt, arrGt, arrBt), axis=2)

# plt.imshow(arrt)
# plt.show()
```

**Comment by TheodoreT** [comment]
@qianyizh what you are suggesting is how to tranfer a `three::Image` to Matlab if I am not wrong, but what I want is the other way around. I want to send it from Matlab to a mex script which is in C++. So, I do have all my values inside an array, `uint8* rgb` but then I am not sure how to cast them to `three::Image' instead of the `cv::Mat` as I am showing in the example.

**Comment by qianyizh** [comment]
umm, if I get your question right, you want to do it in C++ right?
Then in this case, the best solution is to initialize an Open3D image object of the same size, then copy the raw data over.
The reason is that the Image object needs to take the ownership of the data so it cannot resides on a raw pointer (in that case, it is not clear who will take responsibility of releasing the memory). So Image class always assumes it has the ownership.
cv::Mat on the other hand, is a smart pointer, so can be used to wrap up data blocks.

**Comment by TheodoreT** [comment]
Yes you are right, I want it in C++. So the initialization can be done as follows:

```
// initialize image
three::Image image;
image.width_ = 1920;
image.height_ = 1080;
image.num_of_channels_ = 3;
image.bytes_per_channel_ = 8;
```

how I do the copy though? This is what I do not get. Any help here is welcome.

**Comment by TheodoreT** [comment]
Yup, this seems to do the job. Much neater than my way. However, I have the issue with the order that the data are passed as you can see the below with the channels:

![image](https://user-images.githubusercontent.com/10189018/41996806-5163b634-7a56-11e8-8cb9-394b26b50461.png)

For that reason also in opencv first they were accessing each channel individually and then merging them together. Is there a merge function from the `three::Image` class. I do not see something [here](Open3D/src/Core/Geometry/Image.h) or any other idea to address this issue.

**Comment by qianyizh** [comment]
For C++ code, you can directly manipulate ``Image::data_``, it is the raw buffer of image data, c-contiguous, row - col - channel. So you can do things just by copying bytes around.

But we have not implemented convenient functions for image processing (like those in OpenCV). The main reason is that we think this can be handled by numpy if using python binding.

**Comment by TheodoreT** [comment]
ok, I tried to create a function similar to what you have for the [CreateFloatImage()](https://github.com/IntelVCL/Open3D/blob/35be432d45bf47bbcdf920c62d7d9d446ac6d36d/src/Core/Geometry/ImageFactory.cpp#L72) as shown below:

```
 std::shared_ptr<Image> CreateRGBImageFromMat(uint8_t *mat_image, int width, int height, int channels)
{
    auto open3d_image = std::make_shared<Image>();
    open3d_image->PrepareImage(height, width, channels, sizeof(uint8_t));
//     memcpy(open3d_image->data_.data(), mat_image, open3d_image->data_.size());
    
    
    for (int i = 0; i < height * width; i++) {
        uint8_t *p = (uint8_t *)(open3d_image->data_.data() + i * channels * sizeof(uint8_t));
        *p++ = *mat_image++;
    }
    return open3d_image;
}
```

Now the result is a bit better but still I am doing something wrong as you can see:

![image](https://user-images.githubusercontent.com/10189018/42047023-74d80df0-7aff-11e8-8897-71968cb7baca.png)

I know it is something simple but knowledge to c++ and pointers is not the best.

**Comment by qianyizh** [comment]
Umm, I need to understand the data structure of mat_image.
For Open3D Image class, it is just C-type array row * col * channel.

**Comment by TheodoreT** [comment]
the raw data (coming from matlab) that I am passing to Open3D image class are similar. My impression is that the channels are in different order. I will try to examine that and I will write back.

**Comment by qianyizh** [comment]
Ah, I see. The problem is that in the following loop, it only iterates ``height*width`` and in each iteration only one byte is copied. (Should have 3 bytes copied.)
```
    for (int i = 0; i < height * width; i++) {
        uint8_t *p = (uint8_t *)(open3d_image->data_.data() + i * channels * sizeof(uint8_t));
        *p++ = *mat_image++;
    }
```

**Comment by TheodoreT** [comment]
@qianyizh that's not correct since I specify the channels variable as 3. Thus, 3*sizeof(uint8_t) should be giving me the correct number of bytes, shouldn't be?

**Comment by qianyizh** [comment]
Yes but ``*p++ = *mat_image++;`` was only executed once - hence only one byte is copied.

**Comment by TheodoreT** [comment]
ok, I see your point. The following seems to do the job:

```
std::shared_ptr<Image> CreateRGBImageFromMat(uint8_t *mat_image, int width, int height, int channels)
{
    auto open3d_image = std::make_shared<Image>();
    open3d_image->PrepareImage(height, width, channels, sizeof(uint8_t));

    for (int i = 0; i < height * width; i++) {
        uint8_t *p = (uint8_t *)(open3d_image->data_.data() + i * channels * sizeof(uint8_t));

        *p++ = *(mat_image + i);
        *p++ = *(mat_image + i + height*width);
        *p++ = *(mat_image + i + height*width*2);
    }
    return open3d_image;
}
```

I am not sure though if I can replace the for loop with `memcpy()` or `std::copy()`.

**Comment by TheodoreT** [comment]
@qianyizh I couldn't find a way to replace the above loop with `memcpy()` or `std::copy()`. Thus if you do not have any other proposal or idea whether this is possible we can close this issue ;-).

**Comment by qianyizh** [comment]
Sure. Feel free to re-open / close issues when you think it is necessary.
