### ISSUE TITLE
PYBIND11 cmake error

### ISSUE THREAD

**Issue by yoshiyama** [IntelVCL/Open3D#420]
In cmake-gui for latest src, installation of pybind11 have an error of PYBIND directory not found.
My environment is windows 10 64bit.
But for src downloaded on 5th June, it succeed completely.
What are the differences between latest and old src ?

**Comment by takanokage** [comment]
There is no difference as far as `pybind11` is concerned - `pybind11` is always built from source.
Without additional information my suggestion is to clean the project files (delete the `build` folder, delete the CMake cache) and start over.

**Comment by dotchang** [comment]
I also met same problem. Maybe, it has some problems.

And, I don't need any python interfacce for Open3D, I need only c++ libraries.
But I can't cancel python-related options. I think that it is big problem.

**Comment by dotchang** [comment]
The error is caused by 3rd line of Open3D/src/External/CMakeList.txt.
find_package(PkgConfig QUIET)
find_package(OpenGL    QUIET)
#find_package(pybind11  QUIET)

**Comment by yoshiyama** [comment]
Even after deleting the CMake cache,  the error also happens.

**Comment by takanokage** [comment]
I've just tested on my Windows 10 64bit machine, Python 2.7 32bit, CMake 3.11.0.
No trouble whatsoever. I can even disable building pybind11 and the python module.
What version of CMake are you using? Do you have any other information that might help us root cause the issue?

Thanks!

Building pybind11 from source:
```
Selecting Windows SDK version 10.0.16299.0 to target Windows 10.0.14393.
Disable unit tests since this feature is not fully supported on Windows.
Compiling on Windows
Compiling with MSVC
Using installed OpenMP 
Building EIGEN3 from source
Building GLEW from source
Building GLFW from source
Looking for pthread.h
Looking for pthread.h - not found
Found Threads: TRUE  
Could NOT find Vulkan (missing: VULKAN_LIBRARY VULKAN_INCLUDE_DIR) 
Using Win32 for window creation
Building LIBJPEG from source
Building JSONCPP from source
Building LIBPNG from source
Looking for sys/types.h
Looking for sys/types.h - found
Looking for stdint.h
Looking for stdint.h - found
Looking for stddef.h
Looking for stddef.h - found
Check size of off64_t
Check size of off64_t - failed
Building PYBIND11 from source
pybind11 v2.2.1
Building TINYFILEDIALOGS from source
Build experimental projects
Configuring done
```

Disabled building pybind11 and the python module:
```
Selecting Windows SDK version 10.0.16299.0 to target Windows 10.0.14393.
Disable unit tests since this feature is not fully supported on Windows.
Compiling on Windows
Compiling with MSVC
Using installed OpenMP 
Building EIGEN3 from source
Building GLEW from source
Building GLFW from source
Could NOT find Vulkan (missing: VULKAN_LIBRARY VULKAN_INCLUDE_DIR) 
Using Win32 for window creation
Building LIBJPEG from source
Building JSONCPP from source
Building LIBPNG from source
Building TINYFILEDIALOGS from source
Build experimental projects
Configuring done
```

**Comment by yoshiyama** [comment]
My PC is Windows 10 64bit with Python 3.5.2 32bit and CMake 3.11.4.

**Comment by qianyizh** [comment]
@yoshiyama can you try the solution in #66 ?
In short, you need to specify these:
```
cmake -DPYTHON_LIBRARY=/Users/qianyizh/anaconda/envs/py36/lib/libpython3.6m.dylib
-DPYTHON_INCLUDE_DIR=/Users/qianyizh/anaconda/envs/py36/include/python3.6m
-DPYTHON_EXECUTABLE:FILEPATH=/Users/qianyizh/anaconda/envs/py36/bin/python3.6m
../src
```

(Sorry I don't have a Windows machine at hand so I can't test it right now.) You can start with adding ``-DPYTHON_EXECUTABLE:FILEPATH``, then ``-DPYTHON_LIBRARY``, then ``-DPYTHON_INCLUDE_DIR``.

It is a known issue CMake gets confused when looking for Python executable and library and directory. On pybind11 repo they also note this https://github.com/pybind/pybind11/issues/99

**Comment by qianyizh** [comment]
@dotchang Sorry for the late reply. I am trying to fix the build system. Yeah, it has not been managed well and has some issues.

If you want to turn off Python binding, can you try to use the following switch:
```
cmake -DBUILD_PYBIND11=OFF -DBUILD_PYTHON_MODULE=OFF -DBUILD_PYTHON_TUTORIALS=OFF ../src
```

Will the error still exist? I can't duplicate the error so need your help, :)

**Comment by yoshiyama** [comment]
Thank you qianyizh.
The error is solved by specifying location of directory of python (In my case, Anaconda python).

**Comment by yxlao** [comment]
@LLDavid , please see @qianyizh 's [comment above](https://github.com/IntelVCL/Open3D/issues/420#issuecomment-404239638) . 

If you remove the build directory and start from scratch, for me it's sufficient to use specify the `PYTHON_EXECUTABLE`. First we'll need to find where the python is. 

E.g. if you're using a conda environment:
```batch
ylao@DESKTOP-CFLLFA0 C:\Users\ylao
$ activate py36

(py36) ylao@DESKTOP-CFLLFA0 C:\Users\ylao
$ where python
C:\Users\ylao\Miniconda3\envs\py36\python.exe

(py36) ylao@DESKTOP-CFLLFA0 C:\Users\ylao
$ cmake -DPYTHON_EXECUTABLE=C:\Users\ylao\Miniconda3\envs\py36\python.exe -DYOUR_OTHER_CMAKE_FLAGS ..
```

**Comment by LLDavid** [comment]
> DPYTHON_EXECUTABLE=C:\Users\ylao\Miniconda3\envs\py36\

@yxlao Thanks! Now I can get the open3d.sln, and I rebuild the 'ALL_BUILD' as the tutorial says (on VS 2015 2017). Then I try to build the 'INSTALL' and I got following one error:

> Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3073	The command "setlocal
C:\Users\Owner\Li\bin\cmake.exe -DBUILD_TYPE=Release -P cmake_install.cmake
if %errorlevel% neq 0 goto :cmEnd
:cmEnd
endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone
:cmErrorLevel
exit /b %1
:cmDone
if %errorlevel% neq 0 goto :VCEnd
:VCEnd" exited with code 1.	INSTALL	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets	138	

Any idea what I am missing?

**Comment by yxlao** [comment]
It's a little bit hard to tell from the limited information. From the error code, seems like it's similar to [this one](https://stackoverflow.com/a/31588065/1255535). One thing you could try is to specify a path that non-admin can access, as described in. Otherwise, by default, it will be installed to `C:\Program Files` which require admin access.
```
cmake -DCMAKE_INSTALL_PREFIX=\some\non\admin\path ..
```

Or, start the CMD console with Administrator rights.

**Comment by yxlao** [comment]
Currently, we're undergoing some dramatic changes for the python build system: see https://github.com/IntelVCL/Open3D/pull/604 and https://github.com/IntelVCL/Open3D/pull/618.

If you're on the lastest master (as of [this commit point](https://github.com/IntelVCL/Open3D/tree/7e5a844b146459650bbec07298dfec7b0482e246)), `make install` will not install python. In fact, in current master, you don't even need to run `make install` to get the python package working. 

Following https://github.com/IntelVCL/Open3D/pull/604, all you'll need to do is to build `install-pip-wheel`.
```
make install-pip-wheel

# If you're on windows, build the install-pip-wheel target in Visual Studio. 
# Or, at windows terminal, run
# cmake --build . --config Release --target pip-package
```

If you run into permission issue again, instead, try
```
make pip-wheel
```
And then find your wheel `*.whl` file in `build\lib\python_package\dist`, and use
```
pip install -U \path\to\wheel.whl
```

Lastly, we'd recommend using a python virtual environment (can be pip virtualenv or conda virtualenv). This will solve a lot of the permission issues.

**Comment by LLDavid** [comment]
@yxlao Now I can get it work. Really appreciate your help!
