### ISSUE TITLE
parameters used by OdometryOption()

### ISSUE THREAD

**Issue by argosvr** [IntelVCL/Open3D#424]
Can you give the details of the parameters used by OdometryOption() ?
Is their a way to increase the detection factor ? on photogrammetry softwares, we have a way to change the detector sensitivity..
Using the same rosbag, when I use a photogrammetry software (Capturing Reality) I got a good reconstruction in 3d. Using your different reconstruction methods I can't get any result usable.
We are using Intel D415 cameras.

**Comment by syncle** [comment]
Hi, here are some explanations about ``OdometryOption()  ``
- ``minimum_correspondence_ratio`` : after registration, measure the overlapping ratio of two RGBD images. If there is too few overlapping region (about 30% by default), the odometry module determine this alignment as a failure case.
- ``max_depth_diff`` : maximum allowable depth value difference for correspondence searching. For example, in depth image domain, if the two aligned depth pixels have less than specified ``max_depth_diff``, they are considered as matched correspondences. 
- ``min_depth`` and ``max_depth`` : the depth pixels having depth value of smaller than ``min_depth`` or larger than ``max_depth`` are ignored.

I am not quite sure what detection factor means, but you may try increase ``max_depth_diff``. Another advise is that can you try to visualize RGBD image as a point cloud first? If the two image domain is not correctly aligned or synchronized, RGBD odometry could fail. The useful tutorial can be found [here](http://open3d.org/docs/tutorial/Basic/rgbd_images/redwood.html).
