### ISSUE TITLE
update version before releasing a milestone

### ISSUE THREAD

**Issue by takanokage** [IntelVCL/Open3D#427]
There are several issues that need to be placed in the "process change" category.

This one is about updating the Open3D version in `src/CMakeLists.txt` before merging a milestone branch or before assigning a milestone tag. This also implies rebuilding and repackaging for pip. When we rebuild the Open3D version gets propagated throughout the code and to the `setup.py` script used to package Open3D.

Any thoughts?

**Comment by syncle** [comment]
Good point. We need to update version correctly. Can you update ``src/CMakeLists.txt`` and pip packages accordingly? I will also update the release header.

**Comment by syncle** [comment]
Addressed in #434. We don't maintain github milestone for now. The way to change software version is to modify src/version.txt. This will propagate to the packages.
