### ISSUE TITLE
Automatically update version in docs

### ISSUE THREAD

**Issue by takanokage** [IntelVCL/Open3D#428]
When we generate the project files with CMake the Open3D version in `src/CMakeLists.txt` gets updated in the C++ code and `setup.py` script used to package Open3D for pypi.

Let's update the Open3D version throughout the documentation using the same mechanism.

In summary, what I'm proposing is that we specify the Open3D version (and maybe a few other things) in one central location and have it updated throughout the project automatically. The current mechanism I've used is CMake.

**Comment by syncle** [comment]
Sounds good plan. This will relieve some manual labor. How about make a version.txt and make CMake and docs/conf.py referring it?, or docs/conf.py refers the version defined in CMake (I am not quite sure about this option yet.)
