### ISSUE TITLE
voxelgrid

### ISSUE THREAD

**Issue by nrj127** [IntelVCL/Open3D#429]
Is there a way to get the points inside a voxel. I would like to convert my point cloud into a voxel grid and do some statistical analysis on points inside every voxel.

**Comment by syncle** [comment]
Hi. Could you elaborate bit more? To answer the following question:
> Is there a way to get the points inside a voxel.

You can use voxel downsampling
http://www.open3d.org/docs/tutorial/Basic/pointcloud.html#voxel-downsampling

**Comment by qianyizh** [comment]
Umm, the python interface does not have a function for it. You need to write a C++ function to do it.
The other option is to use EstimateNormals to compute the normals directly then write a RANSAC for plane extraction.

**Comment by nrj127** [comment]
Okay, Thanks
