### ISSUE TITLE
Anaconda support

### ISSUE THREAD

**Issue by syncle** [IntelVCL/Open3D#430]
Currently we have ``pip`` distribution, but it is also necessary to distribute package via anaconda. 
Relates to #217, #408.

Useful link for conda packaging: https://conda.io/docs/user-guide/tutorials/build-pkgs-skeleton.html

**Comment by yxlao** [comment]
## Summary of behaviors
While we are adding `conda install open3d-python` support in https://github.com/IntelVCL/Open3D/pull/514. I've run some experiments to test our our current status under different enviroments and installation methods.

Enviroment setups:
- Operating systems
    - Ubuntu 16.04
    - macOS
    - Windows (not tested yet)
- Python
    - 2.7
    - 3.5
    - 3.6
- Installation method
    - Native Pip: `pip install open3d-python` in a Pip virtualenv
    - Pip in Conda: `pip install open3d-python` in a Conda virtualenv
    - Conda in Conda: `conda install open3d-python` in a Conda virtualenv (to be added)

### Ubuntu + "Native Pip"
- Ubuntu 16.04 + Python 2.7 + Native Pip: works
```
virtualenv open3d_pip_2.7 -p python2.7
source open3d_pip_2.7/bin/activate
pip install open3d-python
python -c "from open3d import *"
```
- Ubuntu 16.04 + Python 3.5 + Native Pip: works
```
virtualenv open3d_pip_3.5 -p python3.5
source open3d_pip_3.5/bin/activate
pip install open3d-python
python -c "from open3d import *"
```
- Ubuntu 16.04 + Python 3.6 + Native Pip: doesn’t work
```
virtualenv open3d_pip_3.6 -p python3.6
source open3d_pip_3.6/bin/activate
pip install open3d-python
python -c "from open3d import *"
```
```
(open3d_pip_3.6) ➜  ~ python -c "from open3d import *"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/yixing/venvs/open3d_pip_3.6/lib/python3.6/site-packages/open3d/__init__.py", line 9, in <module>
    from open3d.linux import *
  File "/home/yixing/venvs/open3d_pip_3.6/lib/python3.6/site-packages/open3d/linux/__init__.py", line 7, in <module>
    globals().update(importlib.import_module('open3d.linux.open3d').__dict__)
  File "/home/yixing/venvs/open3d_pip_3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /home/yixing/venvs/open3d_pip_3.6/lib/python3.6/site-packages/open3d/linux/open3d.so: undefined symbol: _Py_ZeroStruct
```

### Ubuntu + "Pip in Conda"
- Ubuntu 16.04 + Python 2.7 + Pip in Conda: works
```
conda create -n newenv2.7 python=2.7
source activate newenv2.7
pip install open3d-python
python -c "from open3d import *"
```
- Ubuntu 16.04 + Python 3.5 + Pip in Conda: works
```
conda create -n newenv3.5 python=3.5
source activate newenv3.5
pip install open3d-python
python -c "from open3d import *"
```
- Ubuntu 16.04 + Python 3.6 + Pip in Conda: doesn’t work
```
conda create -n newenv3.6 python=3.6
source activate newenv3.6
pip install open3d-python
python -c "from open3d import *"
```
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/yixing/miniconda3/envs/newenv3.6/lib/python3.6/site-packages/open3d/__init__.py", line 9, in <module>
    from open3d.linux import *
  File "/home/yixing/miniconda3/envs/newenv3.6/lib/python3.6/site-packages/open3d/linux/__init__.py", line 7, in <module>
    globals().update(importlib.import_module('open3d.linux.open3d').__dict__)
  File "/home/yixing/miniconda3/envs/newenv3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /home/yixing/miniconda3/envs/newenv3.6/lib/python3.6/site-packages/open3d/linux/open3d.so: undefined symbol: _Py_ZeroStruct
```

### MacOS + "Native Pip"
(Using the same commands as in Ubuntu)
- MacOS + Python 2.7 + Native Pip: works
- MacOS + Python 3.5 + Native Pip: not tested
- MacOS + Python 3.6 + Native Pip: doesn’t work
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/ylao/repo/venvs/open3d_pip_3.6/lib/python3.6/site-packages/open3d/__init__.py", line 11, in <module>
    from open3d.macos import *
  File "/Users/ylao/repo/venvs/open3d_pip_3.6/lib/python3.6/site-packages/open3d/macos/__init__.py", line 7, in <module>
    globals().update(importlib.import_module('open3d.macos.open3d').__dict__)
  File "/Users/ylao/repo/venvs/open3d_pip_3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: dlopen(/Users/ylao/repo/venvs/open3d_pip_3.6/lib/python3.6/site-packages/open3d/macos/open3d.so, 2): Symbol not found: __Py_ZeroStruct
  Referenced from: /Users/ylao/repo/venvs/open3d_pip_3.6/lib/python3.6/site-packages/open3d/macos/open3d.so
  Expected in: flat namespace
 in /Users/ylao/repo/venvs/open3d_pip_3.6/lib/python3.6/site-packages/open3d/macos/open3d.so
```

### Mac + "Pip in Conda"
(Using the same commands as in Ubuntu)
- MacOS + Python 2.7 + Pip in Conda: works
- MacOS + Python 3.5 + Pip in Conda: doesn’t work
```
(newenv3.5) ➜  ~/repo python -c "from open3d import *"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/ylao/miniconda3/envs/newenv3.5/lib/python3.5/site-packages/open3d/__init__.py", line 11, in <module>
    from open3d.macos import *
  File "/Users/ylao/miniconda3/envs/newenv3.5/lib/python3.5/site-packages/open3d/macos/__init__.py", line 7, in <module>
    globals().update(importlib.import_module('open3d.macos.open3d').__dict__)
  File "/Users/ylao/miniconda3/envs/newenv3.5/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: dlopen(/Users/ylao/miniconda3/envs/newenv3.5/lib/python3.5/site-packages/open3d/macos/open3d.so, 2): Symbol not found: __Py_ZeroStruct
  Referenced from: /Users/ylao/miniconda3/envs/newenv3.5/lib/python3.5/site-packages/open3d/macos/open3d.so
  Expected in: flat namespace
 in /Users/ylao/miniconda3/envs/newenv3.5/lib/python3.5/site-packages/open3d/macos/open3d.so
```
- MacOS + Python 3.6 + Pip in Conda: doesn’t work
```
(newenv3.6) ➜  ~/repo python -c "from open3d import *"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/ylao/miniconda3/envs/newenv3.6/lib/python3.6/site-packages/open3d/__init__.py", line 11, in <module>
    from open3d.macos import *
  File "/Users/ylao/miniconda3/envs/newenv3.6/lib/python3.6/site-packages/open3d/macos/__init__.py", line 7, in <module>
    globals().update(importlib.import_module('open3d.macos.open3d').__dict__)
  File "/Users/ylao/miniconda3/envs/newenv3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: dlopen(/Users/ylao/miniconda3/envs/newenv3.6/lib/python3.6/site-packages/open3d/macos/open3d.so, 2): Symbol not found: __Py_ZeroStruct
  Referenced from: /Users/ylao/miniconda3/envs/newenv3.6/lib/python3.6/site-packages/open3d/macos/open3d.so
  Expected in: flat namespace
 in /Users/ylao/miniconda3/envs/newenv3.6/lib/python3.6/site-packages/open3d/macos/open3d.so
```

**Comment by syncle** [comment]
That's interesting to know. Could you make a custom pip package using failing environments and test importing again? You will need to build Open3D with external libraries:
```
cmake ../src -DBUILD_EIGEN3=ON -DBUILD_GLEW=ON -DBUILD_GLFW=ON -DBUILD_JPEG=ON -DBUILD_JSONCPP=ON -DBUILD_PNG=ON -DBUILD_PYBIND11=ON -DCMAKE_INSTALL_PREFIX=~/open3d_install 
```
and need to add ``-DPYTHON_EXECUTABLE:FILEPATH=<path-to-python-executable>`` to build Open3D python package with specific python version.

**Comment by takanokage** [comment]
I propose let's keep everything tidy under just one package.
Pls don't upload multiple different versions of the same pip package. The current package already handles Python 2.7+ and 3.5+ from a single package. If it's really necessary to support each Python version specifically (though I suspect this is not the case beyond Python 2.7+ and 3.5+) this should be handled programmatically through the __init__.py files.

**Comment by yxlao** [comment]
Yeah, that would be ideal. Currently "Ubuntu 16.04 + Python 3.6 + Native Pip" option, as shown above, is not working yet. Maybe we need some fixes to the pip build process?

**Comment by takanokage** [comment]
Currently the `__init__.py` files only look at OS and Python build type (32bit and 64bit) but not at the Python version itself. Hopefully we can, in a similar way, query for the Python version in the same place - haven't tried this before so I can't say for sure.

**Comment by qianyizh** [comment]
Thanks @yxlao for doing the thorough testing. This is great!! Helps us understand the current situation a lot.

A quick question, is there an easy way to setup CI to automatically check pip with different environment / python versions? This way we don't need to manually check everything also the error message can be easily seen by everyone.

**Comment by yxlao** [comment]
Conda is now supported in the v0.3.0 release.
