### ISSUE TITLE
Add *.h into CMakeLists.txt

### ISSUE THREAD

**Issue by qianyizh** [IntelVCL/Open3D#432]
Currently only ``.cpp`` files are added to projects. For example:
https://github.com/IntelVCL/Open3D/blob/dd511a0d3f973735d15ae9b90e292077886f1e1b/src/Core/CMakeLists.txt#L2
But no ``.h`` files.

As a result, in Visual Studio, ``.h`` files are not included in projects, and search all function does not apply to ``.h`` files. We need to fix this.

**Comment by takanokage** [comment]
True, with my changes I only addressed building the projects which doesn't need to name the header files specifically, only where to find them.
I will add the headers as well.
