### ISSUE TITLE
problem re-installing open3d

### ISSUE THREAD

**Issue by argosvr** [IntelVCL/Open3D#441]
On Ubuntu after a clone and after a clean.sh, I tried to reinstall open3d.
I had to change some values on CMakeCache.txt turning some BuILD_XXX=ON but after make -j4 I get this:
Scanning dependencies of target ShaderFileTarget
Error copying directory from "/media/argos/UbuntuData/Librairies/Open3D/src/Python/Helper/" to "/media/argos/UbuntuData/Librairies/Open3D/build/lib/.".
Python/CMakeFiles/PythonHelper.dir/build.make:57: recipe for target 'PythonHelper' failed
make[2]: *** [PythonHelper] Error 1
CMakeFiles/Makefile2:1860: recipe for target 'Python/CMakeFiles/PythonHelper.dir/all' failed
make[1]: *** [Python/CMakeFiles/PythonHelper.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs...

I thought that util/scripts/install-deps-ubuntu.sh was supposed to install all dependencies ?

**Comment by qianyizh** [comment]
Can you tell me the version of Ubuntu?

**Comment by argosvr** [comment]
yes:
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.4 LTS
Release:	16.04
Codename:	xenial

**Comment by qianyizh** [comment]
Let me try to reproduce the error.

**Comment by qianyizh** [comment]
Yeah, there was a bug in ``util/scripts/install-deps-ubuntu.sh``. I am fixing it via https://github.com/IntelVCL/Open3D/pull/444

Can you try to run this from a fresh installed Ubuntu 16.04.
```
> cd ~
> sudo apt-get update
> sudo apt-get upgrade
> sudo apt-get install git cmake
> sudo apt-get install \
 		xorg-dev \
 		libglu1-mesa-dev \
 		libgl1-mesa-glx \
 		libglew-dev \
 		libglfw3-dev \
 		libjsoncpp-dev \
 		libeigen3-dev \
 		libpng-dev \
 		libjpeg-dev \
 		python-dev \
 		python3-dev \
 		python-tk \
 		python3-tk
> sudo apt-get install libpng16-dev
> cd ~/Open3D
> mkdir build
> cd build
> cmake ../src
> make -j
```

I just tried it on a virtual machine and it worked. Let me know if it works for you.

**Comment by argosvr** [comment]
Well, I'm sorry but I can't make a fresh install at the moment.
Then I tried your commands and yes it solves the problem with util/scripts/install-deps-ubuntu.sh

but with make -j I got the same problem:
make -j
Error copying directory from "/media/argos/UbuntuData/Librairies/Open3D/src/Python/Helper/" to "/media/argos/UbuntuData/Librairies/Open3D/build/lib/.".
Error copying directory from "/media/argos/UbuntuData/Librairies/Open3D/src/Python/Test/" to "/media/argos/UbuntuData/Librairies/Open3D/build/lib/./Test".
[  1%] Built target tinyfiledialogs
[  2%] Built target EncodeShader
Python/CMakeFiles/PythonHelper.dir/build.make:57: recipe for target 'PythonHelper' failed
make[2]: *** [PythonHelper] Error 1
Python/CMakeFiles/PythonTest.dir/build.make:57: recipe for target 'PythonTest' failed
make[2]: *** [PythonTest] Error 1
CMakeFiles/Makefile2:1866: recipe for target 'Python/CMakeFiles/PythonHelper.dir/all' failed
make[1]: *** [Python/CMakeFiles/PythonHelper.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:1903: recipe for target 'Python/CMakeFiles/PythonTest.dir/all' failed
make[1]: *** [Python/CMakeFiles/PythonTest.dir/all] Error 2
[ 10%] Built target zlib
[ 10%] Built target PythonTutorial
[ 20%] Built target IO
[ 38%] Built target Core
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by qianyizh** [comment]
Umm, this is weird. I have never seen this type of error before. Looks like it fails at copying directories.

Can you first double check you have the write permission to the folder, and there is enough disk space. If it still does not work, try to make a fresh clone and run cmake and make again?

**Comment by qianyizh** [comment]
Ah I see. Yeah, this looks like a bug.
Can you try to create two empty folders ``Open3D/src/Python/Test/`` and ``Open3D/src/Python/Helper/``.
See if the build can pass.

**Comment by qianyizh** [comment]
Or remove these lines:
https://github.com/IntelVCL/Open3D/blob/050e123ebb18092092009a1cdf51ec1450e20129/src/Python/CMakeLists.txt#L29-L46

I will write a PR to remove these.

**Comment by argosvr** [comment]
Ok.. it worked creating  two empty folders Open3D/src/Python/Test/ and Open3D/src/Python/Helper/.

**Comment by argosvr** [comment]
well... if mke -j is working, their is still a problem with python biding...
when I try to bind it I got this:
 cmake -DPYTHON_EXECUTABLE:FILEPATH=/usr/lib/python2.7/ ../src
CMake Deprecation Warning at CMakeLists.txt:8 (cmake_policy):
  The OLD behavior for policy CMP0054 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.


-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Open3D 0.2.0.0
-- Compiling on Unix
-- Disable RealSense since it is not fully supported on Linux.
-- Using installed OpenMP 
-- Using installed EIGEN3 3.2.92
-- Using installed GLEW 1.13.0
-- Using installed GLFW 3.1.2
-- Using installed LIBJPEG 
-- Using installed JSONCPP 1.7.2
-- Using installed LIBPNG 1.6.20
-- Building PYBIND11 from source
-- Found PythonInterp: /usr/lib/python2.7 (found version "1.4") 
CMake Error at External/pybind11/tools/FindPythonLibsNew.cmake:95 (message):
  Python config failure:

Call Stack (most recent call first):
  External/pybind11/tools/pybind11Tools.cmake:16 (find_package)
  External/pybind11/CMakeLists.txt:33 (include)


-- Configuring incomplete, errors occurred!
See also "/media/argos/UbuntuData/Open3D/build/CMakeFiles/CMakeOutput.log".

**Comment by qianyizh** [comment]
Sorry for the late reply.
You need to specify ``DPYTHON_LIBRARY`` besides ``DPYTHON_EXECUTABLE:FILEPATH``.
See this #66 

I will fix the doc.

**Comment by syncle** [comment]
Hi @argosvr @qianyizh: is the issue resolved?

**Comment by syncle** [comment]
Closed due to inactivity. @argosvr Feel free to reopen this if necessary.
