### ISSUE TITLE
Travis CI is not consistent with install script

### ISSUE THREAD

**Issue by qianyizh** [IntelVCL/Open3D#443]
The root cause is this commit.
https://github.com/IntelVCL/Open3D/commit/3b419ca35d873f60d7f84b9ec577164ad01ac012

This needs to be reverted.

**Comment by qianyizh** [comment]
This commit is broken too:
https://github.com/IntelVCL/Open3D/commit/dd0988673558cf7933abbed13dda264465907e10

It should be reverted after the previous (install dependencies).
Actually we should have multiple CIs to test different versions of Ubuntu, install from dep and build from source.

**Comment by syncle** [comment]
Addressed in #444.
