### ISSUE TITLE
Setup CI for Ubuntu 16.04 and 18.04

### ISSUE THREAD

**Issue by qianyizh** [IntelVCL/Open3D#447]
Travis CI only supports Ubuntu 14.04 for now. And there seems to be no plan in the near future. See this thread: https://github.com/travis-ci/travis-ci/issues/5821

For now, we have to manually test build systems for Ubuntu 16.04 and Ubuntu 18.04.
We should setup Jenkins CI.

**Comment by syncle** [comment]
Jenkins CI is good option in general, but I've also searched for reasonable solution and found Semaphore CI. It is Ubuntu 16.04 based, and supports very fast configuration. Each build took about 5:20 including installing dependencies. I've mimicked our Travis CI build here: https://semaphoreci.com/syncle/open3d/branches/master/builds/11
@qianyizh How do you think?

**Comment by qianyizh** [comment]
Up to you!

**Comment by syncle** [comment]
As the follow-up, @takanokage is making multiple docker environments to test Open3D with various Ubuntu platforms + naive Python installations. @takanokage: please take the ownership on this issue.

**Comment by takanokage** [comment]
Yep, I have implemented docker based build & unit tests using the following configuration parameters:
- Ubuntu 14.04/16.04/18.04
- native installation of python2/python3
- miniconda2/miniconda3
- with/without native installation of Open3D dependencies (like GLEW, GLFW, Eigen, etc.)
- STATIC vs SHARED builds

Currently I'm validating my implementation and fixing bugs. I'll release soon.

**Comment by takanokage** [comment]
We have recently released the code for running/testing Open3D under Docker for all off the afore mentioned configurations. Please checkout the [documentation](http://open3d.org/docs/tutorial/docker/docker-test.html) and the [.travis.yml ](https://github.com/IntelVCL/Open3D/blob/master/.travis.yml) example of how to run these in TravisCI.
