### ISSUE TITLE
ReconstructionSystem with fresh install on Ubuntu 16.04

### ISSUE THREAD

**Issue by argosvr** [IntelVCL/Open3D#449]
with a fresh install, I get this problem using make_fragment.py :

Fragment 000 / 003 :: RGBD matching between frame : 98 and 99
Traceback (most recent call last):
  File "make_fragments.py", line 150, in <module>
    process_fragments(args.path_dataset, args.path_intrinsic)
  File "make_fragments.py", line 133, in process_fragments
    optimize_posegraph_for_fragment(path_dataset, fragment_id)
  File "/media/argos/UbuntuData/Librairies/Open3D/src/Python/Tutorial/ReconstructionSystem/optimize_posegraph.py", line 33, in optimize_posegraph_for_fragment
    preference_loop_closure = 0.1)
  File "/media/argos/UbuntuData/Librairies/Open3D/src/Python/Tutorial/ReconstructionSystem/optimize_posegraph.py", line 20, in run_posegraph_optimization
    reference_node = 0)
TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. open3d.GlobalOptimizationOption()
    2. open3d.GlobalOptimizationOption(arg0: open3d.GlobalOptimizationOption)
    3. open3d.GlobalOptimizationOption(max_correspondence_distance: float=0.03, edge_prune_threshold: float=0.25, reference_node: int=-1L)

Invoked with: kwargs: reference_node=0, edge_prune_threshold=0.25, max_correspondence_distance=0.07, preference_loop_closure=0.1

**Comment by qianyiforma** [comment]
I saw your post, 😄 
I think you are using a wrong version of Open3D.
Can you try this in python:
```
import open3d
help(open3d.GlobalOptimizationOption)
```
You should see something like:
```
......

 |  __init__(...)
 |      __init__(*args, **kwargs)
 |      Overloaded function.
 |      
 |      1. __init__(self: open3d.GlobalOptimizationOption) -> None
 |      
 |      Default constructor
 |      
 |      2. __init__(self: open3d.GlobalOptimizationOption, arg0: open3d.GlobalOptimizationOption) -> None
 |      
 |      Copy constructor
 |      
 |      3. __init__(self: open3d.GlobalOptimizationOption, max_correspondence_distance: float=0.03, edge_prune_threshold: float=0.25, preference_loop_closure: float=1.0, reference_node: int=-1) -> None
 |  

......
```
The third initialization function should work with the latest make_fragment script. (In your log, the init function does not take parameter preference_loop_closure as input.)

**Comment by argosvr** [comment]
Thanks! in fact the problem was that I made a fresh clone of open3d but after that I used the old terminal windows open on the previous install.. then it was pointing to the trash and the old version... stupid me !

**Comment by qianyiforma** [comment]
I think you are still importing a wrong version of Open3D.
Can you go to ``build/lib/Python`` folder, run Python (use the right python version, which should match the name of the .so file), then do the ``help(...)`` thing there?

**Comment by argosvr** [comment]
I have this : open3d.cpython-35m-x86_64-linux-gnu.so
>>> help('open3d.cpython-35m-x86_64-linux-gnu.so')
no Python documentation found for 'open3d.cpython-35m-x86_64-linux-gnu.so'

I just tried a make uninstall and a make install to be sure to build the right Open3D Python module. But same result.

**Comment by argosvr** [comment]
I think it has something to do with the problem we have to install the last version of open3d on Ubuntu 16.04 (see issue #441 )
when I try python biding, I got this:
 cmake -DPYTHON_EXECUTABLE:FILEPATH=/usr/lib/python2.7/ ../src
CMake Deprecation Warning at CMakeLists.txt:8 (cmake_policy):
  The OLD behavior for policy CMP0054 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.


-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Open3D 0.2.0.0
-- Compiling on Unix
-- Disable RealSense since it is not fully supported on Linux.
-- Using installed OpenMP 
-- Using installed EIGEN3 3.2.92
-- Using installed GLEW 1.13.0
-- Using installed GLFW 3.1.2
-- Using installed LIBJPEG 
-- Using installed JSONCPP 1.7.2
-- Using installed LIBPNG 1.6.20
-- Building PYBIND11 from source
-- Found PythonInterp: /usr/lib/python2.7 (found version "1.4") 
CMake Error at External/pybind11/tools/FindPythonLibsNew.cmake:95 (message):
  Python config failure:

Call Stack (most recent call first):
  External/pybind11/tools/pybind11Tools.cmake:16 (find_package)
  External/pybind11/CMakeLists.txt:33 (include)


-- Configuring incomplete, errors occurred!
See also "/media/argos/UbuntuData/Open3D/build/CMakeFiles/CMakeOutput.log".

**Comment by qianyizh** [comment]
Merge this thread with #441
