### ISSUE TITLE
Coordinate frame displayed on the visualization windows

### ISSUE THREAD

**Issue by blackccpie** [IntelVCL/Open3D#451]
Hello,

This is rather a feature request than an issue, but I think it would be great if we could have coordinate frame displayed on the visualization windows. 

Thx

**Comment by syncle** [comment]
Hi @blackccpie. Open3D has a primitive for coordinate frame. http://open3d.org/docs/tutorial/Basic/visualization.html#geometry-primitives is this what you mean?

**Comment by blackccpie** [comment]
Hi @syncle, my mistake, I missed that in the doc and that's what I need!
Thanks for the tip

**Comment by chrisranderson** [comment]
The link above is dead. For future people searching, you can use this:

```
visualizer.add_geometry(TriangleMesh.create_coordinate_frame())
```

**Comment by MegaYEye** [comment]
A quick answer:
```o3d.visualization.draw_geometries([o3d.geometry.TriangleMesh.create_coordinate_frame()])```

**Comment by April211** [comment]
cloud & frame:
mesh_frame = o3d.geometry.TriangleMesh.create_coordinate_frame(...)
o3d.visualization.draw_geometries([mesh_frame, cl],...)

**Comment by dust1nth3wind** [comment]
hey @April211 i tried what you mentioned, but the frame wont show up, just the pointcloud.
It seems like i am not able to visualize a point cloud and a mesh at the same time, does anyone has an idea how to solve that?

**Comment by themightyoarfish** [comment]
see https://github.com/isl-org/Open3D/issues/239, this use case will not be supported, and one should use the new API, although it seems much more complicated.

**Comment by Brez18** [comment]
> hey @april211 i tried what you mentioned, but the frame wont show up, just the pointcloud. It seems like i am not able to visualize a point cloud and a mesh at the same time, does anyone has an idea how to solve that?

U just need to add this geometry to the array like [o3d.geometry.TriangleMesh....... , your_pcd]
