### ISSUE TITLE
Noisy marching cubes mesh

### ISSUE THREAD

**Issue by godfather1402** [IntelVCL/Open3D#454]
I found the marching cubes mesh algorithm(extract from TSDF volume) provides a noisy mesh as a tutorial here 
http://www.open3d.org/docs/tutorial/Advanced/rgbd_integration.html#tsdf-volume-integration
But the provided mesh (fountain dataset) in the color map optimization tutorial is very smooth
I would like to ask a question that how I can obtain the smooth mesh?  
I think marching cubes mesh algorithm has holes and noisy from the original paper (http://paulbourke.net/geometry/polygonise/)
Thanks

**Comment by syncle** [comment]
HI @godfather1402. TSDF volume works like average filter in 3D space. If there is more and more frames are integrated, there are more and more samples will be gathered around the target surface. This will produce high fidelity surface if we extract a mesh from the final volume. In this way, if we integrate more frames, we can get smoother mesh.

The provided tutorial only integrates five noisy RGBD frames. This is just for a quick start. Five frames are not sufficient for producing smooth mesh. The other examples in reconstruction system often integrate 100 frames. This idea is applied to the fountain dataset, so it is smooth. Please have a look other examples that I produced recently: https://github.com/IntelVCL/Open3D/issues/231#issuecomment-402824835
