### ISSUE TITLE
create deb installer

### ISSUE THREAD

**Issue by takanokage** [IntelVCL/Open3D#456]
Building from source is error prone. Installing with pip can be unreliable because of package dependencies that pip cannot handle.

On Ubuntu maybe we could simplify the situation by creating a deb package.
Imagine installing on Ubuntu like this:

```sudo dpkg -i libopen3d.0.2.1_amd64.deb```

pip install can't handle dependencies installed through apt-get. various package managers introduce their own methodology for handling packages making it difficult to design a universal install solution.

The deb package could also handle installing the python module thus dealing with the differences between native installations of Python and package managers (like Anaconda) installations of Python.

**Comment by takanokage** [comment]
that's fair. just an idea.

**Comment by syncle** [comment]
We have tested our recent release with virtualenv or anaconda, so the issue is resolved. @takanokage: feel free to reopen it.

**Comment by alexmyczko** [comment]
there's interest in a deb package, which is not only used by Ubuntu but also Debian: https://bugs.debian.org/892805
