### ISSUE TITLE
how can I get the result of "estimate_normals" 

### ISSUE THREAD

**Issue by adioshun** [IntelVCL/Open3D#457]
I am trying to estimate the normals. (As I know, it will be  `nx,ny,nz` format ???)

I follow the code without downsampling step, however the result is the same. 

```python 
import numpy as np
from open3d import *

downpcd = read_point_cloud("test.pcd")

#downpcd = downpcd.normals
draw_geometries([downpcd])
estimate_normals(downpcd, search_param = KDTreeSearchParamHybrid(radius = 1.0, max_nn = 5))

draw_geometries([downpcd])
```
also the `result` is a bool value : `result = estimate_normals(downpcd, search_param = KDTreeSearchParamHybrid(radius = 1.0, max_nn = 5))`

could you give me comments or a sample code to test. 

Thanks

**Comment by syncle** [comment]
HI @adioshun.

Try this
```
print("single normal")
print(downpcd.normals[0])

print("Normal as a numpy array")
print(np.asarray(downpcd.normals))
```
``estimate_normals`` is inplace function. The return value is nothing to do with vertex normal.

**Comment by adioshun** [comment]
@syncle  thanks for your comment. I tried it. but, it does not work neither. 

Are there any requirements to get the normals from PCD. (eg. *.ply only, needs voxelization)

I also tried `TestData` on your github. 

![](https://i.imgur.com/J9XWKZ6.png)

**Comment by syncle** [comment]
Oh, it is bit weird since I cannot see any issues with ``TestData/fragment.ply`` file.

This is my log:
```
Python 3.6.1 |Anaconda 4.4.0 (x86_64)| (default, May 11 2017, 13:04:09) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from open3d import *
>>> pcd = read_point_cloud("../../TestData/fragment.ply")
Reading PLY: [========================================] 100%
>>> print(pcd)
PointCloud with 196133 points.
>>> print(pcd.points)
std::vector<Eigen::Vector3d> with 196133 elements.
Use numpy.asarray() to access data.
>>> print(pcd.has_normals())
True
>>> print(pcd.normals)
std::vector<Eigen::Vector3d> with 196133 elements.
Use numpy.asarray() to access data.
>>> print(pcd.normals[0])
[-0.52822143 -0.08778229 -0.84455693]
```
The only suspicious line is that ``pcd.has_normals()`` is ``False`` in your case. 
Can you check fragment.ply file again whether it is modified to lose normal directions for some reason? 

Of course, in general, it is necessary to compute point normal if a point cloud don't have point normal:
```
estimate_normals(pcd, search_param = KDTreeSearchParamHybrid(radius = 0.1, max_nn = 30))
```
After applying ``estimate_normals``, ``pcd.has_normals()`` should be ``True`` and you will be able to access normal elements.

**Comment by syncle** [comment]
Hi @adioshun, can you clarify this answer was helpful for you?

**Comment by adioshun** [comment]
@syncle Now, it works. thanks alot

**Comment by NaveenBefin** [comment]
I wanted to save a PCD output which can be visualise in open3D window. can i save the **draw_geometries** function to a PCD file? here is the following code:
from open3d import *\

import pcl
import numpy as np
import copy

def draw_registration_result(source, target, transformation):
    source_temp = copy.deepcopy(source)
    target_temp = copy.deepcopy(target)
    source_temp.paint_uniform_color([1, 0.706, 0])
    target_temp.paint_uniform_color([0, 0.651, 0.929])
    source_temp.transform(transformation)
    draw_geometries([source_temp, target_temp])
    

if __name__ == "__main__":
    source = read_point_cloud("/home/naveen/PCL/python-pcl/program/python/colleage/d1.pcd")
    target = read_point_cloud("/home/naveen/PCL/python-pcl/program/python/colleage/d8.pcd")
    threshold = 0.02
    trans_init = np.asarray([[ 0.9966527, -0.08160416, 0.00498396, -0.53212017],
 [ 0.08153274, 0.99658436, 0.01313108, -0.73882985],
 [-0.00603849, -0.01268078, 0.9999022, -0.05852932],
 [ 0.,          0.,          0.,          1.        ]]
)
    draw_registration_result(source, target, trans_init)
    print("Initial alignment")
    evaluation = evaluate_registration(source, target,
            threshold, trans_init)
    print(evaluation)

    print("Apply point-to-point ICP")
    reg_p2p = registration_icp(source, target, threshold, trans_init,
            TransformationEstimationPointToPoint())
    print(reg_p2p)
    print("Transformation is:")
    print(reg_p2p.transformation)
    print("")
    draw_registration_result(source, target, reg_p2p.transformation)

    print("Apply point-to-plane ICP")
    reg_p2l = registration_icp(source, target, threshold, trans_init,
            TransformationEstimationPointToPlane())
    print(reg_p2l)
    print("Transformation is:")
    print(reg_p2l.transformation)
    print("")
    draw_registration_result(source, target, reg_p2l.transformation)

in this line i'm trying to write the output to out.pcd
    write_point_cloud("out.pcd", source_temp)

can we save the output???

**Comment by qianyizh** [comment]
You can use ``source.Transform(reg_p2l.transformation)`` or something like that to transform your source point cloud, then you save it.

**Comment by wangmiaowei** [comment]
@qianyizh @adioshun @syncle @NaveenBefin  I can show the vertex normal using "pcd.estimate_normals(search_param=o3d.geometry.KDTreeSearchParamHybrid(radius=0.1, max_nn=30))
o3d.visualization.draw_geometries([pcd])"
But how to save the vertex normal as .ply file? Is there any valid suggestion? Thanks!!!
