### ISSUE TITLE
Error when import open3d in python

### ISSUE THREAD

**Issue by arcosintan** [IntelVCL/Open3D#458]
Hi, when I import open3d in python, it shows error message like this
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/tierney/.local/lib/python3.6/site-packages/open3d/__init__.py", line 11, in <module>
    from open3d.macos import *
  File "/Users/tierney/.local/lib/python3.6/site-packages/open3d/macos/__init__.py", line 7, in <module>
    globals().update(importlib.import_module('open3d.macos.open3d').__dict__)
  File "/Users/tierney/miniconda3/envs/op3d/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: dlopen(/Users/tierney/.local/lib/python3.6/site-packages/open3d/macos/open3d.so, 2): Symbol not found: __Py_ZeroStruct
  Referenced from: /Users/tierney/.local/lib/python3.6/site-packages/open3d/macos/open3d.so
  Expected in: flat namespace
 in /Users/tierney/.local/lib/python3.6/site-packages/open3d/macos/open3d.so
`

let me describe my environment:
I use python provided by conda, here is package list

blas                      1.0                         mkl  
boost                     1.67.0                   py36_4  
bzip2                     1.0.6                h1de35cc_5  
ca-certificates           2018.03.07                    0  
certifi                   2018.4.16                py36_0  
cycler                    0.10.0           py36hfc81398_0  
freetype                  2.9.1                hb4e5f40_0  
icu                       58.2                 h4b95b61_1  
intel-openmp              2018.0.3                      0  
jsoncpp                   1.8.3                ha5298f7_0  
kiwisolver                1.0.1            py36h0a44026_0  
libboost                  1.67.0               hebc422b_4  
libcxx                    4.0.1                h579ed51_0  
libcxxabi                 4.0.1                hebd6815_0  
libedit                   3.1.20170329         hb402a30_2  
libffi                    3.2.1                h475c297_4  
libgfortran               3.0.1                h93005f0_2  
libiconv                  1.15                 hdd342a3_7  
libpng                    1.6.34               he12f830_0  
matplotlib                2.2.2            py36hbf02d85_2  
mkl                       2018.0.3                      1  
mkl_fft                   1.0.2            py36h6b9c3cc_0  
mkl_random                1.0.1            py36h5d10147_1  
ncurses                   6.1                  h0a44026_0  
numpy                     1.14.5           py36h648b28d_4  
numpy-base                1.14.5           py36ha9ae307_4  
openssl                   1.0.2o               h26aff7b_0  
pip                       10.0.1                   py36_0  
py-boost                  1.67.0           py36h6440ff4_4  
pyparsing                 2.2.0                    py36_1  
python                    3.6.6                hc167b69_0  
python-dateutil           2.7.3                    py36_0  
pytz                      2018.5                   py36_0  
readline                  7.0                  hc1231fa_4  
setuptools                39.2.0                   py36_0  
six                       1.11.0                   py36_1  
sqlite                    3.24.0               ha441bb4_0  
tk                        8.6.7                h35a86e2_3  
tornado                   5.0.2            py36h1de35cc_0  
wheel                     0.31.1                   py36_0  
xz                        5.2.4                h1de35cc_4  
zlib                      1.2.11               hf3cbc9b_2

**Comment by arcosintan** [comment]
Sorry for this issue post. As developers mentioned, open3d only support native python environment

**Comment by syncle** [comment]
HI @arcosintan. Actually the error looks like the issue of python version mismatch: the python version used for compilation and the python version used for execution is not matching. I saw this type of error message many times for this case. 

Can you try check what python version cmake detected, and try this tutorial http://open3d.org/docs/compilation.html#python-binding to fix this?

**Comment by arcosintan** [comment]
I used conda and cmake gui to build open3d, the python version I choosed is in miniconda/envs/op3d/bin/python, which is python 3.6. I thought this issue was caused by non-native python. So, highly demand conda support. Thanks for replying me so fast.

**Comment by syncle** [comment]
It is bit weird. Open3D should run if you build from source regardless it is running native python or not. The native python issue we aware is the case when open3d module is installed by ``pip``. I build Open3D using my Mac use it with ``anaconda``. For example, when I run cmake, cmake says
```
:
-- Found PythonInterp: /Users/mypath/anaconda/bin/python3.6 (found version "3.6.1") 
-- Found PythonLibs: /Users/mypath/anaconda/lib/libpython3.6m.dylib
:
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/mypath/Open3D/build
```
After building and install ``make -j install``, I got 
```
:
-- Installing: /mypath/open3d_install/include/Open3D/Visualization/Visualizer/VisualizerWithCustomAnimation.h
-- Installing: /mypath/open3d_install/include/Open3D/Visualization/Visualizer/VisualizerWithEditing.h
-- Installing: /mypath/open3d_install/include/Open3D/Visualization/Visualizer/VisualizerWithKeyCallback.h
-- Installing: /mypath/.local/lib/python3.6/site-packages/open3d.cpython-36m-darwin.so
```
I can use Open3D like below:
```
$ python
Python 3.6.1 |Anaconda 4.4.0 (x86_64)| (default, May 11 2017, 13:04:09) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import open3d
>>> help(open3d)
Help on module open3d:

NAME
    open3d - Python binding of Open3D
:
```
Can you check the new build is correctly installed as well? For some reason, python may try to import old Open3D python module that does not compatible with your python.

**Comment by arcosintan** [comment]
I got it works, thank you so much. I didn't attach -j when I make it. But during the process of make, there are a lot of warnings generated, which is not happened when I do make without -j. after all, it works.

**Comment by syncle** [comment]
Good to hear! Actually ``make -j`` is for building source using multiple cores. I think some of warning messages are still appearing but blow away quickly in terminal since multiple cores building codes at the same time. We are aware this warning issue, and shall be fixed.
