### ISSUE TITLE
failed to load jpg and png file

### ISSUE THREAD

**Issue by arcosintan** [IntelVCL/Open3D#460]
I use opencv2's imwrite function to save color and depth image, the depth image is CV_16UC1 and color image is CV_8UC4. My environment is python3.6 

After I run the sample rgbd-redwood with replaced file path. open3d shows:
[CreateRGBDImageFromColorAndDepth] Unsupported image format.
RGBDImage of size
Color image : 0x0, with 0 channels.
Depth image : 0x0, with 0 channels.
Use numpy.asarray to access buffer data.

Could you please help me fix this?

**Comment by syncle** [comment]
Can you share one pair of image? Let me quick check.

**Comment by arcosintan** [comment]
I saw #44, thank you.

**Comment by arcosintan** [comment]
So, if I have 1080p color image and 424p depth image, should I scale color image to 424p or crop a 424p image from the original one?

**Comment by syncle** [comment]
It is more like resizing. Actually, color and depth cameras need to be calibrated, and need to be aligned in the same image domain. It will be not just cropping or resizing, but like mapping pixels to new domain using extrinsic/intrinsic calibration information. Aligning color and depth image domain is necessary for some applications: reconstruction system and color map optimization and so on. 

Most of the depth sensor API shall provide this functionality, and you don't have to do it by yourself. Please check with your depth camera API.

**Comment by arcosintan** [comment]
Thank you!

**Comment by syncle** [comment]
Good to hear. Let me close this issue. Please open again if necessary.
