### ISSUE TITLE
internal compiler error: Killed during build, presumably memory related

### ISSUE THREAD

**Issue by konnerthg** [IntelVCL/Open3D#461]
Error while building:

c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
Core/CMakeFiles/Core.dir/build.make:806: recipe for target 'Core/CMakeFiles/Core.dir/Utility/Eigen.cpp.o' failed
make[2]: *** [Core/CMakeFiles/Core.dir/Utility/Eigen.cpp.o] Error 4
make[2]: *** Waiting for unfinished jobs....
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
Core/CMakeFiles/Core.dir/build.make:686: recipe for target 'Core/CMakeFiles/Core.dir/Registration/PoseGraph.cpp.o' failed
make[2]: *** [Core/CMakeFiles/Core.dir/Registration/PoseGraph.cpp.o] Error 4
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
Core/CMakeFiles/Core.dir/build.make:758: recipe for target 'Core/CMakeFiles/Core.dir/Registration/TransformationEstimation.cpp.o' failed
make[2]: *** [Core/CMakeFiles/Core.dir/Registration/TransformationEstimation.cpp.o] Error 4
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
Core/CMakeFiles/Core.dir/build.make:134: recipe for target 'Core/CMakeFiles/Core.dir/ColorMap/ColorMapOptimization.cpp.o' failed
make[2]: *** [Core/CMakeFiles/Core.dir/ColorMap/ColorMapOptimization.cpp.o] Error 4
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
Core/CMakeFiles/Core.dir/build.make:374: recipe for target 'Core/CMakeFiles/Core.dir/Geometry/RGBDImage.cpp.o' failed
make[2]: *** [Core/CMakeFiles/Core.dir/Geometry/RGBDImage.cpp.o] Error 4

**To Reproduce**
util/scripts/install-deps-ubuntu.sh
mkdir build
cd build
cmake ../src -DCMAKE_INSTALL_PREFIX=<open3d_install_directory>
make -j

**Expected behavior**
Clean installation

**Desktop (please complete the following information):**
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.4 LTS
Release:	16.04
Codename:	xenial
4 GB main memory availabe

**Additional context**
Is this _only_ a memory issue? During installation my main memory fills up completely. At the same time the package manager gives: Couldn't make mmap of ... bytes - DynamicMMap (12: Cannot allocate memory)

Is installation possible on my machine with only 4 GB main memory available?

Thank you

**Comment by syncle** [comment]
Hi. Is this virtual machine? Actually I experienced the same issue when I used a virtual machine with 2 CPU cores. My fix was to use:
```
make install
```
instead of 
```
make -j install
```
This will only use single thread and take much longer time, but it should work. Open3D is not heavy library. I believe it would run on 4GB memory.

**Comment by konnerthg** [comment]
Solved. Thank you.
