### ISSUE TITLE
Small bug of Visualizer::CaptureScreenImage's __APPLE__ case of VisualizerRender.cpp

### ISSUE THREAD

**Issue by dotchang** [IntelVCL/Open3D#467]
In the line 248 of VisualizerRender.cpp,
glReadPixels(j, 0, 1, depth_image.width_,
                GL_DEPTH_COMPONENT, GL_FLOAT,
                float_buffer.data());

4th argument "depth_image.width_" will work well at wide image case(width >= height), but it will not work at thin image case(height > width). 
I think, it would be better to "std::max(depth_image.width_, depth_image.height_)".

**Comment by qianyizh** [comment]
Umm, this looks like a bug.
If it read column by column, then it should be:
```
        glReadPixels(j, 0, 1, depth_image.height_,
                GL_DEPTH_COMPONENT, GL_FLOAT,
                float_buffer.data());
```
instead of:
https://github.com/IntelVCL/Open3D/blob/9cc63acf16e7ad67dca9dceca0a73bba192f66a7/src/Visualization/Visualizer/VisualizerRender.cpp#L248-L250

**Comment by dotchang** [comment]
I see.
I don't have mac environment actually. Could you fix it?

**Comment by syncle** [comment]
I agree with @qianyizh . According to this https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glReadPixels.xhtml, the ``depth_image.height_`` should be used in the fourth arguement. 

@dotchang: Thanks for finding the issue! The routine actually reads opengl buffer pixels column by column, and this should work for both width >= height or width < height case. I will double-check with my Mac and submit PR.
