### ISSUE TITLE
Error while running point-to-plane ICP

### ISSUE THREAD

**Issue by mutp** [IntelVCL/Open3D#468]
Whenever I run global registration or multiway registration on my point clouds, I get this error - 

> Error: TransformationEstimationPointToPlane requires pre-computed normal vectors.

The error clearly happens when running the ICP part of the above two algorithms.
What am I doing wrong?

**Comment by qianyizh** [comment]
The point cloud needs to have normal. You can run ``estimate_normals()`` function to do it. See the Note in this page:
http://www.open3d.org/docs/tutorial/Basic/icp_registration.html

**Comment by mutp** [comment]
In the global registration example, estimate_normals() is run. Still when the code reaches  Point-to-plane ICP registration, I get the same error 
> Error: TransformationEstimationPointToPlane requires pre-computed normal vectors.

I'm running the Tutorial global_registration.py script on my data. (Attached the data 
[data.zip](https://github.com/IntelVCL/Open3D/files/2222980/data.zip)
it here)

**Comment by syncle** [comment]
This is the issue related to the size of the point cloud. Please check https://github.com/IntelVCL/Open3D/issues/471#issuecomment-407488801

**Comment by NaveenBefin** [comment]
can we save the result of ICP PROGRAM?? i need to save the results in .PCD can anyone help in this??

**Comment by acenturyandabit** [comment]
For future readers who google the error that open3d gives out, (since the link qianyizh posted is dead):

1. Load your pointcloud using `your_pointcloud = read_point_cloud()`
2. Run `your_pointcloud.estimate_normals()`
3. Run your ICP.

**Comment by ryo-matsuzaka** [comment]
@acenturyandabit 
Thank you very much.
It worked.
