### ISSUE TITLE
Get number of iterations for ICP convergence

### ISSUE THREAD

**Issue by Andyjk1406** [IntelVCL/Open3D#476]
Hi

I am used to C++ but am running this nice library in Python to test the functions.

Is it possible to find out how many iterations ICP actually took ?

` reg_p2l = registration_icp(source, target, threshold, trans_init,
            TransformationEstimationPointToPlane(),ICPConvergenceCriteria(1e-12,1e-12,2000))
print(reg_2pl.iterations_final)`

doesn't work (but it was just a guess!), and in Python (using Idle) I don't have the nice function hints that I get in Visual Studio with C++, so I don't know how to check for public members/functions in Python.

**Comment by syncle** [comment]
Hello @Andyjk1406. You can put ``set_verbosity_level(VerbosityLevel.Debug)`` before calling ``registration_icp`` to see the detailed log. To retrieve members of the class the best and simplest way is to use ``help(reg_p2l)``. Currently, it does not have iteration number, but you can find something like:
```
class RegistrationResult(pybind11_builtins.pybind11_object)
 |  Method resolution order:
 |      RegistrationResult
 |      pybind11_builtins.pybind11_object
 |      builtins.object
 |  
 |  Methods defined here:
 |  
 |  __copy__(...)
 |      __copy__(self: open3d.RegistrationResult) -> open3d.RegistrationResult
 |  
 |  __deepcopy__(...)
 |      __deepcopy__(self: open3d.RegistrationResult, arg0: dict) -> open3d.RegistrationResult
 |  
 |  __init__(...)
 |      __init__(*args, **kwargs)
 |      Overloaded function.
 |      
 |      1. __init__(self: open3d.RegistrationResult) -> None
 |      
 |      Default constructor
:
 |      Copy constructor
 |  
 |  __repr__(...)
 |      __repr__(self: open3d.RegistrationResult) -> str
 |  
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |  
 |  correspondence_set
 |  
 |  fitness
 |  
 |  inlier_rmse
 |  
 |  transformation
 |  
 |  ----------------------------------------------------------------------
 |  Methods inherited from pybind11_builtins.pybind11_object:
 |  
 |  __new__(*args, **kwargs) from pybind11_builtins.pybind11_type
 |      Create and return a new object.  See help(type) for accurate signature.
```
Another helpful examples can be found from: http://open3d.org/docs/tutorial/Basic/python_interface.html

**Comment by Andyjk1406** [comment]
Ok thanks, that works.
