### ISSUE TITLE
Multiway registration using fast global

### ISSUE THREAD

**Issue by Andyjk1406** [IntelVCL/Open3D#480]
The 2016 paper for fast global registration includes multiview registration without the drawback of optimising many pairwise clouds (some of which can slip and slide).

I understand that the pose graph technique used here will minimise the influence of false edges, but is there a way to use multiview fast global registration in open3d? This would seem preferable to completely discarding a good overlap (edge) because its pairwise alignment had fallen into the wrong local minimum.

**Comment by syncle** [comment]
Thanks for the suggestion. We will try to add this in Open3D, but I we cannot guarantee this will be shipped in the near future. I will mark this request in our list.

**Comment by pranavgundewar** [comment]
Any update on this?
