### ISSUE TITLE
Correct way to visualise a vector of pointclouds in C++

### ISSUE THREAD

**Issue by Andyjk1406** [IntelVCL/Open3D#484]
I am loading 20 pointclouds, then transforming them and displaying them. To do this I do

// Display

	std::vector<std::shared_ptr<const Geometry>> pcds_geom;
	for (int i = 0; i < pcds.size(); i++) {
			std::shared_ptr<const Geometry> pcd_geom;
			pcd_geom = std::dynamic_pointer_cast<PointCloud>(pcds[i]);
			pcds_geom.push_back(pcd_geom);
	}
	DrawGeometries( pcds_geom , "PointCloud", 1600, 900);
`

but I am wondering if this is the correct way? pcds is a std::vector<std::shared_ptr<three::PointCloud>  but I need these as pointclouds (not Geometries) so that I can apply a Transform to them first.

Is there a more concise way to display them ?

**Comment by syncle** [comment]
You don't have to explicitly type-cast ``PointCloud`` to ``Geometry``. ``Geometry`` is a abstract class of ``PointCloud``, ``TraingleMesh``, and even for ``Image``. Therefore, you can easily define container of ``PointCloud`` using ``Geometry``. 

For example, the following code reads the same point cloud 10 times and make a list ``pcds`` and display it:

```
    std::vector<std::shared_ptr<const Geometry>> pcds;
    for (int i = 0; i < 10; i++) {
        auto pcd = std::make_shared<PointCloud>();
        ReadPointCloud(argv[1], *pcd);
        # do your transformation like 
        # Eigen::Matrix4d trans = Eigen::Matrix4d::Identity();
        # pcd->Transform(trans)
	pcds.push_back(pcd);
    }
    DrawGeometries(pcds);
```

**Comment by Andyjk1406** [comment]
Thanks

This works if I want to do the transform in the loader function, before pushing it onto the vector.

However, if I want to call a loader function, then later call a function to create some Eigen::Matrix4d transforms, and then apply them, it seems that I must return a vector<Pointcloud> from my loader function because <Geometry> does not have a Transform member.

So, for example, in the example you give above, if I later tried
`pcds[0]->Transform(matrix)`

I cannot compile becasue Geometries does not contain a Transform member.

Is there any way around this or is my first solution the neatest we can get ?

**Comment by syncle** [comment]
I see the point. How about this way?

```
    std::vector<std::shared_ptr<PointCloud>> pcds;
    // batch loader
    for (int i = 0; i < 20; i++) {
        auto pcd = std::make_shared<PointCloud>();
        ReadPointCloud(argv[1], *pcd);
		pcds.push_back(pcd);
    }
    // batch transform
    for (int i = 0; i < 20; i++) {
        Eigen::Matrix4d trans = Eigen::Matrix4d::Identity();
        pcds[i]->Transform(trans);
    }
    batch_pcd_visualization(pcds);
```
and you have additional helper function: ``batch_pcd_visualization``
```
void batch_pcd_visualization(
        std::vector<std::shared_ptr<PointCloud>> pcds)
{
    std::vector<std::shared_ptr<const Geometry>> pcds_geo;
    for (auto i = 0; i < pcds.size(); i++) {
        pcds_geo.push_back(pcds[i]);
    }
    DrawGeometries(pcds_geo);
}
```
basically you are maintaining vector of point cloud in your main code. Using ``batch_pcd_visualization`` just envolves copy of shared pointers, so this should be efficient. 

Please correct me if I am wrong :)

**Comment by syncle** [comment]
@Andyjk1406: Closing for now due to inactivity. Feel free to reopen if needed.
