### ISSUE TITLE
Integer only version?

### ISSUE THREAD

**Issue by rafael2k** [IntelVCL/Open3D#487]
I have a need for integer only implementation stuff (using hardware which does not go well with floating point). Which steps should I take to make an integer only Open3D branch?

**Comment by syncle** [comment]
Umm I think it would be plausible because Open3D requires on double precision operations for registration, visualization, optimization, and so on.

**Comment by rafael2k** [comment]
Thanks!

**Comment by syncle** [comment]
Let me close this issue. Feel free to open this if needed. :)
