### ISSUE TITLE
How to get the normal computed by estimate_normals()?

### ISSUE THREAD

**Issue by DKandrew** [IntelVCL/Open3D#490]
I am trying to compute surface normals of a flat wall using `estimate_normals()` function. In the tutorial, it only shows how to plot the normals, but did not tell us how to store them. I guess the normal is stored in the PointCloud Class, but looking into the PointCloud, Geometry, Geometry3D I cannot find any variable relates to the surface normals. The documentation of the estimate_normals does not have this information either.

**Comment by syncle** [comment]
Yes. For example:
```
>>> from open3d import *
>>> pcd = read_point_cloud("../../TestData/fragment.ply")
Reading PLY: [========================================] 100%
>>> print(pcd)
PointCloud with 196133 points.
>>> print(pcd.points)
std::vector<Eigen::Vector3d> with 196133 elements.
Use numpy.asarray() to access data.
>>> print(pcd.has_normals())
True
>>> print(pcd.normals)
std::vector<Eigen::Vector3d> with 196133 elements.
Use numpy.asarray() to access data.
>>> print(pcd.normals[0])
[-0.52822143 -0.08778229 -0.84455693]
```

**Comment by DKandrew** [comment]
Is the sequence convention of the normal XYZ?

**Comment by syncle** [comment]
Yes it is :)
