### ISSUE TITLE
Voxel downsampling: pick one of the original points instead of the centroid

### ISSUE THREAD

**Issue by tejaskhot** [IntelVCL/Open3D#503]
Is there a way to downsample such that the point generated by each voxel is one of the points occupying it and not the centroid of those points? The current API does not seem to support this.

**Comment by syncle** [comment]
Hi @tejaskhot. Thanks for the great question!

We actually have an implementation for this request. It was for [tangent convolution project](http://vladlen.info/publications/tangent-convolutions-dense-prediction-3d/) project that builds index maps used for pooling and unpooling. The additional class can be found [here](https://github.com/tatarchm/Open3D/blob/35b2729e44701c73fb8c53bd7b3f182d1f2f508f/src/Core/Geometry/DownSample.cpp#L95-#L151).

I am working on several compilation issues, but will handle this soon.

**Comment by syncle** [comment]
Update: working branch https://github.com/syncle/Open3D/tree/down_sample_index
