### ISSUE TITLE
Please don't install empty directories

### ISSUE THREAD

**Issue by yurivict** [IntelVCL/Open3D#509]
You install these two empty directories:
```
include/Open3D/IO/FileFormat
include/Open3D/Visualization/Shader/GLSL
```

Could you please remove them? They are redundant.
Thanks!

**Comment by syncle** [comment]
Thanks @yurivict for pointing out this issue. Could you help to fix this? I think you can exclude these folders by modifying src/IO/CMakeLists.txt and src/Visualization/CMakeLists.txt.
For example, you can exclude the ``include/Open3D/IO/FileFormat`` by modifying the following lines.
```
#src/IO/CMakeLists.txt
install(DIRECTORY   "${CMAKE_CURRENT_SOURCE_DIR}"
        DESTINATION "${CMAKE_INSTALL_PREFIX}/include/${CMAKE_PROJECT_NAME}"
        PATTERN     "*.cpp" EXCLUDE
        PATTERN     "*.txt" EXCLUDE)
```
