### ISSUE TITLE
CMake Error: Could not find X11

### ISSUE THREAD

**Issue by CZ-Wu** [IntelVCL/Open3D#511]
when I run `cmake ../src`
it rises error as following: 
CMake Error at /home/lab-lin.jiehong/anaconda3/share/cmake-3.6/Modules/FindX11.cmake:439 (message):
  Could not find X11
Call Stack (most recent call first):
  External/GLFW/CMakeLists.txt:232 (find_package)

CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
M_LIBRARY
    linked by target "png" in directory /media/data1/pointcloud/Mycode/Open3D/src/External/libpng

**Comment by takanokage** [comment]
One solution is to install the open3d prerequisites as indicated in the
docs.
The other solution is to set the BUILD_PNG cmake option to ON.

Good luck!

**Comment by syncle** [comment]
Closed due to inactivity. @CZ-Wu: please feel free to reopen this if necessary :)
