### ISSUE TITLE
[Question]  How does TSDFVolume.extract_triangle_mesh() avoid double layer mesh?

### ISSUE THREAD

**Issue by bing-jian** [IntelVCL/Open3D#520]
I tried the TSDF volume integration and mesh extracting on some RGB-D face images,  the results look nice.  By looking at the code in
https://github.com/IntelVCL/Open3D/blob/master/src/Core/Integration/ScalableTSDFVolume.cpp
https://github.com/IntelVCL/Open3D/blob/master/src/Core/Integration/UniformTSDFVolume.cpp
I guess around the face surface there will be a thin layer of volume ranging from 1 (exterior) to -1 (interior),  the thickness of this layer should be roughly 2*sdf_trunc_,  half being positive and 
half being negative.  Then behind this thin layer,  the volume should be filled by default value 0
due to this check  if (sdf > -sdf_trunc_f) {...}
https://github.com/IntelVCL/Open3D/blob/master/src/Core/Integration/UniformTSDFVolume.cpp#L311
Because of this,  I expect the extract_triangle_mesh() will return a double layer mesh which is understandable for open thin surfaces,  one layer around the boundary between 0 and tiny negative values inside the thin layer close to the actual face surface,  another layer at sdf == -sdf_trunc_f or around the boundary between -0.99.. and 0.  But looks like the actual mesh returned by extract_triangle_mesh()  only has one layer which is good.  Just wondering how it does it.  I also tried
marching_cubes_lewiner from skimage.measure 
https://github.com/scikit-image/scikit-image/blob/master/skimage/measure/_marching_cubes_lewiner_cy.pyx#L432
on a TSDF volume generated similarly (with sign flipped),  the resulting mesh from skimage.measure.marching_cubes_lewiner clearly showes double layer which is less desirable but explainable.   Maybe I missed something here and will appreciate any discussion/clarification.

Thanks,
Bing

**Comment by qianyizh** [comment]
The answer is simple. It's done with these lines:
https://github.com/IntelVCL/Open3D/blob/e5c93dd49fea87ff1ab0364d1d3ffd8144c6ed77/src/Core/Integration/UniformTSDFVolume.cpp#L166-L169
Basically if a voxel has at least one vertex without tsdf (initialized with weight=0), it will not create any triangles. Thus there won't be the second layer between -0.99 to 0.

**Comment by bing-jian** [comment]
Got it!  Qianyi,  thanks for the quick answer!  So without this check based on the extra weight information, do you think the normal marching cubes will produce two layers from the volume currently generated?

**Comment by qianyizh** [comment]
Yes it will. The empty state has to be explicitly marked and checked. Otherwise there will be ambiguity.

**Comment by qianyizh** [comment]
Closing since there is already an answer. Feel free to reopen.

**Comment by bing-jian** [comment]
Qianyi, Thanks.  Forgot to mention that I made a modified cython extension
based on
https://github.com/scikit-image/scikit-image/blob/master/skimage/measure/_marching_cubes_lewiner_cy.pyx#L432
so that it also takes the weights volume and checks weights as in
https://github.com/IntelVCL/Open3D/blob/e5c93dd49fea87ff1ab0364d1d3ffd
8144c6ed77/src/Core/Integration/UniformTSDFVolume.cpp#L166-L169
So far this change works well.
