### ISSUE TITLE
WritePointCloudToPLY

### ISSUE THREAD

**Issue by ibouazizi** [IntelVCL/Open3D#526]
**Describe the bug**
All color values are set to 255.
When checking WritePointCloudToPLY.cpp it turns out that max and min in the color value clipping are inverted.

**To Reproduce**
1. Write Point Cloud to ply file

**Comment by syncle** [comment]
Could you give more details, such as code reference, minimal example? As a note, color values should be in [0,1] range.

**Comment by ibouazizi** [comment]
Yes, colors are in the range of [0, 1]
Example usage: open3d.write_point_cloud(ply_file, pcd, True)
The erroneous statement is: max(255, ..
That statement will always yield the max.

**Comment by syncle** [comment]
I just tried the following script:
```
from open3d import *

if __name__ == "__main__":

    print("Load a ply point cloud, print it, and render it")
    pcd = read_point_cloud("../../TestData/fragment.ply")
    write_point_cloud("../../TestData/fragment_saved.ply", pcd, True)
    pcd2 = read_point_cloud("../../TestData/fragment_saved.ply")
    draw_geometries([pcd2])
```
but it works fine. 

-----

> The erroneous statement is: max(255, ..
That statement will always yield the 255.

Where did you fine ``max(255, ..`` can you give me a point? I think relevant code is 

https://github.com/IntelVCL/Open3D/blob/e5c93dd49fea87ff1ab0364d1d3ffd8144c6ed77/src/IO/FileFormat/FilePLY.cpp#L317-L324

but the code seems fine to me.

**Comment by qianyizh** [comment]
@ibouazizi can you give some example code for us to better understand the issue? thanks!

**Comment by qianyizh** [comment]
Closing since lack of activity. Feel free to reopen.
