### ISSUE TITLE
Build is broken on VS2017 15.8 and later

### ISSUE THREAD

**Issue by qianyizh** [IntelVCL/Open3D#527]
**Describe the bug**
Build is broken on VS2017 15.8 and later.
Current master, version b11ebc1f56f728474d77e696bd73f9986600b0b1

See this:
https://ci.appveyor.com/project/syncle/open3d/build/1.0.512/job/keb5t0eqyxm8m9jm

c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.15.26726\include\type_traits(1271): error C2338: You've instantiated std::aligned_storage<Len, Align> with an extended alignment (in other words, Align > alignof(max_align_t)). Before VS 2017 15.8, the member type would non-conformingly have an alignment of only alignof(max_align_t). VS 2017 15.8 was fixed to handle this correctly, but the fix inherently changes layout and breaks binary compatibility (*only* for uses of aligned_storage with extended alignments). Please define either (1) _ENABLE_EXTENDED_ALIGNED_STORAGE to acknowledge that you understand this message and that you actually want a type with an extended alignment, or (2) _DISABLE_EXTENDED_ALIGNED_STORAGE to silence this message and get the old non-conformant behavior. [C:\projects\open3d\build\src\Visualization\Visualization.vcxproj]

**Comment by qianyizh** [comment]
Interesting, #517 should be the right fix for this issue. But why is the build still broken?

**Comment by qianyizh** [comment]
Ah, I think the issue is with #505 
It actually reverts the change of #517 
https://github.com/IntelVCL/Open3D/pull/505/files#diff-95e351a3805a1dafa85bf20b81d086e6L144

@syncle do you have any idea why you remove the big configuration block? Or are they supposed to be configured automatically?

**Comment by qianyizh** [comment]
Found it, they are reorged to be at the root directory.

**Comment by qianyizh** [comment]
Let me do the code change, should be easy.

**Comment by syncle** [comment]
> @syncle do you have any idea why you remove the big configuration block? Or are they supposed to be configured automatically?
> Found it, they are reorged to be at the root directory.

Yes. I reorganized. CMakeList.txt addresses general compilation configurations and src/CMakeList.txt addresses configurations for open3d library.

The fix is great. Thanks!
