### ISSUE TITLE
How to merge point cloud in C++

### ISSUE THREAD

**Issue by rafael2k** [IntelVCL/Open3D#533]
Hi,
Is there any method to merge two point clouds, instead of copying all the points by hand (in C++)?

Also, just in case, which are the camera intrinsics of Kinect v1?
; )

I'm really enjoying Open3D!

**Comment by syncle** [comment]
Hi Try using "+" operator. It works on C++ API as well. 

For example, please refer the following example:
https://github.com/IntelVCL/Open3D/blob/16cb1fec715227db9cc259bd75961146a224b6d1/examples/Cpp/PointCloud.cpp#L175-L177

**Comment by qianyizh** [comment]
Close as there is already an answer. Feel free to reopen it if the answer is not clear.

**Comment by muddassir93** [comment]
Hi @syncle
Can you please explain, whether the "=" operator in c++  makes a deep copy of or shallow copy? If it makes a shallow copy then is there any defined method in Open3D to make a deep copy of point cloud?

Regards

**Comment by syncle** [comment]
If you are using ``=`` for ``shared_ptr`` in C++, it is soft copy. Two pointers pointing the the same memory.
If ``=`` is used for Objects, it shall be hard copy.

**Comment by muddassir93** [comment]
Thanks @syncle for a quick response.

For example, if I want to make a deep copy of open3d::PointCloud object, can `=operator` will do the job or I have to call `std::shared_ptr::swap`.

**Comment by emjay73** [comment]
Are there any reference documents about how the point cloud merge algorithm works?
