### ISSUE TITLE
Instructions for installing without sudo

### ISSUE THREAD

**Issue by tejaskhot** [IntelVCL/Open3D#534]
Can we please have instructions for installing Open3D without `sudo` permissions, likely on a remote server where visualization is not needed either. #264 is related but would prefer some clearer and comprehensive steps listed in the README.

**Comment by takanokage** [comment]
Please look at:
- [generate.sh](https://github.com/IntelVCL/Open3D/blob/master/util/scripts/generate.sh)
- [build.sh](https://github.com/IntelVCL/Open3D/blob/master/util/scripts/build.sh)
- [install.sh](https://github.com/IntelVCL/Open3D/blob/master/util/scripts/inst install

Open3D is installed without sudo to ~/open3d_install.

**Comment by tejaskhot** [comment]
How to handle all the dependencies though? Following is the output of running `build.sh` on a fresh machine (note: don't have `sudo` access):
```
building...

generating...
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Open3D 0.2.0.0
-- Compiling on Unix
-- Disable RealSense since it is not fully supported on Linux.
-- Using installed OpenMP 
-- Unable to find EIGEN3 installed in the system
-- Building EIGEN3 from source
-- Unable to find GLEW installed in the system
-- Building GLEW from source
-- Unable to find GLFW installed in the system
-- Building GLFW from source
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE  
-- Could NOT find Vulkan (missing: VULKAN_LIBRARY VULKAN_INCLUDE_DIR) 
-- Using X11 for window creation
CMake Error at /usr0/home/tkhot/anaconda3/share/cmake-3.9/Modules/FindX11.cmake:429 (message):
  Could not find X11
Call Stack (most recent call first):
  3rdparty/GLFW/CMakeLists.txt:226 (find_package)


-- Configuring incomplete, errors occurred!
See also "/usr0/home/tkhot/Open3D/build/CMakeFiles/CMakeOutput.log".

make: *** No targets specified and no makefile found.  Stop.

```

**Comment by takanokage** [comment]
Here's two guidelines that may help:
- [Headless rendering](http://open3d.org/docs/tutorial/Advanced/headless_rendering.html?highlight=headless)
- [Docker](http://open3d.org/docs/tutorial/docker/docker.html)

I'm not sure which is more applicable to your specific needs.

**Comment by takanokage** [comment]
Oh, and forgot to mention, we have scripts for installing the dependencies in [scripts](https://github.com/IntelVCL/Open3D/tree/master/util/scripts).
Hopefully they don't need updating for your specific circumstances.

**Comment by tejaskhot** [comment]
Thanks for the pointers @takanokage.
The dependency installation scripts seem to require `sudo` access. 

I am running into an issue trying to compile `osmesa` per the [instruction page](http://open3d.org/docs/tutorial/Advanced/headless_rendering.html?highlight=headless):
```
checking for glproto >= 1.4.14... no
configure: error: Package requirements (glproto >= 1.4.14) were not met:

No package 'glproto' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables GLPROTO_CFLAGS
and GLPROTO_LIBS to avoid the need to call pkg-config.
```

**Comment by takanokage** [comment]
There's the option to build everything from source, that should take you around sudo for addressing the dependencies.

In order to do that you need to add the following options to `cmake` when generating the project:

> -DBUILD_EIGEN3=ON -DBUILD_GLEW=ON -DBUILD_GLFW=ON -DBUILD_JPEG=ON -DBUILD_JSONCPP=ON -DBUILD_PNG=ON 

Regarding the error you're seeing, it would seem that the `osmesa` requires `glproto` installed and `cmake` can't find it. One suggestion seems to be included in the error message: set the GLPROTO_CFLAGS and GLPROTO_LIBS environment variables to some values if `glproto` is installed on the system. Haven't done this myself before so I don't know what those values need to be.

**Comment by takanokage** [comment]
I was about to suggest Docker but even that requires you to install Docker with sudo.

**Comment by qianyizh** [comment]
@tejaskhot yeah. The dependencies come with the glfw part. If you don't need visualization, you can do the following.

1. As @takanokage suggested, turn ``-DBUILD_XXXX`` to ``ON``
2. Remove anything related to visualization in
https://github.com/IntelVCL/Open3D/blob/master/src/CMakeLists.txt
3. Remove visualization from python bindings, basically edit this file
https://github.com/IntelVCL/Open3D/blob/master/src/Python/CMakeLists.txt
4. Disable anything related to glfw and glew in this file
https://github.com/IntelVCL/Open3D/blob/master/3rdparty/CMakeLists.txt

This should do.

A better suggestion would definitely be Docker. We are in 2018 and should just enbrace containers, :)

**Comment by tejaskhot** [comment]
@qianyizh I removed all the visualization related lines from those files as you mentioned. I just cloned again and trying to build now and get the following error:
```
tkhot/Open3D/build$ cmake -DOpen3D_USE_NATIVE_DEPENDENCY_BUILD=OFF -DBUILD_EIGEN3=ON -DBUILD_GLEW=ON -DBUILD_GLFW=ON -DBUILD_JPEG=ON -DBUILD_JSONCPP=ON -DBUILD_PNG=ON ../src
CMake Error at Core/CMakeLists.txt:9 (ADD_SOURCE_GROUP):
  Unknown CMake command "ADD_SOURCE_GROUP".


CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.9)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring incomplete, errors occurred!
See also "/usr0/home/tkhot/Open3D/build/CMakeFiles/CMakeOutput.log".

```
If I run without the `../src` at the end, then I get:
```
CMake Error: The source directory "/usr0/home/tkhot/Open3D/build" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
```
In fact, this error persists even with:
```
cmake -DOpen3D_USE_NATIVE_DEPENDENCY_BUILD=OFF ../src
```

Can you please assist?

**Comment by takanokage** [comment]
I've seen this error before. In my case it helped cleaning up the build.

```
cd <Open3D_path>/util/scripts
./clean.sh
./build.sh
```

Note: it won't work without cd, aka like this: `Open3D/util/scripts/clean.sh`.

**Comment by tejaskhot** [comment]
I made some progress with this, but the `build.sh` script throws up an error at 98%. 
Here is the full log output:
https://pastebin.com/eqWbBpvt

I have tried to remove all references to Visualization, turned off building of examples and changed the `cmake` command in `build.sh` to `cmake -DCMAKE_INSTALL_PREFIX=~/open3d_install -DOpen3D_USE_NATIVE_DEPENDENCY_BUILD=OFF ..`

**Comment by tejaskhot** [comment]
I have already commented out those lines you mentioned. The output pasted was after having removed those references.

**Comment by takanokage** [comment]
It would seem this is related to the Visualization component of the Python module.

[Python/CMakeLists.txt](https://github.com/IntelVCL/Open3D/blob/master/src/Python/CMakeLists.txt)

I haven't gotten into that part of the code yet so I have not answer off the top of my head.
Maybe one of my colleagues have an idea.

**Comment by tejaskhot** [comment]
The error log I posted above was after I removed line 17 from `Python/CMakeLists.txt` which was related to the visualization part. @qianyizh Can you please assist?

**Comment by qianyizh** [comment]
It is actually pretty close! I think you just need to exclude ``Tools`` folder too then it should be good.
It is basically removing both line 10 and line 11 in:
https://github.com/IntelVCL/Open3D/blob/master/src/CMakeLists.txt

**Comment by qianyizh** [comment]
One more step closer! Now it is in compiling python binding.
Remove line 12 and line 17 in this file:
https://github.com/IntelVCL/Open3D/blob/master/src/Python/CMakeLists.txt

**Comment by tejaskhot** [comment]
Those lines are already removed and the logs I posted was after that.

**Comment by qianyizh** [comment]
Umm, that's weird. The log suggests that these files are still being compiled.
Can you try to remove the folder ``Open3D/src/Python/Visualization`` completely and see if there is error / warning?

**Comment by tejaskhot** [comment]
@qianyizh Almost there! Now I can get through the full installation process, but face this error on importing open3d:
```
In [1]: from open3d import *
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-b85738c1f906> in <module>()
----> 1 from open3d import *

ImportError: /afs/cs.cmu.edu/user/tkhot/.local/lib/python3.6/site-packages/open3d.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN6open3d16SelectDownSampleERKNS_12TriangleMeshERKSt6vectorImSaImEE

```

**Comment by tejaskhot** [comment]
@qianyizh Can you please point me to a solution for this import error?

**Comment by syncle** [comment]
The error message says the module tried to find SelectDownSampleTriangleMesh, but it couldn't see. Can you clean and re-install Open3D again? SelectDownSampleTriangleMesh is recently added, so my guess is that the issue is due to importing old version of open3d.

**Comment by qianyizh** [comment]
Yeah, this is weird. I have never seen this before. Can you maybe share the (changed) code on your fork so we can take a look?

**Comment by tejaskhot** [comment]
@syncle @qianyizh I cleaned and re-installed again but got the same error. My fork is here:
https://github.com/tejaskhot/Open3D

The steps I follow after cloning this are:
```
cd Open3D/util/scripts
./clean.sh
./build.sh
./install.sh
```

**Comment by yxlao** [comment]
After demangling, the missing symbol is
```
open3d::SelectDownSample(open3d::TriangleMesh const&, 
                         std::vector<unsigned long, 
                         std::allocator<unsigned long> > const&)
```
after looking at your fork, seems like `SelectDownSample` was removed.

**Comment by takanokage** [comment]
[SelectDownSample](https://github.com/IntelVCL/Open3D/blob/59c0645a169c589345a1b04753d5afdb5800b349/src/Core/Geometry/DownSample.cpp#L117) was removed [here](https://github.com/tejaskhot/Open3D/commit/f02060dc98a242cb96b538ed2f19a5f7d768ade9#diff-0e082f48f198b3329087124dba34b431L117).

**Comment by tejaskhot** [comment]
That solved it, thanks a lot!
