### ISSUE TITLE
Something odd with UniformTSDFVolume

### ISSUE THREAD

**Issue by martinakos** [IntelVCL/Open3D#536]
I'm doing object modelling using a TSDF to fuse point clouds of the object. I have a solution working using a library that evolved from pcl kinfu, but I wanted to try Open3D because it may be useful to have a pure CPU TSDF implementation. 

In my test, I set up things to integrate the point clouds using UniformTSDFVolume and ScalableTSDFVolume side by side. I transform the point clouds before integrating them into the TSDF so that my object of interest is at the origin. I estimate the size of my object and declare a UniformTSDFVolume of that size.  I assume the TSDF is centred around (0, 0, 0). I use the following code to instanciate the TSDFs:

```
        self.tsdf2 = o3d.UniformTSDFVolume(largest_dim, tsdf_resolution, 0.04, o3d.TSDFVolumeColorType.RGB8)
        self.tsdf3 = o3d.ScalableTSDFVolume(largest_dim/tsdf_resolution, 0.04, o3d.TSDFVolumeColorType.RGB8)
```
largest_dim is 0.25 and tsdf_resolution is 128. 

Then I integrate the point clouds with this code:

```
        rgbd = o3d.create_rgbd_image_from_color_and_depth(
            o3d.Image(color_image), 
            o3d.Image(depth_image),
            depth_trunc = 4, 
            convert_rgb_to_intensity = False)

        self.tsdf2.integrate(rgbd, self.intrinsics, pose)              
        self.tsdf3.integrate(rgbd, self.intrinsics, pose)   
```
and visualise the current TSDF contents with this code:

```
        pcd =self.tsdf2.extract_point_cloud()
        mesh_frame = o3d.create_mesh_coordinate_frame(size = 0.1)
        o3d.draw_geometries([pcd, mesh_frame], width=1000, height=600)  
        
        pcd =self.tsdf3.extract_point_cloud()
        mesh_frame = o3d.create_mesh_coordinate_frame(size = 0.1)
        o3d.draw_geometries([pcd, mesh_frame], width=1000, height=600)  
```

After integrating just one point cloud, the visualisation of tsdf3 shows me this:
![image](https://user-images.githubusercontent.com/2371869/45053328-957bfa00-b081-11e8-9829-d609e64a0525.png)
The axes frame indicates the origin and axes of the TSDF. The origin is at the center of my object of interest which is a mug standing on a desk. I'm just interested in the mug, but ScalableTSDFVolume stores every point in the point cloud. **Question**: is there any way of telling ScalableTSDFVolume to just store points within a given volume? 

The visualisation of tsdf2, however, doesn't look right:
![image](https://user-images.githubusercontent.com/2371869/45053571-3ff41d00-b082-11e8-8a10-02e17ab9cf63.png)
The axes frames is again at the origin, and tsdf2 integrated the same data as tsdf3. However, I can only see this piece of plane, which I hypothesise it may be a crop of what I see in the tsdf3 visualisation (maybe the front right area around the origin). I have tried different length and resolution parameters for UniformTSDFVolume but I seem to always get a visualisation of the same "cropped" area. I don't understand what's going on. May this be a bug?

**Comment by syncle** [comment]
Hi @martinakos, thanks for using Open3D.

> I assume the TSDF is centred around (0, 0, 0).

It is actually not. a single TSDF volume would span a cubic with two endpoints - (0,0,0) and (size,size,size). Here are some differences between ``ScalableTSDFVolume`` and ``UniformTSDFVolume``.
- ``ScalableTSDFVolume`` automatically use multiple cubics, so you are looking the complete scene. 
- ``UniformTSDFVolume`` just integrate depth images to single cubic, so the points located in negative x, y, z coordinate space are being ignored.

Here are two suggestions:
- If you want to use ``ScalableTSDFVolume``, please crop a cup after the integration (I assume you know interested region)
- If you want to use ``UniformTSDFVolume``, add a transform to ``pose`` that translates 2/size along x and y axis, in order to make your depth map are correctly integrated into single cubic.

**Comment by martinakos** [comment]
Thanks for the reply. I can see now that the TSDF is not centred at (0,0,0). I've exposed the parameter origin for the UniformTSDFVolume constructor to the python binding, and I was able to get it to work as I wanted by using an origin of (-length/2, -length/2, -length/2).

**Comment by qianyizh** [comment]
Close this issue since there seems to be a solution. Feel free to reopen it.

**Comment by pavan4** [comment]
Hello, I am facing a similar issue. 

I have constructed a mesh using `ScalableTSDFVolume` and calling  below to create the mesh which works well

    mesh = volume.extract_triangle_mesh()
    mesh.compute_vertex_normals()

Now I would like to crop the object of interest programmatically using a `2d mask` of the object with a given `intrinsics` and `cam_pose`. Is there any way to go from the `2d mask` to cropping the mesh at properly given the `camera pose` ?  

Any suggestion to solve this will be highly appreciated.

**Comment by qianyizh** [comment]
@pavan4 If you are using C++ interface and your mask is a rectangle or a polygon, use <Visualization/Utility/SelectionPolygon.h>, ``CropInPolygon()`` and ``CropInRectangle()`` is the easiest solution.

If you are using python interface, or if you are dealing with a rather random mask, you can project all ``vertices`` in mesh and record an index array for those falling inside the mark. Then call function ``select_down_sample()`` for triangle meshes.
