### ISSUE TITLE
Visualise point clouds in Jupyter notebooks

### ISSUE THREAD

**Issue by nicolas-chaulet** [IntelVCL/Open3D#537]
I am currently using the python bindings of open3d within Jupyter notebooks and it's been great so far. The `draw_geometries` function does not do anything at the moment when executed inside a notebook, is there a way to create a visualization window within the notebook? It sounds like a big ask, but maybe there is a simple solution?

**Comment by syncle** [comment]
This is Related to #376. To my knowledge, one plausible solution is benchmarking https://github.com/daavoo/pyntcloud that uses java + html. We are also welcome if you have any suggestion or willingness to contribute for this. :)

**Comment by nicolas-chaulet** [comment]
Hi @syncle thanks for your reply! I missed that issue sorry about that, I'll close the issue. I found another library though that seems quite good and pretty active: [](https://github.com/maartenbreddels/ipyvolume).
