### ISSUE TITLE
inlier_rmse_ and fitness_ should always return 0.0 in fast registration?

### ISSUE THREAD

**Issue by rafael2k** [IntelVCL/Open3D#538]
Hi,
Should the fast registration result always come with zeroed values of inlier_rmse_ and fitness_?

**Comment by syncle** [comment]
It is not because points are not exactly matching. If there is no correspondences, RMSE could be 0 as an output.

**Comment by qianyizh** [comment]
Close as there is an answer. Feel free to reopen it.
