### ISSUE TITLE
Multiple packages on pypi

### ISSUE THREAD

**Issue by tpet** [IntelVCL/Open3D#542]
There are multiple seemingly same packages on pypi, namely
https://pypi.org/project/open-3d/
https://pypi.org/project/open3d-official/
https://pypi.org/project/open3d-original/
https://pypi.org/project/open3d-python/
https://pypi.org/project/py3d/
Can somebody, please, clarify what is the reason for this and what are the differences?
It seems to me that a small cleanup might help.

**Comment by takanokage** [comment]
We'd be happy to settle for just one: `open3d`.
As you mentioned, there's multiple advantages to a single package and we acknowledge that.
However we've had one guy effectively hijack the open3d project and claiming it as his work including all the source code and the pypi name. You will notice issue [#4243](https://github.com/pypa/warehouse/issues/4243). In fact this has been going on for ~4-5 months and there's no clear eta for us getting our name back.

We're open to suggestions.

**Comment by qianyizh** [comment]
Yeah, there are some historical issues. We are aware of this and in the process of fixing it. But it takes time because there are 3rd parties involved...

**Comment by tpet** [comment]
Thanks for having clarified this! Good luck in claiming the `open3d` package name. It's an awesome library, I was looking for something like this for quite a long time!

**Comment by qianyizh** [comment]
Closing since we are actively working on it. Feel free to reopen.
