### ISSUE TITLE
Incorrect default install location on linux

### ISSUE THREAD

**Issue by anuppari** [IntelVCL/Open3D#550]
**Describe the bug**
The default value for `INSTALL_CMAKE_DIR` is set to `lib/CMake/Open3D`, but according to the [cmake docs](https://cmake.org/cmake/help/v3.5/command/find_package.html?highlight=i), that is not one of the default search locations for `find_package`, so other packages that depend on Open3D can't find it without explicitly giving the install location. Changing `INSTALL_CMAKE_DIR` to `lib/cmake/Open3D` (lower case cmake) fixes this.

**To Reproduce**
Make and install Open3D using the provided instructions. Then create a new package that depends on Open3D, and try to find it in cmake using `find_package(Open3D REQUIRED)`

**Expected behavior**
CMake should find Open3D at it's default install location

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04 64 bit
 - Open3D version:  [commit d356cfe](https://github.com/IntelVCL/Open3D/commit/d356cfee7adde26b813cb8098566e344e9645bb5)

**Comment by yxlao** [comment]
This is now addressed in #568. Thanks for the bug report @anuppari!
