### ISSUE TITLE
Selection of filters

### ISSUE THREAD

**Issue by nicolas-chaulet** [IntelVCL/Open3D#559]
Hi,
I see that you are supporting voxel grid downsizing, uniform downsizing and selective downsampling, do you plan on implementing more filters such as 
- statistical outliers (points that are further away from their neighbours) 
- radius search (points that have less than n neighbors in a sphere of radius r)

Thanks!

**Comment by syncle** [comment]
Hi @nicolas-chaulet. "radius search" seems straight-forward to implement, but I am not sure the difference between "radius search" and "statistical outliers". Can you clarify bit more?

**Comment by syncle** [comment]
Yes. That would be very useful.

**Comment by syncle** [comment]
Closing as this have addressed in #565.
