### ISSUE TITLE
Pan Mouse Wheel Press

### ISSUE THREAD

**Issue by kevinzakka** [IntelVCL/Open3D#560]
First of all, thanks for this amazing open source library!

I was wondering if it would it be possible to implement panning using the mouse wheel press. It's currently really hard to zoom in on some places due to how restricted the viewer is. It would be nice to introduce an option when we can "walk/translate" in a direction using the wheel.

Thanks!

**Comment by syncle** [comment]
This issue have not been answered yet. @qianyizh: could you comment on this?

**Comment by qianyizh** [comment]
I mean, sure, it can be implemented. @syncle up to you if you wanna add it.

**Comment by kevinzakka** [comment]
@syncle @qianyizh Thanks guys, it's pretty useful when viewing/debugging pointclouds in the `view_geometries` window. Some places become unreachable or hard to angle because this feature is lacking.

**Comment by syncle** [comment]
Hi @kevinzakka. I am revisiting this. Could you explain more on the request? Is that different from ``ctrl  + mouse drag``?

**Comment by kevinzakka** [comment]
Hey @syncle. If you use meshlab, it's the same action you do when you lick the scroll wheel and move the focal center of the camera.

**Comment by kevinzakka** [comment]
@syncle It seems it's `control + shift + click` on macOS!

**Comment by syncle** [comment]
Got it. Let me work on this.
