### ISSUE TITLE
undefined reference to `vtable for open3d::PointCloud'

### ISSUE THREAD

**Issue by Vincent-2017** [IntelVCL/Open3D#561]
undefined reference to `vtable for open3d::PointCloud'

**Comment by Vincent-2017** [comment]
class rsdevice
{
public:
    rs::context ctx;
    rs::device * dev;
    int devCount;
    std::shared_ptr<open3d::PointCloud> pointcloud;
...

#include "rsdevice.h"

rsdevice::rsdevice():
    pointcloud(new open3d::PointCloud())
{

}

When I want to get the pointcloud from realsense, the problem arises.

**Comment by qianyizh** [comment]
Can you paste the code in code format?
I.e., quote with a pair of ```

**Comment by syncle** [comment]
Closed for now due to inactivity. @Vincent-2017: Feel free to reopen it :)
