### ISSUE TITLE
Segmentation fault when read binary feature

### ISSUE THREAD

**Issue by shoKagami** [IntelVCL/Open3D#562]
I am trying to read and write FPFH feature using function below:
https://github.com/IntelVCL/Open3D/blob/0bf814dd5022003652b7c202fcebc4c8a7136754/src/IO/ClassIO/FeatureIO.h#L34-L40

When I write FPFH feature to binary using function ``WriteFeature``, This function returned true(file extension is ``.bin``). So I success to write feature to binary file. But when I read this binary file, I face this error:
```
[1]    14038 segmentation fault
``` 

The part of the code where the error occurred is as follows:
```cpp
std::shared_ptr<Feature> ReadFPFHFeature(const char* file_name){
 std::shared_ptr<Feature> pcd_fpfh;
 ReadFeature(file_name, *pcd_fpfh);
 return pcd_fpfh;
}
```

I also face this error, when I read testData below:
https://github.com/IntelVCL/Open3D/blob/master/examples/TestData/Feature/cloud_bin_0.fpfh.bin

Mac OSX High Sierra 10.13.6

**Comment by qianyizh** [comment]
@syncle can you take a look?

**Comment by shoKagami** [comment]
Sorry, It's my mistake.
I should declare new to allocate memory.

I fix the code above like:
```cpp
std::shared_ptr<Feature> ReadFPFHFeature(const char* file_name){
 std::shared_ptr<Feature> pcd_fpfh(new Feature);
 ReadFeature(file_name, *pcd_fpfh);
 return pcd_fpfh;
}
```

So I close this issue.
