### ISSUE TITLE
Headless rendering docs & ENABLE_HEADLESS_RENDERING vs HEADLESS_RENDERING

### ISSUE THREAD

**Issue by adamlofts** [IntelVCL/Open3D#578]
The headless rendering docs http://www.open3d.org/docs/tutorial/Advanced/headless_rendering.html say to use ENABLE_HEADLESS_RENDERING to enable headless rendering. This is consistent with the root cmakefile.

https://github.com/IntelVCL/Open3D/blob/5ca0056aaff92b06c0003a80ee90f99cdae643fb/CMakeLists.txt#L55.

However the included glfw cmakefile expects a parameter called HEADLESS_RENDERING https://github.com/IntelVCL/Open3D/blob/5ca0056aaff92b06c0003a80ee90f99cdae643fb/3rdparty/GLFW/CMakeLists.txt#L29

So currently to build headless rendering you need to specify _both_ on the build command.
```
cmake \
        -DENABLE_HEADLESS_RENDERING=ON \
        -DBUILD_GLEW=ON \
        -DBUILD_GLFW=ON \
        -DBUILD_SHARED_LIBS=ON \
        -DHEADLESS_RENDERING=ON \
``

**Comment by qianyizh** [comment]
@syncle can you comment on this?

**Comment by syncle** [comment]
The cmake flag for headless rendering were diverged. I submitted a PR to fix this.
