### ISSUE TITLE
RGB(depth and color aligned) and depth images are unable to register 

### ISSUE THREAD

**Issue by SriGanesh130** [IntelVCL/Open3D#583]
I did the calibration and i got depth image,  depth and rgb aligned image(RGB) which means both these images have the same resolution. I given this images as input to reconstruction system but it is not reconstructing the scene.I am thinking that the given color image is not pure color image from kinect its a rgb and depth aligned image, so it is the problem?...
if it is then how to take the color and depth(aligned) images from kinect v2... 
please help me to solve this issue..
thanks.

**Comment by syncle** [comment]
Hi @SriGanesh130, for debugging, I recommend you to visualize your dataset like this example: http://open3d.org/docs/tutorial/Basic/rgbd_images/redwood.html.

**Comment by SriGanesh130** [comment]
Thanks for reply,
  How to create dataset like this with kinect v2

**Comment by syncle** [comment]
It is just pair of 8bit color and 16bit depth image. In case of Redwood dataset, the depth is discrete, 1000 means 1000mm = 1m. Please use any APIs for Kinect to record synchronized, and registered color depth image pair.

**Comment by SriGanesh130** [comment]
thanks @syncle 
i used ROS kinect_iai2 but it is not giving accurate results like redwood dataset. suggest me any other API which gives good results for kinect v2

**Comment by SriGanesh130** [comment]
Thanks @syncle 
these are my sample image which are used for reconstruction. But unfortunately they are not reconstructing the scene.
.ply file is not generating in fragments folder while running reconstruction.
![0000_color](https://user-images.githubusercontent.com/42513897/46009002-e8bef680-c0db-11e8-93be-338433a7dcfb.jpg)
![0000_depth](https://user-images.githubusercontent.com/42513897/46009007-ed83aa80-c0db-11e8-9b36-a6a0fe105bff.png)

**Comment by LittleLampChen** [comment]
Can open3d automatically align rgb and depth image?

**Comment by mmaslennikov** [comment]
In my case, this code is working for the RealSense D435 camera:

`# o3d.camera.PinholeCameraIntrinsic(width, height, fx, fy, cx, cy)`
`self.intrinsic = o3d.camera.PinholeCameraIntrinsic(1280,720,920.055,920.343,639.697,357.995)`
`color_depth = [[o3d.io.read_image(path[i]) for i in range(2)] for path in path_rgbd]`
`rgbds = [o3d.geometry.RGBDImage.create_from_color_and_depth(
                p[0], p[1], depth_trunc=4.0, convert_rgb_to_intensity=False) for p in color_depth]`
`point_clouds = [o3d.geometry.PointCloud.create_from_rgbd_image(r, self.intrinsic) for r in rgbds]`
`o3d.visualization.draw_geometries(point_clouds)`

I got fx, fy, cx, cy from the camera intrinsic matrix [A](https://docs.opencv.org/2.4/modules/calib3d/doc/camera_calibration_and_3d_reconstruction.html) and provide the paths to aligned color and depth images.

Some note to Open3d authors: could you kindly consider putting the example of setting the intrinsic 
`# o3d.camera.PinholeCameraIntrinsic(width, height, fx, fy, cx, cy)`
into your [tutorials](http://www.open3d.org/docs/release/tutorial/Basic/rgbd_images/index.html) or [documentation](http://www.open3d.org/docs/release/python_api/open3d.io.read_pinhole_camera_intrinsic.html)?
