### ISSUE TITLE
unable to construct scene

### ISSUE THREAD

**Issue by SriGanesh130** [IntelVCL/Open3D#588]
While reconstruting, the ply files in fragments and scene folder are not generating for my dataset but when i tried with the your dataset it is generating .... but both datasets(yours and mine) are running same(showing no errors) in terminal but scene is not constructing.
These are my sample datasets(color and depth)::
![0000_color1](https://user-images.githubusercontent.com/42513897/46060900-56256280-c182-11e8-8588-d58ad1d7806f.jpg)
![0001_depth](https://user-images.githubusercontent.com/42513897/46060917-676e6f00-c182-11e8-809e-083083a06149.png)

**Comment by syncle** [comment]
Please visualize the RGBD image as a point cloud. You can follow this tutorial http://open3d.org/docs/tutorial/Basic/rgbd_images/redwood.html and replace camera intrinsic accordingly.

**Comment by SriGanesh130** [comment]
Thanks @syncle 
i got it
