### ISSUE TITLE
Can index-adjacent nodes connected requirement for GlobalOptimization be removed?

### ISSUE THREAD

**Issue by dmontagu** [IntelVCL/Open3D#600]
**Is your feature request related to a problem? Please describe.**
I am trying to perform global optimization on a PoseGraph with poses for which not all index-neighboring nodes have a connecting edge, but I am being told that my pose graph is invalid (see here:
https://github.com/IntelVCL/Open3D/blob/0667179c2d69f3e191104b6f70378b4dee6f406a/src/Core/Registration/GlobalOptimization.cpp#L387).

I'm not sure I understand the rationale for why a PoseGraph needs index-adjacent nodes to be connected for global optimization. In particular, if I understand correctly, the real requirement is instead that the PoseGraph has a single connected component -- is that right? (Maybe there is something deeper in the optimization that depends on adjacent nodes being connected?) If so, it would be great if there was a way to either disable the check that index-adjacent nodes are connected, or (better yet) if the validity check actually just checked that the graph was connected.

I can see the benefit of simplicity/ease of implementation given that the index-adjacent-nodes-connected requirement is met in most straightforward applications of RGBD odometry, but I think there are many scenarios where it could be useful to drop this requirement (for example, if using multiple cameras).

**Describe the solution you'd like**
Ideally, the validity check would just check that the graph was connected, rather than that index-adjacent nodes are connected. Perhaps simpler, if there was just a way to disable the node-adjacency validity check, that would suffice.

**Describe alternatives you've considered**
So far, I've just reordered the nodes and added additional edges as necessary (even if they are bad) to ensure adjacent nodes are connected, but it feels like this shouldn't be necessary.

**Additional context**
One thing I haven't tried is adding edges to address the adjacency constraint, and just setting their confidence to zero -- would this basically be equivalent to removing the validity check?

**Comment by syncle** [comment]
That's good point. Checking adjacent node was added to perform sanity check for reconstruction system, but it is not good fit for general use case as you mentioned. How about removing this check and replace it with a new check that can identify an isolated node? I am fine with this change, and would be grateful if you are willing to submit PR regarding this. :)

**Comment by qianyizh** [comment]
@dmontagu I agree with you. I think the current implementation has a loophole there. When we implemented it, we only considered a simple use case - basically the one that's described in the "robust reconstruction" paper.

I agree with your proposal too. It addresses the loophole.

Only one thing that's not clear to me: how do you create the initialization of the optimization if the strong edges do no form a disconnected component?

**Comment by dmontagu** [comment]
@qianyizh Based on your comment and reading through the implementation a little more, I think there could be problems if so many of the weak edges get pruned that the graph becomes disconnected, or if the line process weights update in such a way that any weak edges that could keep the graph connected have weight 0.

However, in practice, with enough "good" weak edges keeping the graph connected, the reconstruction seems to work as desired. I'd have to dig deeper into the implementation details to be able to more adequately address your question about how the optimization is initialized, but I've been using https://github.com/IntelVCL/Open3D/pull/601 for a little while now with posegraphs that are not connected by strong edges (but are connected by weak edges), and have had no issues.

Considering the master branch implementation is also not checking for "strong" edges though, I stand by my original proposal of just warning if the "strong edge" part of the posegraph is not connected but the weak edge part is. I'll try to update the pull request with this modification shortly.

**Comment by qianyizh** [comment]
@dmontagu thanks for the contribution. I agree with your points. This is an important step towards a solution for the topology check of the pose graph - although a complete solution may need more work and more thorough research. I merged #601 and will close this issue for now. Feel free to reopen it if anyone finds any problem with this.
