### ISSUE TITLE
Statistical oulier removal and Radius oulier removal not working in open3D under conda

### ISSUE THREAD

**Issue by guyrap** [IntelVCL/Open3D#613]
Hi,
I'm running the tutorial example 'point_cloud_outlier_removal.py'.
The script fails when trying to run the Statistical outlier removal and Radius outlier removal.

I'm using open3D with conda (latest version) with python 3.6.
I'm getting the following error code:
NameError: name 'statistical_outlier_removal' is not defined

Is it possible that this two functions are not part of the conda open3D version?
Best,
Guy

**Comment by yxlao** [comment]
Hi @guyrap, `statistical_outlier_removal` was recently added by https://github.com/IntelVCL/Open3D/pull/565, so it's not part of the v0.3.0 release. If you'd like to try it out, we'd recommend building from source.

**Comment by guyrap** [comment]
@yxlao - thank you!
Guy
