### ISSUE TITLE
Anyway to paint the point cloud with different colors?

### ISSUE THREAD

**Issue by LLDavid** [IntelVCL/Open3D#614]
I only find "paint_uniform_color ()" for painting , but I want to paint different points with different colors. Anyone knows how to do it? Thanks

**Comment by yxlao** [comment]
We can directly assign a numpy array to `open3d.PointCloud.colors`, see http://www.open3d.org/docs/tutorial/Basic/working_with_numpy.html#working-with-numpy, e.g.

```python
pcd = PointCloud()
pcd.points = Vector3dVector(np_points)
pcd.colors = Vector3dVector(np_colors)
```

**Comment by LLDavid** [comment]
> pcd.colors = Vector3dVector(np_colors)

@yxlao Thanks! Exactly what I need.

**Comment by GnawXam** [comment]
I created my own array of colors based on 
http://www.open3d.org/docs/python_api/open3d.geometry.PointCloud.html?highlight=pointcloud

`Type: | float64 array of shape (num_points, 3), range [0, 1] , use numpy.asarray() to access`

But when I use draw_geometries() to visualize my point cloud I still get the default red blue colors in x y or z direction. Does someone have a concrete example? Not sure what I'm missing.

**Comment by ofalco76** [comment]
Hi guys, How can i paint a single Polygon inside from a polygon list with different colors each?

**Comment by ofalco76** [comment]
How can I paint inside a polygon?, thanks in advance

**Comment by LinoComesana** [comment]
> I created my own array of colors based on
> http://www.open3d.org/docs/python_api/open3d.geometry.PointCloud.html?highlight=pointcloud
> 
> `colors Type: | float64 array of shape (num_points, 3), range [0, 1] , use numpy.asarray() to access`
> 
> But when I use draw_geometries() to visualize my point cloud I still get the default red blue colors in x y or z direction. Does someone have a concrete example? Not sure what I'm missing.

Check the values of the color array. Open3D works with colors in the [0,1] range and not in the [0,255] interval. I had the same problem but normalizing all values in the color array solved my particular issue, maybe is your case too.

**Comment by sharoseali** [comment]
HI i have point clouds in ply format and i up sampled them. After up sampling, the point cloud loose color information. Later i get colors  numpy array of normal point cloud and also up sampled it. Like  I create new numpy array and (in my case for up sampling factor 4 ). I put same RGB value for next 4 point clouds. I visualize my numpy arrays . Everything seems to be fine , but when I render the new point cloud. The color information is still not well. Anyone help me. Below is my code

![normal](https://user-images.githubusercontent.com/19869426/139534971-4c036f51-c109-46a5-9510-bb8637930ea9.PNG)
![upSampled](https://user-images.githubusercontent.com/19869426/139534982-b2fe0da8-d1a7-41bf-b42b-b63c24967f7f.PNG)
![image](https://user-images.githubusercontent.com/19869426/139535193-be7f3a7c-57e9-4893-b9ac-def4bb559ab5.png)


```
new_color = np.zeros(np.asarray(pcd_upsampled.points).shape)
new_color = upsampling_numpyRGB(normal_pointCloud.colors, new_color)
pcd_upsampled.colors = o3d.utility.Vector3dVector(new_color)
o3d.visualization.draw_geometries([pcd_upsampled])
```

**Comment by floridak** [comment]
> We can directly assign a numpy array to `open3d.PointCloud.colors`, see http://www.open3d.org/docs/tutorial/Basic/working_with_numpy.html#working-with-numpy, e.g.
> 
> ```python
> pcd = PointCloud()
> pcd.points = Vector3dVector(np_points)
> pcd.colors = Vector3dVector(np_colors)
> ```

if i had  those lines : plane = np.concatenate([point, [cluster_size]])
                                  planes_out.append(plane)
                                  planes_out = np.array(planes_out) 
so basically a lot of planes, how would I color them with different color?  can you plzz have a look? thanks in advance

**Comment by INF800** [comment]
> We can directly assign a numpy array to `open3d.PointCloud.colors`, see http://www.open3d.org/docs/tutorial/Basic/working_with_numpy.html#working-with-numpy, e.g.
> 
> ```python
> pcd = PointCloud()
> pcd.points = Vector3dVector(np_points)
> pcd.colors = Vector3dVector(np_colors)
> ```

Do we have something like `pcd.labels` as well. I saw `labels` somewhere sometime back

**Comment by LinoComesana** [comment]
> > We can directly assign a numpy array to `open3d.PointCloud.colors`, see http://www.open3d.org/docs/tutorial/Basic/working_with_numpy.html#working-with-numpy, e.g.
> > ```python
> > pcd = PointCloud()
> > pcd.points = Vector3dVector(np_points)
> > pcd.colors = Vector3dVector(np_colors)
> > ```
> 
> Do we have something like `pcd.labels` as well? I saw `labels` somewhere sometime back

It does not seems to exist that feature. I am used to store every possible data as numpy arrays in the following form:

`
import open3d as o3d
point_cloud = o3d.geometry.PointCloud()
point_cloud.points = o3d.utility.Vector3dVector(array_of_points) # array_of_points.shape = (N,3)
point_cloud.colors = o3d.utility.Vector3dVector(array_of_colors) # array_of_colors.shape = (N,3)
point_cloud.normals = o3d.utility.Vector3dVector(array_of_normals) # array_of_normals.shape = (N,3)
`
where `array_of_points`, `array_of_colors` and `array_of_normals` are numpy arrays stored previously in your code.
In case you want to visualize the point cloud as a function of a fourth feature like the "label per point" you can store your labels in a previously defined numpy array (`array_of_labels`) and make the following (example of 2 label classes: label "0" and label "1"):

`
indexes_label_0 = np.where(array_of_labels == 0)
indexes_label_1 = np.where(array_of_labels == 1)
array_of_colors = np.zeros(shape=array_of_points.shape)
array_of_colors[indexes_label_0] = [0,1,0] # Points with label 0 are colored in Green.
array_of_colors[indexes_label_1] = [1,0,0] # Points with label 0 are colored in Red.

import open3d as o3d
point_cloud = o3d.geometry.PointCloud()
point_cloud.points = o3d.utility.Vector3dVector(array_of_points) # array_of_points.shape = (N,3)
point_cloud.normals = o3d.utility.Vector3dVector(array_of_normals) # array_of_normals.shape = (N,3)
point_cloud.colors = o3d.utility.Vector3dVector(array_of_colors) # array_of_colors.shape = (N,3)

o3d.visualization.draw_geometries([point_cloud])

`

**Comment by ShaoxiongYao** [comment]
> > I created my own array of colors based on
> > http://www.open3d.org/docs/python_api/open3d.geometry.PointCloud.html?highlight=pointcloud
> > `colors Type: | float64 array of shape (num_points, 3), range [0, 1] , use numpy.asarray() to access`
> > But when I use draw_geometries() to visualize my point cloud I still get the default red blue colors in x y or z direction. Does someone have a concrete example? Not sure what I'm missing.
> 
> I have got the same issue here

Another probability is that the size of colors and points are not matched. Open3d does not check the shapes when you use `pcd.colors` to assign colors. If the shapes are matched, you may find `pcd.has_colors()` returns True.
