### ISSUE TITLE
is changing color for individual points possible?

### ISSUE THREAD

**Issue by happyBear9** [IntelVCL/Open3D#621]
Hi, Im trying to segment a pcd file but `paint_uniform_color` function seems to change the color of all points in the pointcloud. Is it possible to change color of individual points? 

If not, is it possible to remove specific points from point cloud so i can visualize segmented points as separate pointclouds? Thank you

**Comment by syncle** [comment]
Yes for the both question. 

Please see [this answer](https://github.com/IntelVCL/Open3D/issues/614) to assign color for each point. In the similar manner, you can make a new ``PointCloud()`` with arbitrary points.

**Comment by happyBear9** [comment]
Thanks a lot! Sorry for duplicate.
