### ISSUE TITLE
Issue for import in python. No module named open3d

### ISSUE THREAD

**Issue by ljc19800331** [IntelVCL/Open3D#624]
Hello open3d authors, 

I have successfully compiled open3d from scratch and used for python before I reinstalled my ubuntu 16.04  system. After I reinstalled the system, I found the notice "no module named open3d" after I compile open3d with python binding with the command "-DPYTHON_EXECUTABLE:FILEPATH=<path-to-python-executable> ..". I checked multiple times but could not figure out the solution. Any methods I could check if I successfully link the open3d to my python interpreter? Thanks.

**Comment by yxlao** [comment]
Please see https://github.com/IntelVCL/Open3D/issues/420#issuecomment-430829690, especially https://github.com/IntelVCL/Open3D/pull/604#issue-221284415. 

In short, you don't need to run `make install` at all to install python binding. Now, inside your virtualenv, run:
```
make install-pip-wheel
```

We're working on the documentation for the new way of building python package from source.

**Comment by ljc19800331** [comment]
Thanks for your comment.

**Comment by versatran01** [comment]
I tried 

sudo make install-pip-package

and still get no module named open3d. The command runs without error though.

**Comment by yxlao** [comment]
We do not need to use `sudo` unless we need to install to the system python -- e.g. in virtualenv, no sudo is required.

If there are issues, try splitting it into multiple steps
```
# Create Python package in build/lib/python_package
make python-package

# Create pip wheel in build/lib/python_package/pip_package
# After this command, check if a *.whl file is in build/lib/python_package/pip_package
# and install the wheel manually
make pip-package
```

See: http://www.open3d.org/docs/compilation.html#install-open3d-python-package

**Comment by HeuMindFusion** [comment]
error:No module named 'open3d_tutorial'
