### ISSUE TITLE
Reconstruction system error

### ISSUE THREAD

**Issue by SriGanesh130** [IntelVCL/Open3D#629]
Trying to reconstruct using color and depth images taken from real sense d435 camera but the result is like this...
![room](https://user-images.githubusercontent.com/42513897/47433833-d5787700-d7be-11e8-97c2-dfa5e200a672.png)

I am taking data using recorder_realsense.py and collecting data by holding sensor with hand. But it is not giving any satisfactory result. suggest me to how to collect data and proceed to get the better reconstruction of the object.[Note: I am using python]
I am just following the reconstruction system and not using any other algorithms.
And also I need reconstruct single object in the room but it is giving the entire room.

**Comment by syncle** [comment]
Here is a list:
- There is a tool for analyzing individual fragments. Try 
```
cd ReconstructionSystem
python debug/visualize_fragments.py 
```
and see if all of the fragments are looking good.
- If you found some fragments are breaking, see corresponding frames what's happening (maybe try capture image sequences slowly).
- Are you using rotation table or something? In that case, see the discussions on [here](https://github.com/IntelVCL/Open3D/issues/231#issuecomment-403119855).
- Try to visualize your [depth map as a point cloud form](http://open3d.org/docs/tutorial/Basic/rgbd_images/redwood.html) and check if it is reasonable. Flat wall should be flat. Check whether the distance depths are clipped away.

**Comment by yxlao** [comment]
Also see this demo as a reference: 
[![IMAGE ALT TEXT](http://img.youtube.com/vi/AD0zp5zoA3w/0.jpg)](http://www.youtube.com/watch?v=AD0zp5zoA3w "Open3D Reconstruction Demo")
https://www.youtube.com/watch?v=AD0zp5zoA3w
