### ISSUE TITLE
[Question] Normal Estimation

### ISSUE THREAD

**Issue by kevinzakka** [IntelVCL/Open3D#635]
Hey guys,

Am wondering if there are robust strategies to determine a good set of hyperparameters for the normal estimation algorithm. Specifically, how can I couple the voxel downsampling, number of neighbors and radius size to eliminate outlier normals and return a the most common normal (i.e. mode).

Thanks

**Comment by syncle** [comment]
HI @kevinzakka. I recommend to use 1:2 ratio for the point cloud downsampling and normal estimation.  For example, if you downsample your point cloud using 5cm voxels, you can use 10cm radius for the normal estimation. You can [refer this tutorial](http://open3d.org/docs/tutorial/Basic/pointcloud.html#vertex-normal-estimation). 

However, this ratio is purely based on my experience. It may not the best number for the noisy point clouds. It is open question how to evaluate noisiness of the point cloud though.
