### ISSUE TITLE
  black block occurs in visualizer

### ISSUE THREAD

**Issue by jwm111** [IntelVCL/Open3D#640]
when i run the demo /Python/Tutorial/Basic/visualization.py  and spin the pointcloud , the visualizer  seems discontinuous and black block occurs in some frames ， just like following images  。
![screenshot from 2018-10-26 17-08-12](https://user-images.githubusercontent.com/19990848/47557223-b73b8400-d942-11e8-9e3d-ce0d92e91358.png)
![screenshot from 2018-10-26 17-08-25](https://user-images.githubusercontent.com/19990848/47557238-c15d8280-d942-11e8-98cb-b2b04cb5a38e.png)

does anyone knows the real  reasons and how to slove this problem?

**Comment by syncle** [comment]
I never saw this, but thanks for informing us. Can you tell your environment and installation method? One quick option is to build from source with all the dependences included in Open3D.

**Comment by jwm111** [comment]
> I never saw this, but thanks for informing us. Can you tell your environment and installation method? One quick option is to build from source with all the dependences included in Open3D.

thanks for your reply . my environment is ubuntu16.04 . I install Open3D from source according to the  tutorial. But the problem still remains whether dependencies are installed  firstly or built from source . . And I guess it's about  version conflict. I try these commands,then the problem are solved:
-     sudo apt-get install build-essential libgl1-mesa-dev
-     sudo apt-get install freeglut3-dev
-     sudo apt-get install libglew-dev libsdl2-dev libsdl2-image-dev libglm-dev libfreetype6-dev
