### ISSUE TITLE
Some questions about Fast Global Registration ... 

### ISSUE THREAD

**Issue by ghost** [IntelVCL/Open3D#644]
Hello, Thank you for your work about FGR.
Recently, I am tring to use the FGR in my dataset, but I can not get the correct results. I have tuned all the parameters, but it does not work. The following are the sceenshots of my data.
![1](https://user-images.githubusercontent.com/34222433/47613838-f7c90800-dad0-11e8-834a-29b301755d63.PNG)
![1](https://user-images.githubusercontent.com/34222433/47613844-0dd6c880-dad1-11e8-992a-c9e4bb101d8f.PNG)
The following is the pointcloud files. 
https://raw.githubusercontent.com/zhuangleilei/hello-world/master/pointcloud1.rar
https://raw.githubusercontent.com/zhuangleilei/hello-world/master/pointcloud2.rar
Could you get the correct results? Or the FGR can be only used in some special cases?

**Comment by syncle** [comment]
For the quick reference, please have a look [this](https://github.com/IntelVCL/FastGlobalRegistration/blob/master/troubleshooting.md)

**Comment by zhuangleilei** [comment]
I have checked the ratio, and it is right. Could you test my datasets? I need your help. Thank  you! @syncle

**Comment by syncle** [comment]
![image](https://user-images.githubusercontent.com/18297113/47687022-5ce93000-db9b-11e8-9438-2bfadf8b2369.png)
I tried examples/Python/Advanced/global_registration.py with voxel size 1.0, but I haven't got reasonable result using FGR yet.

**Comment by zhuangleilei** [comment]
I have tried the GR in my datasets, and get the same result. But the method of GR is time-consuming, I want to register the pointclouds quickly. 
That is to say, Is FGR not  suited for my datasets? Thank you very much for your reply. @syncle

**Comment by syncle** [comment]
@zhuangleilei Could also try with [original FGR code](https://github.com/IntelVCL/FastGlobalRegistration)? When I fused the FGR into Open3D, I did some modifications, so that might cause some issue.
