### ISSUE TITLE
organised Pointcloud, RGBD....?

### ISSUE THREAD

**Issue by lukaspistelak** [IntelVCL/Open3D#647]
Hi
I am new into pointclouds technology and I really like your library.

Point Cloud data type object is obviously unorganized In this library, what I need is probably organized point cloud

My problem:

I have 2 frames of the same object taken by a different angle, So i have fór every frame organized RGB and XYZ values

I need to merge this 2 frames, so I need on output :

frame with organized RGB values and corresponding XYZ values, with this data i have to work as standard image-processing data, so I need the most accurate method

One Way is Make Point clouds,
 do ICP registration,
 but How can I get image data with height And width and corresponding XYZ values
From output Point cloud!??

or exists another effective way how can I do it?

Thanks

**Comment by syncle** [comment]
Hi, luka, if you can express your xyz data as a depth map with intrinsic matrix, I think you can try [RGBD Odometry](http://open3d.org/docs/tutorial/Basic/rgbd_odometry.html#compute-odometry-from-two-rgbd-image-pairs).

**Comment by syncle** [comment]
Closed due to inactivity. @lukaspistelak: feel free to reopen this if necessary :)

**Comment by lukaspistelak** [comment]
Hi syncle thanks:
i do this:

1.First Of All I do rgbd registration

So I get the transformation affinity Matrix and some another all info

2. Initialize The Pose graph

To get to U,V position in target frame, 
Where begin the source frame

Since I have only one image rgbd pair
 And  frames are taken horizontally

I think It's Easy and
I don't think that I need to optimise graph, but I don't know

So I don't know how to get this UV index position


of course my brutal own solution is iterate over this array and the with some threshold find the first matching XYZ point but I want to use the open 3d methods


III.:

Transform depth image to x y z Space thanks Camera interestings

And  transform source frame with transformation matrix to target frame plane space


4:

Creat final RGBD frame 

When I get UV index position I can append  source Frame Over the Target frame and that's it


Here is Code sample::

def Run_Merge_Process(self,a_rgb, a_depth, b_rgb, b_depth, cx, cy, fx, fy):        
        
        #1: I expect this format!:  ,height,witdh    ICP:           
       
        [success, transform_matrix, info,source_rgbd_image,target_rgbd_image]=self.icp_RGBD(a_rgb, a_depth, b_rgb, b_depth)    
        
        set_verbosity_level(VerbosityLevel.Error)
       
        print("info",info) #OK!''or get u,v of matching point HERE????
        
        
        
        #2: ITS OK? pose graph to get u,v of matching point :
        
        pose_graph = PoseGraph()
        trans_odometry = np.identity(4)
        
        pose_graph.nodes.append(PoseGraphNode(trans_odometry))        
        
        trans_odometry = np.dot(transform_matrix, trans_odometry)
        
        trans_odometry_inv = np.linalg.inv(trans_odometry)
        
        pose_graph.nodes.append(PoseGraphNode(trans_odometry_inv))        
        pose_graph.edges.append(  PoseGraphEdge(0, 0, transform_matrix, info, uncertain = False))
        
        
        pose_graph=self.run_posegraph_optimization(pose_graph)
        
        print("pose_graph node : u,v points in target frame:",pose_graph.edges[0].pose,np.linalg.inv(pose_graph.nodes[1].pose))
        
        
        
        
        #3:convert to XYZ space
        source_depth_n_array=np.asarray(source_rgbd_image.depth)        
        source_rgb_n_array=np.asarray(source_rgbd_image.color)           
        
        source_depth_xyz=self.create_XYZ_image(source_depth_n_array,cx, cy, fx, fy)
        
        
        target_rgb_n_array=np.asarray(target_rgbd_image.color) 
        target_depth_n_array=np.asarray(target_rgbd_image.depth)                      
        
        target_depth_xyz=self.create_XYZ_image(target_depth_n_array,cx, cy, fx, fy) 
        
        
        #transform source to target space:
        t_source_xyz=self.transform_xyz_image_to_target_space(source_depth_xyz, transform_matrix)
        
        
        
       # 4: create new image xyz arraya and append target and source_n_arrays to this array by u,v positions:

**Comment by lukaspistelak** [comment]
Thanks sincle:

1.First Of All I do rgbd registration
So I get the transformation affinity Matrix and some another all info


2. Initialize The Pose graph
To get to U,V position in target frame, 
Where begin the source frame
Since I have only one image rgbd pair
 And  frames are taken horizontally

I think It's Easy and I don't think that I need to optimise graph, but I don't know
So I don't know how to get this UV index position
of course my brutal own solution is iterate over this array and the with some threshold find the first matching XYZ point but I want to use the open 3d methods


III.:
Transform depth image to x y z Space thanks Camera interestings.
And  transform source frame with transformation matrix to target frame plane space


4:
Creat final lgbt frame
When I get UV index position I can append  source Frame Over the Target frame and that's it

Here is Code sample::

def Run_Merge_Process(self,a_rgb, a_depth, b_rgb, b_depth, cx, cy, fx, fy):        
        
        #1: I expect this format!:  ,height,witdh    ICP:           
       
        [success, transform_matrix, info,source_rgbd_image,target_rgbd_image]=self.icp_RGBD(a_rgb, a_depth, b_rgb, b_depth)    
        
        set_verbosity_level(VerbosityLevel.Error)
       
        print("info",info) #OK!''or get u,v of matching point HERE????
        
        
        
        #2: ITS OK? pose graph to get u,v of matching point :
        
        pose_graph = PoseGraph()
        trans_odometry = np.identity(4)
        
        pose_graph.nodes.append(PoseGraphNode(trans_odometry))        
        
        trans_odometry = np.dot(transform_matrix, trans_odometry)
        
        trans_odometry_inv = np.linalg.inv(trans_odometry)
        
        pose_graph.nodes.append(PoseGraphNode(trans_odometry_inv))        
        pose_graph.edges.append(  PoseGraphEdge(0, 0, transform_matrix, info, uncertain = False))
        
        
        pose_graph=self.run_posegraph_optimization(pose_graph)
        
        print("pose_graph node : u,v points in target frame:",pose_graph.edges[0].pose,np.linalg.inv(pose_graph.nodes[1].pose))
        
        
        
        
        #3:convert to XYZ space
        source_depth_n_array=np.asarray(source_rgbd_image.depth)        
        source_rgb_n_array=np.asarray(source_rgbd_image.color)           
        
        source_depth_xyz=self.create_XYZ_image(source_depth_n_array,cx, cy, fx, fy)
        
        
        target_rgb_n_array=np.asarray(target_rgbd_image.color) 
        target_depth_n_array=np.asarray(target_rgbd_image.depth)                      
        
        target_depth_xyz=self.create_XYZ_image(target_depth_n_array,cx, cy, fx, fy) 
        
        
        #transform source to target space:
        t_source_xyz=self.transform_xyz_image_to_target_space(source_depth_xyz, transform_matrix)
        
        
        
       # 4: create new image xyz arraya and append target and source_n_arrays to this array by u,v positions:
