### ISSUE TITLE
Linker Problems (KDTreeFlann::SearchKNN)

### ISSUE THREAD

**Issue by timfelle** [IntelVCL/Open3D#648]
Hello, I am using the Open3D library along with Visual Studio 2017 for a project. During which i am trying to make use of the KDTreeFlann class in order to do a Nearest Neighbour Search. I am using the function `open3d::KDreeFlann::SearchKNN` but i am getting the following error when attempting to compile the program:

`LNK2001	unresolved external symbol "public: int __cdecl open3d::KDTreeFlann::SearchKNN<class Eigen::Block<class Eigen::Matrix<double,-1,-1,0,-1,-1>,1,-1,0> >(class Eigen::Block<class Eigen::Matrix<double,-1,-1,0,-1,-1>,1,-1,0> const &,int,class std::vector<int,class std::allocator<int> > &,class std::vector<double,class std::allocator<double> > &)const "`

So far what i have been able to gather is that there might be an issue with the linking of the libraries, but i cant find the FLANN library anywhere except the 3rdparty folder before compiling. CMake includes no reference to FLANN when i build Open3D.

**Comment by qianyizh** [comment]
FLANN is header only so you don't really need to link it. The error looks like an Open3D internal function ``open3d::KDTreeFlann::SearchKNN`` is not successfully built and is not linked to your program. Can you double check if ``core.lib`` has been built in your build folder? (It should be the first thing your compiler builds.)

Also, can you paste the full output log from VS2017 console?

**Comment by timfelle** [comment]
It would seem `core.lib` have not been built. 
The output from building my program: (If you meant the output from building Open3D then just let me know.

>1>------ Rebuild All started: Project: Registration, Configuration: Release x64 ------
>1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppBuild.targets(391,5): warning MSB8028: The intermediate directory (C:\PATH_TO_SOLUTION\build\x64\Release\) contains files shared from another project (GenerateData.vcxproj).  This can lead to incorrect clean and rebuild behavior.
>1>point_cloud_utility.cpp
>1>utility_functions.cpp
>1>registration.cpp
>1>fast_point_feature_histograms.cpp
>1>fast_point_feature_histograms.obj : error LNK2001: unresolved external symbol "public: int __cdecl open3d::KDTreeFlann::Search<class Eigen::Block<class Eigen::Matrix<double,-1,-1,0,-1,-1>,1,-1,0> >(class Eigen::Block<class Eigen::Matrix<double,-1,-1,0,-1,-1>,1,-1,0> const &,class open3d::KDTreeSearchParam const &,class std::vector<int,class std::allocator<int> > &,class std::vector<double,class std::allocator<double> > &)const " (??$Search@V?$Block@V?$Matrix@N$0?0$0?0$0A@$0?0$0?0@Eigen@@$00$0?0$0A@@Eigen@@@KDTreeFlann@open3d@@QEBAHAEBV?$Block@V?$Matrix@N$0?0$0?0$0A@$0?0$0?0@Eigen@@$00$0?0$0A@@Eigen@@AEBVKDTreeSearchParam@1@AEAV?$vector@HV?$allocator@H@std@@@std@@AEAV?$vector@NV?$allocator@N@std@@@6@@Z)
>1>C:\PATH_TO_SOLUTION\Registration.exe : fatal error LNK1120: 1 unresolved externals
>1>Done building project "Registration.vcxproj" -- FAILED.
>========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========

**Comment by qianyizh** [comment]
It looks like your CMake has not successfully found Open3D. So the libraries are wrong. Can you check your project property -> Libraries. See if the installed Open3D directory is in the additional directories and core.lib is in input?

**Comment by timfelle** [comment]
core.lib is not located in the input, however it did not help to include it, and the Open3D library is included. I do not get any errors when i attempt to reinstall open3d.

**Comment by timfelle** [comment]
I solved the problem. 
So initially i was attemtping to query Model.row(i) of the class Eigen::MatrixXd in the search tree. It was fixed by saving the Model.row(i) as a VectorXd and then do the query in the KDTree. So the problem turns out to be a template issue.

KDTree is build:
> KDTreeFlann KDTree_q;
> KDTree_q.SetMatrixData(FPFH_q);

Original:
> int knn = 1;
> KDTree_q.SearchKNN(FPFH_mod.col(i), knn, index, dist);

Fixed version:
> int knn = 1;
> VectorXd mod = FPFH_mod.col(i);
> KDTree_q.SearchKNN(mod, knn, index, dist);
