### ISSUE TITLE
[Question] Plotting a Vector with a 6D Pose

### ISSUE THREAD

**Issue by kevinzakka** [IntelVCL/Open3D#660]
Hey,

I can't figure out how to plot a vector on top of a pointcloud. I've computed the surface normals and would like to plot only a single normal at a given (x, y, z) location with a given orientation.

I tried using a Vector3dVector but draw_geometries threw an error.

Would appreciate any help!

**Comment by syncle** [comment]
Hi @kevinzakka, Please see this example http://www.open3d.org/docs/tutorial/Basic/visualization.html#draw-line-set. To draw a line you will need to define two points and edges. For example, you can you p, p+n to draw a line of normal vector for p.

**Comment by kevinzakka** [comment]
HI @syncle,

I've installed open3d from source and cannot find LineSet. The output to `dir(open3d)` also doesn't show up.

**Comment by syncle** [comment]
Can you check that you are using the recent Open3D? We had some change on the python installation, so old open3d version is still being imported in your Python environment. Consider use "python -v" to see the the your Open3D package location, remove it, and install Open3D again from source or from conda or pip.

**Comment by kevinzakka** [comment]
Solved. Thanks @syncle !
