### ISSUE TITLE
Visual 3d point directly from numpy array

### ISSUE THREAD

**Issue by jinfagang** [IntelVCL/Open3D#664]
Does it support visualize numpy array?

**Comment by yxlao** [comment]
Almost -- first we'll need to create a `PointCloud` from the numpy array. 

```python
import numpy as np
import open3d

points = np.random.rand(10000, 3)
point_cloud = open3d.PointCloud()
point_cloud.points = open3d.Vector3dVector(points)
open3d.draw_geometries([point_cloud])
```

**Comment by syncle** [comment]
I think we can say "yes" :) Thanks to #657, there is almost no overhead.

**Comment by jinfagang** [comment]
@syncle @yxlao Many thanks. Open3D is a very good library, the only question is that it's not work very well with IDE for code suggestions such as PyCharm in Python interface. Would be better to promote it, then it could be good as OpenCV

**Comment by yxlao** [comment]
Could there be settings in pycharm? 

For example, Jupyter notebook does code suggestions pretty well: 
<img width="691" alt="screen shot 2018-11-06 at 6 07 30 pm" src="https://user-images.githubusercontent.com/1501945/48106111-f1344200-e1ee-11e8-9485-a0258460be9b.png">

There are two cases: (1) pure Python code and (2) compiled C++ python module (and Open3D has a lot of them). Apparently Jupyter suggesion works for both (1) and (2). 

My guess is that PyCharm is configured to only show case (1)? If this is the case, do you have suggestions on how to "promote" case (2) to be case (1) for PyCharm?

**Comment by jinfagang** [comment]
I saw Open3D source codes, it did some promote suggestion optimization in Jupyter notebook. But not in pure python, I mean, pycharm or vscode can not work with that. If you try pycharm, you will see Open3D just failing at any code suggestions

**Comment by yxlao** [comment]
From this https://stackoverflow.com/a/5196184/1255535, it seems to be possible to set up in PyCharm. Though there are other reports saying that it is not possible with PyCharm.

I did a quick comparison with opencv. The `__init__.py` file look almost identical, so if opencv autocomplete works, open3d shall also work
- https://github.com/skvark/opencv-python/blob/master/cv2/__init__.py (which exposes https://github.com/opencv/opencv/blob/master/modules/python/src2/cv2.cpp)
- https://github.com/IntelVCL/Open3D/blob/master/src/Python/Package/open3d/__init__.py

Coud you check your installed opencv and see if there are some additional tricks? 🕵️

**Comment by jinfagang** [comment]
@yxlao Thanks for your quick look. `__init__` file actually identical. I think maybe it's installation process makes sure the child package importable in IDEs. I am not quite specialized in Python package writing, helping for your guys improve it in the future and make Open3D a great library though

**Comment by yxlao** [comment]
@jinfagang looked at it again today, turned out to be an easy fix #676

**Comment by jinfagang** [comment]
@yxlao The API seems broken looks from today. I updated it here for users might got into this issue:

```
point_cloud = o3d.geometry.PointCloud()
point_cloud.points = o3d.utility.Vector3dVector(ptc)

o3d.visualization.draw_geometries([point_cloud])
```

**Comment by happyseo10** [comment]
> visualization
I tried this but get the error RuntimeError: Unable to cast Python instance to C++ type (compile in debug mode for details) ? I'm trying to just purely use python here. tried changing points to float64 but seems to have shape error too.
