### ISSUE TITLE
(Question) Custom rgbd format

### ISSUE THREAD

**Issue by HTLife** [IntelVCL/Open3D#665]
In the [rgbd_tum.py](https://github.com/IntelVCL/Open3D/blob/master/examples/Python/Basic/rgbd_tum.py) example, `create_rgbd_image_from_tum_format` expect a 1 channel color image.  If I want to create rgbd image from 3 channel(rgb) color image, what is the best practice?

**Comment by syncle** [comment]
Add ``convert_rgb_to_intensity=False``. It will create a RGBD image with color.

**Comment by HTLife** [comment]
It works!  Thank you.
