### ISSUE TITLE
Possible issue in point cloud generation of sun dataset. (1 point is missing)

### ISSUE THREAD

**Issue by dhorka** [IntelVCL/Open3D#671]
Hi,

I am not pretty sure if it is a bug or I am doing something wrong. I am working with the SUN-RGBD dataset and I am trying to create the point cloud using depth and color images. But in the resulting pointcloud 1 point is missing... I am following the tutorial provided in the documentation. The piece of code that I am using is this one:

```
import open3d
import numpy as np
img_folder = "/datasets/SUNRGBD/kv2/kinect2data/000037_2014-05-26_14-54-02_260595134347_rgbf000041-resize"
rgb_path = open3d.read_image(img_folder+'/image/0000041.jpg')
depth_path = open3d.read_image(img_folder+'/depth_bfx/0000041.png')

intrinsic = np.loadtxt(img_folder + '/intrinsics.txt') 

rgbd_image = open3d.create_rgbd_image_from_sun_format(rgb_path, depth_path);
print("color: ", np.shape(np.asarray(rgbd_image.color)))
print("depth: ", np.shape(np.asarray(rgbd_image.depth)))
#pcd = open3d.create_point_cloud_from_rgbd_image(rgbd_image,open3d.PinholeCameraIntrinsic(
#    730,530,intrinsic[0,0],intrinsic[1,1],intrinsic[0,2],intrinsic[1,2]))
pcd = open3d.create_point_cloud_from_rgbd_image(rgbd_image, open3d.PinholeCameraIntrinsic(
        open3d.PinholeCameraIntrinsicParameters.PrimeSenseDefault))

pcd.transform([[1, 0, 0, 0], [0, -1, 0, 0], [0, 0, -1, 0], [0, 0, 0, 1]])
print(pcd.points)
np_points = np.asarray(pcd.points)
print("points", np.shape(np_points))
```
**Output:**

> color:  (530, 730)
> depth:  (530, 730)
> std::vector<Eigen::Vector3d> with 386899 elements.
> Use numpy.asarray() to access data.
> points (386899, 3)
> 

I am was expecting to have 530*730 = 386900 points. I checked with the matlab tools provided by the authors of the dataset, and with their tools I obtaining the expected result 386900 points, (all of them different of nan). I am using the processed depth in order to have depth values for each pixel.

Am I wrong in something? 

Thanks for your time.

**Environment:**
Ubuntu 16.04
Python 3.5
open3d 0.3.0 from source (also tested in open3d 0.4.0 from pip)

**Comment by syncle** [comment]
Hi @dhorka, I think on of the depth pixel was not valid so ``create_point_cloud_from_rgbd_image`` didn't create a point for that. As you can see in here 

https://github.com/IntelVCL/Open3D/blob/e08bae1fa0a9db0691d3726cda140d11738d439c/src/Core/Geometry/PointCloudFactory.cpp#L39-L50

It just only triangulates non-zero depth values. You can check if there are any pixels having zero values.

**Comment by dhorka** [comment]
Hi @syncle, First at all thanks for your quick answer. As I said on the post, I am using the [toolbox](http://rgbd.cs.princeton.edu/data/SUNRGBDtoolbox.zip) provided for the authors in order to compare the results obtained in open3d. I re-checked and the depth file that I am using is not containing any zero values, all of them are valid values. (I checked using the matlab toolbox). Then maybe the problem is not located in the create_point_cloud function, maybe is located on create_rgbd_image_from_sun_format. Can be?

**Comment by syncle** [comment]
Then, please check if the depth value has more than 7m. 
https://github.com/IntelVCL/Open3D/blob/ef042a6c50e54c4bb56ccb4657a745c9b38c1b7f/src/Core/Geometry/RGBDImageFactory.cpp#L85-L88

**Comment by dhorka** [comment]
I see. There is one value larger than 7 meters and when the comment said the depth is truncated, it means the value is eliminated, right? In the original matlab code the depth is truncated as 8 but the value is not eliminated, is tresholded to 8 as you can see in this piece of code:
```
function [rgb,points3d,depthInpaint,imsize]=read3dPoints(data)
         data.depthpath
         depthVis = imread(data.depthpath);
         max(max(depthVis))
         imsize = size(depthVis)
         depthInpaint = bitor(bitshift(depthVis,-3), bitshift(depthVis,16-3));
         depthInpaint = single(depthInpaint)/1000; 
         depthInpaint(depthInpaint >8)=8;
         [rgb,points3d]=read_3d_pts_general(depthInpaint,data.K,size(depthInpaint),data.rgbpath);
         points3d = (data.Rtilt*points3d')';
end
```
Then the only solution possible at this moment to be able to obtain the same results that I obtaining using the matlab code, it is rewrite the read function by my own, right?

**Comment by syncle** [comment]
Yes. To do this, 
1) you can do manually clipping them (something like ``depthInpaint(depthInpaint >8)=8;``) using the Python, change 7.0 in ``return CreateRGBDImageFromColorAndDepth(color, depth, 1000.0, 7.0, convert_rgb_to_intensity);`` to be larger than 8.0, 
2) build Open3D from source. 
By doing so, depth value more than 8.0 will become 8.0, and they will not be ignored, because ``CreateRGBDImageFromColorAndDepth`` only drops pixels more than 8.0

**Comment by syncle** [comment]
Closed for now due to inactivity. @dhorka: Feel free to reopen this if necessary :)
