### ISSUE TITLE
Open3D/docs/_static/C++/TestVisualizer.cpp compilation error

### ISSUE THREAD

**Issue by ZF-AR** [IntelVCL/Open3D#675]
**Describe the bug**
Open3D compilation and installation successful.
But Open3D/docs/_static/C++/TestVisualizer.cpp cannot compile due to lpng16 error.

**To Reproduce**
1. cd /Open3D/docs/_static/C++
2. cmake .
3. make

**Expected behavior**
/Open3D/docs/_static/C++$ cmake .
-- Found Open3D 0.2.0.0
-- Configuring done
-- Generating done
-- Build files have been written to: /Open3D/docs/_static/C++

Open3D/docs/_static/C++$ make
[ 50%] Building CXX object CMakeFiles/TestVisualizer.dir/TestVisualizer.cpp.o
[100%] Linking CXX executable TestVisualizer
**/usr/bin/ld: cannot find -lpng16**
collect2: error: ld returned 1 exit status
CMakeFiles/TestVisualizer.dir/build.make:95: recipe for target 'TestVisualizer' failed
make[2]: *** [TestVisualizer] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/TestVisualizer.dir/all' failed
make[1]: *** [CMakeFiles/TestVisualizer.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Desktop (please complete the following information):**
 - Ubuntu 16.04 LTS

**Comment by fzheng010** [comment]
Fixed. Followed http://www.linuxfromscratch.org/blfs/view/8.0/general/libpng.html, and installed libpng manually.

**Comment by fzheng010** [comment]
Please help close. Thanks.

**Comment by yxlao** [comment]
Seems an old version is used?
```
Found Open3D 0.2.0.0
```
