### ISSUE TITLE
Can't read pcd.bin format

### ISSUE THREAD

**Issue by ppalaupuigdevall** [IntelVCL/Open3D#680]
Whenever I try to load a pcd in binary format (**pcd.bin**) I can't do it. I use the function _read_point_cloud('my_point_cloud.pcd.bin')_ but this one does not support this format.

Is it possible to load this format? If not, I think it could be a valuable feature to add.

Thank you and congratulations for the library,

**Comment by dbadrian** [comment]
Replied to you on discord, but I think you didnt read it before leaving maybe?

**Short answer:** You need to rename your file from **.pcd.bin** to **.pcd** .

Why?: the correct function for loading is automatically inferred from the file extension and that is ".pcd". The information that it is (compressed) binary is read from the header itself and requires no user input. I am not the author of this code, but a quick glance at the respective source code tells me it should be possible to read ascii/binary and seemingly also compressed binary (in the case of the PCD format).
(see https://github.com/IntelVCL/Open3D/blob/master/src/IO/FileFormat/FilePCD.cpp)


Generally: 
Supported are for PointCloud: xyz, xyzn, zyzrgb, ply, pcd, pts
(see https://github.com/IntelVCL/Open3D/blob/master/src/IO/ClassIO/PointCloudIO.cpp)

Supported are for TriangleMesh: ply
(see https://github.com/IntelVCL/Open3D/blob/master/src/IO/ClassIO/TriangleMeshIO.cpp)

**Comment by syncle** [comment]
Yes. As @dbadrian said, ``read_point_cloud`` determines file type based on its extension. Another option is to add ``format = "pcd"`` in the ``read_point_cloud`` in order to manually specify file format.

**Comment by ppalaupuigdevall** [comment]
Hello, thank you for your answers. I checked https://github.com/IntelVCL/Open3D/blob/master/src/IO/FileFormat/FilePCD.cpp as @dbadrian said and I see that it based on the extension. I renamed the file to .pcd but the following error appears: 
_Read PCD failed: unable to parse header._ . I think that all the pointcloud is in binary, including the header. I had no problems reading .pcd files but when dealing with these kind of .pcd.bin it does not work.

**Comment by qianyizh** [comment]
Can you give more details regarding where you get these bin files? How are they created? Can you also give us a sample file so we can take a look?

**Comment by ppalaupuigdevall** [comment]
Solved! The problem was not related to the library, it was a problem of not knowing the format and shape of the pointclouds. I opened the file with _pcd.bin_ extension with: 
`numpy.fromfile(filename, dtype=np.float32)`
Then reshape it to Nx3 matrix and create a Pointcloud from a 3d vector as specified in here: [http://www.open3d.org/docs/tutorial/Basic/working_with_numpy.html#from-numpy-to-open3d-pointcloud](url) 

Thank you all for the answers,
