### ISSUE TITLE
Correct use of smart pointers

### ISSUE THREAD

**Issue by syncle** [IntelVCL/Open3D#701]
We will need to check if there is a code in current master has the similar issue what @yxlao mentioned. Please see: https://github.com/IntelVCL/Open3D/pull/694#pullrequestreview-174584341
In summary, when we make a new shared_ptr, we should avoid copy constructor.

**Comment by yxlao** [comment]
Did a quick check of current master (7218a5283b9034f2ab865b9f98032f61cf69aef7) of all usages of `make_shared` and `make_unique`, there's only one of such issue:
https://github.com/IntelVCL/Open3D/blob/7218a5283b9034f2ab865b9f98032f61cf69aef7/src/UnitTest/Core/ColorMap/ColorMapOptimization.cpp#L96

**Comment by takanokage** [comment]
This is the same we've been discussing in #694.
My case was that all copies are not bad - they're only bad if you can prove they have a negative impact on performance or functional correctness.
The code is functionally correct and there's no performance bottleneck here that needs to be resolved.

**Comment by syncle** [comment]
Let's not compromise with current situation - in a long term the test function will be extended, and the current functions will be used as a reference. At that point, we may miss the point raised by @yxlao. I think we need to provide the best code, and this fix will not severely blocks our workload.
