### ISSUE TITLE
Is there a function like write_line_set

### ISSUE THREAD

**Issue by xuyongzhi** [IntelVCL/Open3D#705]
Is there a File IO method for Line_set, like write_line_set? Similar with write_point_cloud and write_triangle_mesh.

**Comment by syncle** [comment]
Nope. Actually I am not sure if there is a common format that can support lineset. For point cloud and triangle mesh is widely used though. It is interesting question. Maybe we need to define a new general file format like .pcd in PCL?

**Comment by xuyongzhi** [comment]
Thanks for quick and nice reply! I think ply format can support this with element edge as shown in: http://paulbourke.net/dataformats/ply/
I currently use plyfile to do this: https://github.com/dranjan/python-plyfile

**Comment by syncle** [comment]
Thanks for the suggestion. @xuyongzhi! I am working on this.

**Comment by qianyizh** [comment]
Addressed in #742
