### ISSUE TITLE
Mac Build Warning

### ISSUE THREAD

**Issue by syncle** [IntelVCL/Open3D#712]
**Describe the bug**
When a code is built from source, there are tones of warning messages.
```
warning: unknown warning option '-Wno-expansion-to-defined'; did you mean '-Wno-macro-redefined'?
      [-Wunknown-warning-option]
```

**To Reproduce**
Build from source using current master branch

**Desktop (please complete the following information):**
 - OS: OSX (10.12.6)

**Additional context**
Need to fix CmakeList.txt

**Comment by yxlao** [comment]
Encounter the same problem. On CI, there is also a lot of such warning, see https://travis-ci.org/IntelVCL/Open3D/jobs/460845985#L2675. 

This was introduced in a previous commit:
https://github.com/IntelVCL/Open3D/pull/707/files#diff-af3b638bc2a3e6c650974192a53c7291R139
