### ISSUE TITLE
Parameters for global registration on a special 2d cloud ?

### ISSUE THREAD

**Issue by templiert** [IntelVCL/Open3D#718]
I am trying to adjust parameters of the global registration to align two 2d point clouds (p1, p2, attached). There are small distortions and a few outliers between the two clouds.

To start with, I am not succeeding in simply registering p1 with a translation+rotation of p1. I have unsuccessfully tried many combinations of the parameters: 
- voxel_size (I think it should be 1, the point locations are integer and no downsampling should be used)
- distance_threshold
- RANSAC iterations
- CorrespondenceCheckerBasedOnEdgeLength

Here a snapshot of what the initial p1 and transformed p1 look like:
![image](https://user-images.githubusercontent.com/34257249/48967143-7fc10580-efdc-11e8-9619-f43d7f039e85.png)

I assume that some of the 33 computed features are useless on a 2d cloud (normals do not really make sense in this modality) ? Would there still be a meaningful set of parameters for such data ?

Thanks a lot for any hint

----------------------------------------------------
The modality it comes from:
- there is a random distribution of identical spheres in 3d
- parallel xy planes are extracted along the z axis
- the spheres intersecting the planes are approximated by a point in the 2d planes
- the distance between consecutive planes is smaller than the diameter of the spheres, so that each sphere intersects several planes
- the planes are rotated/translated and their order shuffled. For a given 2d plane I am trying to find back which other planes were originally neighbor planes, i.e., which planes share a sufficient number of spheres in common
----------------------------------------------------
[p1p2.zip](https://github.com/IntelVCL/Open3D/files/2612190/p1p2.zip)

**Comment by qianyizh** [comment]
Umm, you need a 2D feature to run registration for 2D point clouds. Open3D does not have such a feature yet. (The FPFH feature used in Open3D is a 3D feature based on local geometry - in 2D case, it is a local surfel, thus cannot distinguish different points.)

But I think registering 2D point sets is a relatively easier problem. You can look for similar feature extractors / registration algorithm in OpenCV.

**Comment by syncle** [comment]
I think the example data is ill-posed. Instead of the unique solution, any transformations that can align the planar scene could be the solution. Does the pattern in the 2D domain has meaningful distribution? Otherwise, I think any feature descriptor just describes a feature about planar scene, and could be matched to any region.

**Comment by templiert** [comment]
> Umm, you need a 2D feature to run registration for 2D point clouds. Open3D does not have such a feature yet. (The FPFH feature used in Open3D is a 3D feature based on local geometry - in 2D case, it is a local surfel, thus cannot distinguish different points. 

Ok that's clear, thanks.

> But I think registering 2D point sets is a relatively easier problem.

I agree.

> You can look for similar feature extractors / registration algorithm in OpenCV.

I could not find a 2D feature extractor working with a point cloud specifically (using for example the relative position of one point to its neighbors as a descriptor), easy to use with python and easily parallelizable.

> I think the example data is ill-posed. Instead of the unique solution, any transformations that can align the planar scene could be the solution.

Sorry I am not sure I understand what you mean. In the example a 2D random point cloud has been transformed in the same plane, and I was trying to let the algorithm find the known transformation back. In the real use case, the two clouds will be slightly different, in the example I was using the same 2d cross section as a first easy test.

> Does the pattern in the 2D domain has meaningful distribution?

As mentioned at the bottom of the first post, these images are 2d xy cross sections from a same 3D random point cloud. The points from the 3D cloud are actually spheres with a certain diameter so that a same point is visible in multiple 2d cross sections.

> Otherwise, I think any feature descriptor just describes a feature about planar scene, and could be matched to any region.

Sorry again, I'm not sure I understand.

Thanks anyway for your answers, I'll look for another solution.

**Comment by Doodle1106** [comment]
@templiert 
Hi, I'm doing something similar, have you found a good way to register two 2D point clouds?
