### ISSUE TITLE
Color Space

### ISSUE THREAD

**Issue by rukie** [IntelVCL/Open3D#719]
I'm curious if you've tested any performance impacts or accuracy impacts with different color spaces. I have come across some discussion on RGB vs HSV and L*a*b* Color spaces. 

Example: Here the team uses Hue and drops Saturation and drops Value. 
https://hal-lirmm.ccsd.cnrs.fr/lirmm-00128684/document

As always, thanks for the great tool!

**Comment by qianyizh** [comment]
I have experimented different color spaces a few years ago when I started the color map optimization project. Here are my personal (very rough and empirical) summary:

1. For alignment purpose, intensity is usually enough. The strongest signal comes from the texture edges. No matter which color space you use, texture edges are always there. So intensity is enough.
2. For synthesize / composition purpose, Lab is the best color space. A robust average gives the best result.

**Comment by syncle** [comment]
Closed due to inactivity. @rukie: feel free to reopen this if necessary :)
