### ISSUE TITLE
About /Python/Tutorial/Advanced/outlier_removal.py

### ISSUE THREAD

**Issue by wangyingyu** [IntelVCL/Open3D#724]
Hello, 
I want to use the point cloud denoising feature. I see this feature in `/Python/Tutorial/Advanced/outlier_removal.py `but it can only be displayed but not saved. I want to save the denoised point cloud using the write_point_cloud()  function.But 
```
cl, ind = statistical_outlier_removal(voxel_down_pcd,
             Nb_neighbors=20, std_ratio=2.0)
```
statistical_outlier_removal()  I didn't find its definition and I don't know what the returned value is. You can give me some advice on how to denoise the point cloud and save the result?

**Comment by syncle** [comment]
You can see the following lines from the tutorial:
```
def display_inlier_outlier(cloud, ind):
    inlier_cloud = select_down_sample(cloud, ind)
```
here, ``inlier_cloud`` is inlier subset of the point cloud. You can use 
```
write_point_cloud("inliner.pcd", inlier_cloud)
```
to save ``inlier_cloud``

**Comment by wangyingyu** [comment]
> You can see the following lines from the tutorial:
> 
> ```
> def display_inlier_outlier(cloud, ind):
>     inlier_cloud = select_down_sample(cloud, ind)
> ```
> here, `inlier_cloud` is inlier subset of the point cloud. You can use
> 
> ```
> write_point_cloud("inliner.pcd", inlier_cloud)
> ```
> to save `inlier_cloud`

Thanks for your reply.I modified the code according to your method, as follows:
 ```
print("Statistical oulier removal")
    cl,ind = statistical_outlier_removal(voxel_down_pcd,
            nb_neighbors=20, std_ratio=2.0)
    display_inlier_outlier(voxel_down_pcd, ind)
    

    print("Radius oulier removal")
    cl,ind = radius_outlier_removal(voxel_down_pcd,
            nb_points=16, radius=0.05)
    display_inlier_outlier(voxel_down_pcd, ind)
    

    write_point_cloud("/Users/charlie/Downloads/copy_of_fragment.pcd", inlier_cloud)
```
Then prompt after running the program
```
Traceback (most recent call last):
  File "./pointcloud_outlier_removal.py", line 45, in <module>
    write_point_cloud("/Users/charlie/Downloads/copy_of_fragment.pcd", inlier_cloud)
NameError: name 'inlier_cloud' is not defined
```
How can I do this?

**Comment by wangyingyu** [comment]
> add `inlier_cloud = select_down_sample(voxel_down_pcd, ind)` below `display_inlier_outlier(voxel_down_pcd, ind)`

I tried this before, when the code is like this:
```
print("Statistical oulier removal")
    cl,ind = statistical_outlier_removal(voxel_down_pcd,
            nb_neighbors=20, std_ratio=2.0)
    display_inlier_outlier(voxel_down_pcd, ind)
    inlier_cloud = select_down_sample(voxel_down_pcd, ind) 

    print("Radius oulier removal")
    cl,ind = radius_outlier_removal(voxel_down_pcd,
            nb_points=16, radius=0.05)
    display_inlier_outlier(voxel_down_pcd, ind)
    inlier_cloud = select_down_sample(voxel_down_pcd, ind) 
```
Run this program to return an error:
`Write PCD failed: unable to generate header.`

**Comment by wangyingyu** [comment]
> add `inlier_cloud = select_down_sample(voxel_down_pcd, ind)` below `display_inlier_outlier(voxel_down_pcd, ind)`

So, can you give me some advice on how to modify it? Or I want to know where these functions are defined, I can find them and see where the problem is. Thank you.

**Comment by syncle** [comment]
This should work out-of-the-box
```
from open3d import *

def display_inlier_outlier(cloud, ind):
    inlier_cloud = select_down_sample(cloud, ind)
    outlier_cloud = select_down_sample(cloud, ind, invert=True)

    print("Showing outliers (red) and inliers (gray): ")
    outlier_cloud.paint_uniform_color([1, 0, 0])
    inlier_cloud.paint_uniform_color([0.8, 0.8, 0.8])
    draw_geometries([inlier_cloud, outlier_cloud])


if __name__ == "__main__":

    print("Load a ply point cloud, print it, and render it")
    pcd = read_point_cloud("../../TestData/ICP/cloud_bin_2.pcd")
    draw_geometries([pcd])

    print("Downsample the point cloud with a voxel of 0.02")
    voxel_down_pcd = voxel_down_sample(pcd, voxel_size = 0.02)
    draw_geometries([voxel_down_pcd])

    print("Radius oulier removal, or you can try other")
    cl,ind = radius_outlier_removal(voxel_down_pcd,
            nb_points=16, radius=0.05)
    display_inlier_outlier(voxel_down_pcd, ind)
    inlier_cloud = select_down_sample(voxel_down_pcd, ind)
    write_point_cloud("test.ply", inlier_cloud)
```

``Write PCD failed: unable to generate header.`` this might be because of the point cloud you wanted to save is empty. Can you do ``print(inlier_cloud)`` or  ``print(len(inlier_cloud.points))`` and see how many points remain after the filtering?

**Comment by wangyingyu** [comment]
> This should work out-of-the-box
> 
> ```
> from open3d import *
> 
> def display_inlier_outlier(cloud, ind):
>     inlier_cloud = select_down_sample(cloud, ind)
>     outlier_cloud = select_down_sample(cloud, ind, invert=True)
> 
>     print("Showing outliers (red) and inliers (gray): ")
>     outlier_cloud.paint_uniform_color([1, 0, 0])
>     inlier_cloud.paint_uniform_color([0.8, 0.8, 0.8])
>     draw_geometries([inlier_cloud, outlier_cloud])
> 
> 
> if __name__ == "__main__":
> 
>     print("Load a ply point cloud, print it, and render it")
>     pcd = read_point_cloud("../../TestData/ICP/cloud_bin_2.pcd")
>     draw_geometries([pcd])
> 
>     print("Downsample the point cloud with a voxel of 0.02")
>     voxel_down_pcd = voxel_down_sample(pcd, voxel_size = 0.02)
>     draw_geometries([voxel_down_pcd])
> 
>     print("Radius oulier removal, or you can try other")
>     cl,ind = radius_outlier_removal(voxel_down_pcd,
>             nb_points=16, radius=0.05)
>     display_inlier_outlier(voxel_down_pcd, ind)
>     inlier_cloud = select_down_sample(voxel_down_pcd, ind)
>     write_point_cloud("test.ply", inlier_cloud)
> ```
> `Write PCD failed: unable to generate header.` this might be because of the point cloud you wanted to save is empty. Can you do `print(inlier_cloud)` or `print(len(inlier_cloud.points))` and see how many points remain after the filtering?

Thank you very much. Yes, the number of points I filtered is 0. This is because all points have been filtered after Radius oulier removal. I have solved this problem now.
