### ISSUE TITLE
i think this is a bug,hope you can help me

### ISSUE THREAD

**Issue by ChenDRAG** [IntelVCL/Open3D#727]
i use
 vis.get_view_control().convert_from_pinhole_camera_parameters(intrinsic, extrinsic)
to try to change the vis's intrinsic , but get the error message
[ViewControl] ConvertFromPinholeCameraParameters() failed because window height and width do not match.
however,i specificly set window size but still get the error message .
it seems that the vis do not allow others to change its intrinsic?

here is the code

```python
m = load.Obj("../ori/live_smpl/frame_1536_live_smpl.obj")
m=m.data
mesh=dict_to_open3dmesh(m)
root=np.array([
[  0.998829 , 0.0333804 ,-0.0346933,    1.01455],
[0.0347492  , -0.99859 , 0.0396284  ,  1.30343],
[-0.0333237 ,-0.0407875  ,-0.998584 ,  0.862265],
[0     ,     0   ,       0    ,      1]
])
mesh.transform(root)
mesh.compute_vertex_normals()
#custom_draw_geometry_with_key_callback(mesh)
vis = open3d.Visualizer()
intrinsic=open3d.PinholeCameraIntrinsic()
intrinsic.set_intrinsics(640,480,365.4020,365.6674,316.4944,235.7411)
extrinsic=np.array([
[    0.9981 ,-0.0160041,  0.0593907 ,   -1.0298],
[0.0123974 ,  0.998087 , 0.0605806  , -1.59618],
[-0.060248, -0.0597236 ,  0.996391  ,  1.32826],
[       0.  ,        0. ,       0.     ,     1.]
],dtype='float64')
print(vis)
print(vis.get_window_name())
print(vis.get_view_control())
vis.create_window(width=640, height=480, left=50, right=50)
vis.get_view_control().convert_from_pinhole_camera_parameters(intrinsic, extrinsic)
vis.add_geometry(mesh)
vis.run()
vis.destroy_window()
```

in a hurry ,really need your help

**Comment by yxlao** [comment]
One possible reason is that `convert_from_pinhole_camera_parameters` function signature has been changed in https://github.com/IntelVCL/Open3D/pull/597. It now takes the camera parameter instead if intrinsic and extrinsic.

**Comment by ChenDRAG** [comment]
i read #597,but don't really get it?
does that mean i for now cannot change the intrinsics by myself of is there annother to do  it?  can you please show me(a function or an example would be enough) ?
also , it seems that i cannot use the clase newly merged in #597 

>>> help(PinholeCameraParameters)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'PinholeCameraParameters' is not defined
>>> help(open3d.PinholeCameraParameters)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'open3d.open3d' has no attribute 'PinholeCameraParameters'
>>> help(read_pinhole_camera_parameters)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'read_pinhole_camera_parameters' is not defined

thanks again

**Comment by ChenDRAG** [comment]
is that because i pip3 install a wrong version of open3d?

**Comment by yxlao** [comment]
Oh sorry, that was a separate issue. To use the new features in `master` branch, we'll have to build from source. `pip install` only gets the released milestones.

Now, assuming we're using the 0.4.0 release. Regarding the original question, according to [here](
https://github.com/IntelVCL/Open3D/blob/master/src/Visualization/Visualizer/ViewControl.cpp#L154), we need to change the `cx = width / 2 - 0.5 = 319.5` and `cy = height / 2 - 0.5 = 239.5`.

E.g. change this line:
```python
intrinsic.set_intrinsics(640, 480, 365.4020, 365.6674, 319.5, 239.5)
```

**Comment by ChenDRAG** [comment]
got it , problem solved.thanks a lot .
really appreciate your help.

**Comment by simon-donne** [comment]
I'd like to reopen this. Why is the check w.r.t. the optical center there?
If this is the general assumption with Open3D, then why pass the optical center at all ? (i.e. I have pre-calibrated cameras which I'd like to replicate but which isn't directly possible like this).
