### ISSUE TITLE
Read and Write pointcloud progress bar

### ISSUE THREAD

**Issue by timfelle** [IntelVCL/Open3D#728]
Is it possible to avoid the progress bar output when using the c++ api of Open3d::ReadPointCloud and the write equivalent version as well?

**Comment by syncle** [comment]
Hi @timfelle. The option you can try now is to comment out ``ResetConsoleProgress`` ``AdvanceConsoleProgress`` functions in Open3D/src/IO/FileFormat/FilePLY.cpp (I am assuming you are working with ply file format)

In a long term (**note for Open3D dev team)**, it would be good to control this progress bar message using the following scopes 
https://github.com/IntelVCL/Open3D/blob/aa70a654b606ffe443036804f5c2c2f4788d94f6/src/Core/Utility/Console.h#L38-L44
used for open3d::PrintXX functions.

**Comment by timfelle** [comment]
Thankyou for the help.
For the interested reader the exact code to solve the problem was `SetVerbosityLevel(VerbosityLevel::VerboseError)`
