### ISSUE TITLE
Is there a way to set line thickness when drawing a LineSet?

### ISSUE THREAD

**Issue by ndrplz** [IntelVCL/Open3D#734]
As the title suggests, is there a 3D equivalent of `thickness` parameter in [`cv2.line`](https://docs.opencv.org/2.4/modules/core/doc/drawing_functions.html#line) when drawing a LineSet?

Like the `tube_radius` in [this](https://github.com/enthought/mayavi/blob/5c2694b72b329b8d5c469bc459a211378e2c8581/examples/mayavi/mlab/protein.py#L132) myavi example.

Thanks,
A

**Comment by syncle** [comment]
Hi @ndrplz, I am working on the request in this branch -> https://github.com/syncle/Open3D/tree/line_width it shall be submitted by this weekend.

**Comment by qianyizh** [comment]
Addressed in #738
