### ISSUE TITLE
WritePointCloud closing program with no warning

### ISSUE THREAD

**Issue by timfelle** [IntelVCL/Open3D#735]
I am writting a program to add synthetic noise and transformation to pointclouds. However adding outliers to a pointcloud sometimes cause the WritePointCloud function to close the program with no error or warning message. 

Outliers are added by randomly selecting an index and adding a rather large normally distributed noise to that point in the point cloud.

**Comment by syncle** [comment]
Hi @timfelle, could you explain your environment, minimal code and data, so that one of us can reproduce the issue?

**Comment by timfelle** [comment]
I am running a Visual Studio 2017 solution and test the program through the Cygwin console. The data i am using is the stanford bunny point cloud ply files. I have been experimenting with the `SetVerbosityLevel` but none of the levels seem to show an error when the program stops. 
````
#include <stdio.h>
#include <stdlib.h>
#include <cstdlib>
#include <iostream>
#include <string>
#include <math.h>
#include <random>

#include <Open3D/Core/Core.h>	// Open3D 
#include <Open3D/IO/IO.h>		// Open3D 

int main(int argc, char *argv[])
{
vector<string> dataName = { string(argv[1]), string(argv[2]) };
ReadPointCloud(dataName[0], model);

double outlier_amount = 10.0;
double amount = atof(outlier_amount) / 100.0;

default_random_engine gen;
normal_distribution<double> randn(0.0, 0.1*radius);
uniform_int_distribution<int> randi(0, (int)nPoints);
for (size_t i = 0; i < nPoints*amount; i++)
{
    int index = randi(gen);
    model.points_[index](0) += randn(gen);
    model.points_[index](1) += randn(gen);
    model.points_[index](2) += randn(gen);
}
WritePointCloud(  dataName[1], model);
}
```

**Comment by syncle** [comment]
Code looks fine except for few points. 
```
int index = randi(gen);
    model.points_[index](0) += randn(gen);
```
Can you check index does not exceed the number of points?
```
WritePointCloud(  dataName[1], model);
```
Can you check ``dataName[1]`` points correct path? You can just try "test.ply" (not providing the path but just filename) to see if the incorrect path is the issue.

**Comment by timfelle** [comment]
None of your sugestions seem to make a difference. The indicies do not exeed the size of the array and the path did not make a difference. The WritePointCloud function is always started but sometimes it just close the program.

**Comment by syncle** [comment]
> The indicies do not exeed the size

That's not true. According to [this reference](https://en.cppreference.com/w/cpp/numeric/random/uniform_int_distribution)

> Produces random integer values i, uniformly distributed on the closed interval [a, b]

and your generator was initialized by 
```
uniform_int_distribution<int> randi(0, (int)nPoints)
```
that means ``randi`` will produce [0, (int)nPoints]. **It will exceed the maximum index.** 

It should be 
```
uniform_int_distribution<int> randi(0, (int)nPoints-1)
```
As you are already experiencing, wrong memory access to ``std::vector`` container can make unexpected behavior. 

If the issue still persist, please report your environment (like we are gently asking when you opened issue) and minimal code and **data** so that we can try reproduce it.

**Comment by timfelle** [comment]
It seems that was the issue, thank you. I would have expected an segmentation fault would have been cast when i attempted to access the element, however that was not the case.
