### ISSUE TITLE
how to change the PinholeCameraIntrinsicParameters.PrimeSenseDefault

### ISSUE THREAD

**Issue by keacifer** [IntelVCL/Open3D#752]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by qianyizh** [comment]
``PinholeCameraIntrinsicParameters.PrimeSenseDefault`` is an enum that is used to create a ``PinholeCameraIntrinsic`` instance via ``PinholeCameraIntrinsic(PinholeCameraIntrinsicParameters.PrimeSenseDefault)``.

You can create a ``PinholeCameraIntrinsic`` with other initialization function such as:
``PinholeCameraIntrinsic(width, height, fx, fy, cx, cy)`` where ``fx, fy`` are the focal lengths, and ``cx, cy`` are the optical center coordinates.

**Comment by keacifer** [comment]
thanks very much , it helps a lot
