### ISSUE TITLE
In python, create_window() has a "left" and "right" parameter.  should be "left" and "top"?

### ISSUE THREAD

**Issue by mfassler** [IntelVCL/Open3D#754]
**Describe the bug**
If I want to create_window() in a specific position, there are two parameters:  "left" and "right".  The "right" parameter seems to control the up-down position.  Should this be renamed to "top"?  (The behavior is correct, just the argname is confusing.)

**Desktop (please complete the following information):**
Ubuntu 16.04.  Intel i5-8400, 32 GB ram.  GeForce-GTX-1080

**Comment by qianyizh** [comment]
You are right. It should be ``top``.

**Comment by syncle** [comment]
Addressed in #759.
