### ISSUE TITLE
Add some documentation or tutorials for a cube or box

### ISSUE THREAD

**Issue by ndbroadbent** [IntelVCL/Open3D#758]
Hello,

I've really been struggling to figure out how to render simple cube or box. I'm trying to visualize a 3D grid with some boxes, but I can only see meshes for spheres and cylinders. 

Does Open3D not include a "cube" or "box" primitive?

Thanks!

**Comment by syncle** [comment]
Hi @ndbroadbent: have you checked out [this tutorial](http://open3d.org/docs/tutorial/Basic/visualization.html#draw-line-set)? I believe this would be fit for your needs.

**Comment by ndbroadbent** [comment]
Hi @syncle, yes I saw the LineSet tutorial, but I wanted to render a solid cube with some faces, instead of lines. For my case, it would be much easier if I could just define the width, height, and depth, and a color, and then render a grid of cubes.
