### ISSUE TITLE
Cannot control the viewer when updating the geometry

### ISSUE THREAD

**Issue by taochenshh** [IntelVCL/Open3D#770]
Hi, I wrote the following code for realtime visualization of point cloud. But it seems that I cannot use mouse to rotate the view in the visualizer after the window shows up. It can be reproduced with the following code. I am using open3d 0.4.  Can anyone help? Thanks.
```python
import open3d
import numpy as np
import time

vis = open3d.Visualizer()
vis.create_window("3D Map")
pcd = open3d.PointCloud()
pts = np.mgrid[1: 6: complex(100), 
      2: 9: complex(100), 
      3: 6: complex(100)].reshape(3, -1).T
a = 1
start = time.time()
coord = open3d.create_mesh_coordinate_frame(1, [0, 0, 0])
coord_x = 0
vis.add_geometry(pcd)
while True:
    start_time = time.time()
    pcd.clear()
    coord.clear()
    pts[:, 0] = pts[:, 0] + 0.1
    pcd.points = open3d.Vector3dVector(pts)
    coord_x += 0.2
    coord = open3d.create_mesh_coordinate_frame(1, [coord_x, 0, 0])
    vis.add_geometry(coord)
    vis.update_geometry()
    vis.poll_events()
    vis.update_renderer()
    if time.time() - start > 30:
        break
    end_time = time.time()
    process_time = end_time - start_time
    print("Updating FPS = {0}".format(1.0 / process_time))
    print('Processing time:', process_time)
vis.destroy_window()
```

**Comment by taochenshh** [comment]
Hi, @syncle , Thanks for your quick reply. That makes sense. But I cannot see the points now (the visualization window is blank at all). Is there any other step that I am missing? Thanks.

**Comment by taochenshh** [comment]
Thanks.

**Comment by yigitkaraduman** [comment]
@syncle how can i set the view point in the middle of the window without reseting continiously?
i am dealing with point clouds of car's lidar and when i drive towards outside the window, point clouds disappear and went out the window frame.
