### ISSUE TITLE
no attribute 'voxel_down_sample_and_trace'

### ISSUE THREAD

**Issue by OmarAhmadien** [IntelVCL/Open3D#776]
When I use open3d inside my code and I call open3d.voxel_down_sample_and_trace it throws me that error: 

open3d.open3d has no attribute 'voxel_down_sample_and_trace'

I installed Open3D from the source. 

Any suggestions?

**Comment by yxlao** [comment]
Currently it's only available on `master` branch, compile it from source.
It will be added in the 0.5.0 release soon on PyPI and Conda.
