### ISSUE TITLE
read_pinhole_camera_intrinsic from numpy array?

### ISSUE THREAD

**Issue by lukaspistelak** [IntelVCL/Open3D#781]
I cant find nowhere in API how to load  intrinsic data. with known camera intrinsic-like numpy array for ex.

this only load only json:
intrinsic = read_pinhole_camera_intrinsic(config["path_intrinsic"]) 

Can i load numpy array?

**Comment by qianyizh** [comment]
See this: https://github.com/IntelVCL/Open3D/issues/752

You can also create an empty instance ``x = open3d.PinholeCameraIntrinsic()`` and control it directly with member variables:
```
 |  height
 |  
 |  intrinsic_matrix
 |  
 |  width
```
``height, width`` are integers and ``intrinsic_matrix`` is a 3-by-3 ``numpy.ndarray``.
