### ISSUE TITLE
Question: how to control mesh overlap during registration

### ISSUE THREAD

**Issue by rnunziata** [IntelVCL/Open3D#798]
Question: how to control mesh overlap during registration
When using ~/Open3D/examples/Python/ReconstructionSystem  I want to specify an near %80 overlap for the adjacent fragments...is this controlled by the loop settings.

    "preference_loop_closure_odometry": 0.1,
    "preference_loop_closure_registration": 5.0,

In MeshLab I am able to set the overlap that helps greatly with alignment of the point clouds.  Is there any way to do this inside the ReconstructionSystem system in examples.

**Comment by syncle** [comment]
Here is hard-coded line you can adjust:
https://github.com/IntelVCL/Open3D/blob/c4e974abb87b4006309ff98f69b1925d17074a0c/examples/Python/ReconstructionSystem/register_fragments.py#L47

**Comment by rnunziata** [comment]
thaks I believe this is related to my issue on global registration I will test changing these parameters as well.

**Comment by rnunziata** [comment]
thanks
