### ISSUE TITLE
RANSAC C++ example looping 50,000 times

### ISSUE THREAD

**Issue by pezcode** [IntelVCL/Open3D#800]
The [RegistrationRANSAC C++ example](https://github.com/IntelVCL/Open3D/blob/master/examples/Cpp/RegistrationRANSAC.cpp) is doing some odd looping where it runs the registration 50,000 times.

I assume this was for benchmarking, but it would be nice to have a useful working example that also visualizes the result (maybe an extra commandline option for the visualizer, currently it's forced to false).

**Comment by syncle** [comment]
You're right. Let me fix this.
