### ISSUE TITLE
Eigen directory not found on Ubuntu 18.04

### ISSUE THREAD

**Issue by Erblinium** [IntelVCL/Open3D#812]
Hi, I am getting include error in the C++ examples when building on ubuntu 18.04 with eigen3 installed.
I followed the installation guide in the tutorial pages without any errors, however when building the cpp example I am getting include error for Eigen.

The problem is that the Open3D header files refer to the Eigen libraries like this:
#include <Eigen/Core> while it actually should be (in my case) #include <eigen3/Eigen/Core>.

Is there a way of fixing this? I thought of just modifying each header file, however that would not be a good solution. 

Here is the makefile I am using and the build error:
 ```
cmake_minimum_required(VERSION 3.13)
macro(EXAMPLE_CPP EXAMPLE_CPP_NAME)

    add_executable(${EXAMPLE_CPP_NAME} "${EXAMPLE_CPP_NAME}.cpp")
    set(DEPENDENCIES "${ARGN}")
    foreach(DEPENDENCY IN LISTS DEPENDENCIES)
        target_link_libraries(${EXAMPLE_CPP_NAME} ${DEPENDENCY})
    endforeach()

    set_target_properties(${EXAMPLE_CPP_NAME} PROPERTIES
            FOLDER "examples/Cpp/"
            RUNTIME_OUTPUT_DIRECTORY "${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/examples")

endmacro(EXAMPLE_CPP)

EXAMPLE_CPP(Image                     ${CMAKE_PROJECT_NAME})
EXAMPLE_CPP(IntegrateRGBD             ${CMAKE_PROJECT_NAME})
```
[ 25%] Building CXX object CMakeFiles/Image.dir/Image.cpp.o
In file included from /usr/local/include/Open3D/Core/Core.h:30:0,
                 from /home/eruj/CLionProjects/Open3D-test/Image.cpp:29:
/usr/local/include/Open3D/Core/Utility/Console.h:32:10: fatal error: Eigen/Core: No such file or directory
 #include <Eigen/Core>
          ^~~~~~~~~~~~
compilation terminated.
CMakeFiles/Image.dir/build.make:62: recipe for target 'CMakeFiles/Image.dir/Image.cpp.o' failed
make[2]: *** [CMakeFiles/Image.dir/Image.cpp.o] Error 1
CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/Image.dir/all' failed
make[1]: *** [CMakeFiles/Image.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by takanokage** [comment]
Hey Erblinium, what is the goal that you want to accomplish?
Based on that we can try finding a solution for you.

**Comment by Erblinium** [comment]
First I want to visualise/generate pointcloud data from rgb + depth images from a dataset like in https://github.com/thodan/t-less_toolkit/blob/master/doc/t-less_doc.md.

Then as a project I want to implement a PPF algorithm variant  for pose estimation.

**Comment by takanokage** [comment]
Am I correct to assume you want to do this from a C++ project that uses Open3D installed after building from source?

**Comment by Erblinium** [comment]
Yes, you are correct 👍

**Comment by takanokage** [comment]
I'll post this [documentation link](http://open3d.org/docs/tutorial/C++/cplusplus_interface.html) in case you haven't checked that out already.
The link describes how to create your own C++ project based on installed Open3D and provides a CMakeLists.txt example that might work for your purpose.

**Comment by Erblinium** [comment]
Thanks! The CMakeLists.txt now works flawlessly in my C++ project. Should maybe include this CMakeLists.txt file in the C++ examples directory rather the existing one I first failed to use? Or is it for some other build type systems?
