### ISSUE TITLE
Couldn't resolve requests

### ISSUE THREAD

**Issue by iSIlya** [IntelVCL/Open3D#818]
Hello. It is not possible to run the example "realsense_recorder.py". I get this error "realsense_recorder.py", line 104, in <module>
     profile = pipeline.start (config)
RuntimeError: Could not resolve requests "
My configuration: Windows 10, Python 3.6, built by pyrealsense2.cp36-win_amd64.pyd and pyrealsense2.pyd
How to make this example work?
Sorry if such a question has already been asked.

**Comment by syncle** [comment]
Hi @iSIlya. ``realsense_recorder.py`` assumes ``pyrealsense2`` is correctly installed and working. Based on the error message, the issue is related to ``pyrealsense2``, not Open3D. Please visit https://github.com/IntelRealSense/librealsense to find answers.

**Comment by iSIlya** [comment]
@syncle ,
I checked examples with (https://github.com/IntelRealSense/librealsense) and everything works for me, I get images from the camera.

**Comment by syncle** [comment]
That's weird. One possibility is that the camera cannot accept the requested configuration
https://github.com/IntelVCL/Open3D/blob/3af3b81edf9d32b8fbec97e5034ea6354ef658dc/examples/Python/ReconstructionSystem/sensors/realsense_recorder.py#L96-L97
Could you say more about your camera model?

**Comment by iSIlya** [comment]
@syncle ,
Yes. The problem was to resolve the configuration. Fixed it like this
`config.enable_stream (rs.stream.depth, 640, 480, rs.format.z16, 30)`
and it all worked. Thanks you. I use realsense d435.

**Comment by syncle** [comment]
Thanks for sharing your experience with us. d435 is able to stream 1280x720 depth maps as shown in [here](https://click.intel.com/intelr-realsensetm-depth-camera-d435.html), but in some conditions (if ordinal USB cable is used, not high bandwith USB 3.0), it's resolution could be restricted.

**Comment by syncle** [comment]
@iSIlya. Just to give another note:
```
config.enable_stream(rs.stream.depth, 1280, 720, rs.format.z16, 30)
```
was to utilize the original depth frame captured by the camera. 
If the downsampled depth map is requested like the following configuration
```
config.enable_stream(rs.stream.depth, 640, 480, rs.format.z16, 30)
```
The camera will produce **downsampled and blurred depth maps**. I intentionally didn't use this configuration in the example as it harms the reconstruction quality.

**Comment by iSIlya** [comment]
@syncle , ` config.enable_stream(rs.stream.depth, 1280, 720, rs.format.z16, 30)`
With this resolution it worked, after I connected the camera to usb port 3.0. Prior to this, the camera was connected via usb hub, which was also connected through 3.0 and its outputs were also 3.0.

**Comment by iSIlya** [comment]
@syncle , And one more question. When a command is a --record_imgs, does he have to save frames? I have a console output "Depth Scale is:  0.0010000000474974513". Frames are not saved.

**Comment by souctleague** [comment]
thanks,this also solved my problem

**Comment by enescanguven** [comment]
I just recognize that back USB port of my desktop is better. I recommend you to use back USB porst. even if frons usb dock has 3.0 its not worked for my camera.
