### ISSUE TITLE
Pose Graph Optimization throwing segmentation fault

### ISSUE THREAD

**Issue by MrGoort** [IntelVCL/Open3D#825]
Hi there,

I am trying to use the pose graph optimization method but I am getting segmentation fault errors when I am running the GlobalOptimization method.

I've been working with version 0.2.0.0 until last week, and the global optimization was working perfectly, but I have just updated the library to the version 0.5.0.0 and a new segmentation fault error with the same code appeared.

Here is a copy of the input I am adding to the graph:

Node 0 Pose
1 0 0 0
0 1 0 0
0 0 1 0
0 0 0 1
Processed frame: 2 of 4
Node 1 Pose:
           1  0.000348263 -1.22749e-05 -1.43802e-05
 -0.00034822     0.999994   0.00330148 -0.000963371
 1.34246e-05  -0.00330148     0.999994 -9.16485e-05
          -0            0           -0            1
Edge from 1 to 0:
           1  -0.00034822  1.34246e-05  1.40459e-05
 0.000348263     0.999995  -0.00330148  0.000963068
-1.22749e-05   0.00330148     0.999995  9.48284e-05
           0            0            0            1
Information matrix:
   11483 -2.69338   442.59        0 -41586.9   464.12
-2.69338  11363.2 -75.8717  41586.9        0  1661.67
  442.59 -75.8717  381.286  -464.12 -1661.67        0
       0  41586.9  -464.12   154291        0        0
-41586.9        0 -1661.67        0   154291        0
  464.12  1661.67        0        0        0   154291
Processed frame: 3 of 4
Node 2 Pose:
           1  0.000467657 -0.000896341  0.000215826
-0.000464828     0.999995   0.00315407 -0.000912117
 0.000897811  -0.00315365     0.999995 -5.88879e-05
          -0            0           -0            1
Edge from 2 to 1:
           1 -0.000116606  0.000884438 -0.000230261
 0.000116475            1  0.000147516 -5.12707e-05
-0.000884455 -0.000147413            1 -3.27043e-05
           0            0            0            1
Information matrix:
 11566.9 -2.05148  446.643        0 -41859.8  448.367
-2.05148  11443.3 -71.4445  41859.8        0  1676.13
 446.643 -71.4445   387.37 -448.367 -1676.13        0
       0  41859.8 -448.367   155236        0        0
-41859.8        0 -1676.13        0   155236        0
 448.367  1676.13        0        0        0   155236
Processed frame: 4 of 4
Node 3 Pose:
    0.999999    0.0013606  -0.00102324  0.000243003
 -0.00135741     0.999994   0.00311082 -0.000892653
  0.00102747  -0.00310942     0.999995 -8.10445e-05
          -0            0           -0            1
Edge from 3 to 2:
           1 -0.000892541  0.000129679 -2.79627e-05
 0.000892535            1  4.41716e-05 -1.96778e-05
-0.000129718 -4.40559e-05            1  2.21488e-05
           0            0            0            1
Information matrix:
   11634  -2.3825  450.697        0 -42071.6  445.312
 -2.3825  11508.2 -70.4615  42071.6        0  1689.17
 450.697 -70.4615  392.363 -445.312 -1689.17        0
       0  42071.6 -445.312   155938        0        0
-42071.6        0 -1689.17        0   155938        0
 445.312  1689.17        0        0        0   155938
Loop closure transform from 3 to 0:
           1 -0.000650496 -0.000424474  0.000143309
 0.000649141     0.999995   -0.0031849  0.000913324
 0.000426544   0.00318462     0.999995  7.86166e-05
           0            0            0            1
Information matrix:
 11621.7  -2.6175   452.14        0 -42032.7  452.838
 -2.6175  11495.7  -72.773  42032.7        0  1694.58
  452.14  -72.773  392.059 -452.838 -1694.58        0
       0  42032.7 -452.838   155816        0        0
-42032.7        0 -1694.58        0   155816        0
 452.838  1694.58        0        0        0   155816
Validating PoseGraph - finished.
Segmentation fault (core dumped)

As you can see from the transformations, the object and the camera are not moving, so it shouldn't be any problem with the color registration. I have also tried to fill the graph with identity matrices, to see if one of the transformations was wrong and causing problems, but same issue.

Do you have any idea what could be causing the problem?????

Thanks in advance

**Comment by syncle** [comment]
Oh, that's interesting and should be fixed. Please use ``bug report template`` 
**Environment (please complete the following information):**
 - OS: [e.g. OSX Mojave, Ubuntu 16.04, Windows 10.0]
 - Python version: 
 - Open3D version:
 - How did you install Open3D?: pip or conda or build_from_source (provide build method, such as gcc, xcode, visual studio, and so on)
 - Can you provide minimal dataset to reproduce the issue?

**Comment by MrGoort** [comment]
- OS: Ubuntu 16.04
- Python version: 3.7.0, although not using Open3D with Python, I am using the C++ code with C++ 11 and 14
- Open3D: 0.5.0.0
- How did you install Open3D?: build from source using cmake
    Can you provide minimal dataset to reproduce the issue?
see attachment 
[framesClouds.zip](https://github.com/IntelVCL/Open3D/files/2859760/framesClouds.zip)

I have seen other issues that might be related, like ##653, but not entirely sure if it is the case, registration seems to be working on my end.

Please, let me know if you need anything else.

Cheers

**Comment by syncle** [comment]
Thanks @MrGoort, sorry to bother, but can you also share your c++ code as well? I thought you are using Python tutorial example.

**Comment by MrGoort** [comment]
Sorry guys, after several exhaustive debugging sessions, I found out it was another library messing with Open3D. Don't know exactly the reason, but removing that library lets Open3D do its job properly.
Sorry for the confusion, we can close this issue
