### ISSUE TITLE
Object origin/position

### ISSUE THREAD

**Issue by jattiogbe** [IntelVCL/Open3D#826]
Hi,

How do I set the origin /position of an object I create ?
I see _origin_ for **create_mesh_coordinate_frame**, but what's the parameter when i do   **create_mesh_cylinder** or **create_mesh_box** ? origin doesn't work then.

**Comment by syncle** [comment]
all geometry primitives has [0,0,0] as an origin. You can simply try ``transform`` to locate the primitives.
```
    new_origin = [10,10,10]
    transformation = np.identity(4)
    transformation[:3,3] = new_origin
    cylinder = create_mesh_cylinder()
    cylinder.transform(transformation)
```

**Comment by jattiogbe** [comment]
Thanks, this works perfectly.
