### ISSUE TITLE
pythonapi crop point given a 3d bounding box

### ISSUE THREAD

**Issue by bigsheep2012** [IntelVCL/Open3D#852]
hello open3d team,

I have checked #404 and the basic tutorial about crop [here](http://www.open3d.org/docs/tutorial/Basic/pointcloud.html#crop-point-cloud).
I am wandering if there is a python api (other than read a json file) that could let the user  crop the point cloud with a given 3D box or sphere or other shapes?

Thanks in advance.

**Comment by cygerts** [comment]
This would be one of the possible solutions: https://github.com/IntelVCL/Open3D/issues/774

**Comment by yxlao** [comment]
There is a API to do 3D box cropping for point cloud and mesh: http://www.open3d.org/docs/python_api/geometry.html#open3d.geometry.crop_point_cloud, http://www.open3d.org/docs/python_api/geometry.html#open3d.geometry.crop_triangle_mesh .

Here's an example usage: https://github.com/IntelVCL/Open3D/pull/851/files#diff-189e9a6b9063320d7877cf6d8f828060R24

**Comment by bigsheep2012** [comment]
Sorry for late reply. The crop_point_cloud works.
Thanks.
