### ISSUE TITLE
Reading files silently

### ISSUE THREAD

**Issue by chrischoy** [IntelVCL/Open3D#884]
In python, open3d function `read_point_cloud` print out

```
Reading PLY: [========================================] 100%
```

Make the mess in the std out.
Is it necessary? If it is, could you make an option to make it silently load the file?

**Comment by syncle** [comment]
**Solution**

This is a default behavior like you mentioned
```
>>> pcd = read_point_cloud("/Users/jaesikpa/Research/Open3D/examples/TestData/color.ply")
Reading PLY: [========================================] 100%
>>> print(pcd)
PointCloud with 3017 points.
```
You can control all the message comes from Open3D by changing the verbosity level.
Now let's change the level as 0 (only prints error messages)
```
>>> set_verbosity_level(VerbosityLevel.Error)
>>> pcd = read_point_cloud("/Users/jaesikpa/Research/Open3D/examples/TestData/color.ply")
>>>
>>> print(pcd)
PointCloud with 3017 points.
```

**Explanation**

According to this line, you will notice ``PrintConsoleProgress()`` calls ``PrintInfo()`` to display progress bar.
https://github.com/IntelVCL/Open3D/blob/377fc7d6a47ea47681c25a1e07a5383d62a612aa/src/Open3D/Utility/Console.cpp#L108-L111

and there are some definitions on the verbosity level.
https://github.com/IntelVCL/Open3D/blob/377fc7d6a47ea47681c25a1e07a5383d62a612aa/src/Open3D/Utility/Console.h#L38-L44

This means the ``PrintInfo`` will be ignored if the verbosity level is less than 2, and we changed it using ``set_verbosity_level``

**Comment by chrischoy** [comment]
Got it. Thanks!
