### ISSUE TITLE
add noise to a point cloud

### ISSUE THREAD

**Issue by barlaensdoonn** [IntelVCL/Open3D#893]
I am having a very similar problem to this issue: 
#889 

I have written a function to add noise to a numpy array that is structrued as [(x, y, z)], with an arbitrary number of entries in the array. Well after I add noise to it and try to recast it to an open3d PointCloud I get this error:
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-40-a1326a8507eb> in <module>
----> 1 bnyrtd3d = convert_np_to_open3D(bnyrt)

<ipython-input-35-7e947ff71cbf> in convert_np_to_open3D(matrix)
      2     '''this currently doesn't work for pointclouds rotated via rotate_matrix_90_degrees()'''
      3     o3d = open3d.PointCloud()
----> 4     o3d.points = open3d.Vector3dVector(matrix)
      5     return o3d
      6 

RuntimeError: 
```
What am I missing here?

**Environment (please complete the following information):**
 - OS: Ubuntu 16.04
 - Python version: 3.5.2
 - Open3D version: 0.5.0.0
 - Is this remote workstation?: no
 - How did you install Open3D?: pip

**Comment by yxlao** [comment]
What's the output of 
```python
print(matrix.shape)
print(matrix.dtype)
```

**Comment by barlaensdoonn** [comment]
very strange but it worked for me this morning, if I find another reproducible example of it not working I will post it
