### ISSUE TITLE
Visual Studio 2017 migration

### ISSUE THREAD

**Issue by qianyizh** [IntelVCL/Open3D#98]
Need to add Visual Studio 2017 into the tool chain.
Later on, we should setup travis-ci or similar testing systems to test the build of Visual Studio.

**Comment by syncle** [comment]
I have tested with CMake3.1 + Anaconda2 + Win10 + VC2017 environment. It successfully compiled with no warning and error message. Can you elaborate me what issues you had with cmake + gcc compiler?

**Comment by qianyizh** [comment]
Close the ticket since the toolchain has been setup and tested. Good job @syncle
